blocks=(
'▀: Upper half block [Block_Elements]'
'▁: Lower one eighth block [Block_Elements]'
'▂: Lower one quarter block [Block_Elements]'
'▃: Lower three eighths block [Block_Elements]'
'▄: Lower half block [Block_Elements]'
'▅: Lower five eighths block [Block_Elements]'
'▆: Lower three quarters block [Block_Elements]'
'▇: Lower seven eighths block [Block_Elements]'
'█: Full block [Block_Elements]'
'▉: Left seven eighths block [Block_Elements]'
'▊: Left three quarters block [Block_Elements]'
'▋: Left five eighths block [Block_Elements]'
'▌: Left half block [Block_Elements]'
'▍: Left three eighths block [Block_Elements]'
'▎: Left one quarter block [Block_Elements]'
'▏: Left one eighth block [Block_Elements]'
'▐: Right half block [Block_Elements]'
'░: Light shade [Block_Elements]'
'▒: Medium shade [Block_Elements]'
'▓: Dark shade [Block_Elements]'
'▔: Upper one eighth block [Block_Elements]'
'▕: Right one eighth block [Block_Elements]'
'▖: Quadrant lower left [Block_Elements]'
'▗: Quadrant lower right [Block_Elements]'
'▘: Quadrant upper left [Block_Elements]'
'▙: Quadrant upper left and lower left and lower right [Block_Elements]'
'▚: Quadrant upper left and lower right [Block_Elements]'
'▛: Quadrant upper left and upper right and lower left [Block_Elements]'
'▜: Quadrant upper left and upper right and lower right [Block_Elements]'
'▝: Quadrant upper right [Block_Elements]'
'▞: Quadrant upper right and lower left [Block_Elements]'
'▟: Quadrant upper right and lower left and lower right [Block_Elements]'
)
