boxdrawing=(
    '─: box drawings light horizontal [box_drawing]'
    '━: box drawings heavy horizontal [box_drawing]'
    '│: box drawings light vertical [box_drawing]'
    '┃: box drawings heavy vertical [box_drawing]'
    '┄: box drawings light triple dash horizontal [box_drawing]'
    '┅: box drawings heavy triple dash horizontal [box_drawing]'
    '┆: box drawings light triple dash vertical [box_drawing]'
    '┇: box drawings heavy triple dash vertical [box_drawing]'
    '┈: box drawings light quadruple dash horizontal [box_drawing]'
    '┉: box drawings heavy quadruple dash horizontal [box_drawing]'
    '┊: box drawings light quadruple dash vertical [box_drawing]'
    '┋: box drawings heavy quadruple dash vertical [box_drawing]'
    '┌: box drawings light down and right [box_drawing]'
    '┍: box drawings down light and right heavy [box_drawing]'
    '┎: box drawings down heavy and right light [box_drawing]'
    '┏: box drawings heavy down and right [box_drawing]'
    '┐: box drawings light down and left [box_drawing]'
    '┑: box drawings down light and left heavy [box_drawing]'
    '┒: box drawings down heavy and left light [box_drawing]'
    '┓: box drawings heavy down and left [box_drawing]'
    '└: box drawings light up and right [box_drawing]'
    '┕: box drawings up light and right heavy [box_drawing]'
    '┖: box drawings up heavy and right light [box_drawing]'
    '┗: box drawings heavy up and right [box_drawing]'
    '┘: box drawings light up and left [box_drawing]'
    '┙: box drawings up light and left heavy [box_drawing]'
    '┚: box drawings up heavy and left light [box_drawing]'
    '┛: box drawings heavy up and left [box_drawing]'
    '├: box drawings light vertical and right [box_drawing]'
    '┝: box drawings vertical light and right heavy [box_drawing]'
    '┞: box drawings up heavy and right down light [box_drawing]'
    '┟: box drawings down heavy and right up light [box_drawing]'
    '┠: box drawings vertical heavy and right light [box_drawing]'
    '┡: box drawings down light and right up heavy [box_drawing]'
    '┢: box drawings up light and right down heavy [box_drawing]'
    '┣: box drawings heavy vertical and right [box_drawing]'
    '┤: box drawings light vertical and left [box_drawing]'
    '┥: box drawings vertical light and left heavy [box_drawing]'
    '┦: box drawings up heavy and left down light [box_drawing]'
    '┧: box drawings down heavy and left up light [box_drawing]'
    '┨: box drawings vertical heavy and left light [box_drawing]'
    '┩: box drawings down light and left up heavy [box_drawing]'
    '┪: box drawings up light and left down heavy [box_drawing]'
    '┫: box drawings heavy vertical and left [box_drawing]'
    '┬: box drawings light down and horizontal [box_drawing]'
    '┭: box drawings left heavy and right down light [box_drawing]'
    '┮: box drawings right heavy and left down light [box_drawing]'
    '┯: box drawings down light and horizontal heavy [box_drawing]'
    '┰: box drawings down heavy and horizontal light [box_drawing]'
    '┱: box drawings right light and left down heavy [box_drawing]'
    '┲: box drawings left light and right down heavy [box_drawing]'
    '┳: box drawings heavy down and horizontal [box_drawing]'
    '┴: box drawings light up and horizontal [box_drawing]'
    '┵: box drawings left heavy and right up light [box_drawing]'
    '┶: box drawings right heavy and left up light [box_drawing]'
    '┷: box drawings up light and horizontal heavy [box_drawing]'
    '┸: box drawings up heavy and horizontal light [box_drawing]'
    '┹: box drawings right light and left up heavy [box_drawing]'
    '┺: box drawings left light and right up heavy [box_drawing]'
    '┻: box drawings heavy up and horizontal [box_drawing]'
    '┼: box drawings light vertical and horizontal [box_drawing]'
    '┽: box drawings left heavy and right vertical light [box_drawing]'
    '┾: box drawings right heavy and left vertical light [box_drawing]'
    '┿: box drawings vertical light and horizontal heavy [box_drawing]'
    '╀: box drawings up heavy and down horizontal light [box_drawing]'
    '╁: box drawings down heavy and up horizontal light [box_drawing]'
    '╂: box drawings vertical heavy and horizontal light [box_drawing]'
    '╃: box drawings left up heavy and right down light [box_drawing]'
    '╄: box drawings right up heavy and left down light [box_drawing]'
    '╅: box drawings left down heavy and right up light [box_drawing]'
    '╆: box drawings right down heavy and left up light [box_drawing]'
    '╇: box drawings down light and up horizontal heavy [box_drawing]'
    '╈: box drawings up light and down horizontal heavy [box_drawing]'
    '╉: box drawings right light and left vertical heavy [box_drawing]'
    '╊: box drawings left light and right vertical heavy [box_drawing]'
    '╋: box drawings heavy vertical and horizontal [box_drawing]'
    '╌: box drawings light double dash horizontal [box_drawing]'
    '╍: box drawings heavy double dash horizontal [box_drawing]'
    '╎: box drawings light double dash vertical [box_drawing]'
    '╏: box drawings heavy double dash vertical [box_drawing]'
    '═: box drawings double horizontal [box_drawing]'
    '║: box drawings double vertical [box_drawing]'
    '╒: box drawings down single and right double [box_drawing]'
    '╓: box drawings down double and right single [box_drawing]'
    '╔: box drawings double down and right [box_drawing]'
    '╕: box drawings down single and left double [box_drawing]'
    '╖: box drawings down double and left single [box_drawing]'
    '╗: box drawings double down and left [box_drawing]'
    '╘: box drawings up single and right double [box_drawing]'
    '╙: box drawings up double and right single [box_drawing]'
    '╚: box drawings double up and right [box_drawing]'
    '╛: box drawings up single and left double [box_drawing]'
    '╜: box drawings up double and left single [box_drawing]'
    '╝: box drawings double up and left [box_drawing]'
    '╞: box drawings vertical single and right double [box_drawing]'
    '╟: box drawings vertical double and right single [box_drawing]'
    '╠: box drawings double vertical and right [box_drawing]'
    '╡: box drawings vertical single and left double [box_drawing]'
    '╢: box drawings vertical double and left single [box_drawing]'
    '╣: box drawings double vertical and left [box_drawing]'
    '╤: box drawings down single and horizontal double [box_drawing]'
    '╥: box drawings down double and horizontal single [box_drawing]'
    '╦: box drawings double down and horizontal [box_drawing]'
    '╧: box drawings up single and horizontal double [box_drawing]'
    '╨: box drawings up double and horizontal single [box_drawing]'
    '╩: box drawings double up and horizontal [box_drawing]'
    '╪: box drawings vertical single and horizontal double [box_drawing]'
    '╫: box drawings vertical double and horizontal single [box_drawing]'
    '╬: box drawings double vertical and horizontal [box_drawing]'
    '╭: box drawings light arc down and right [box_drawing]'
    '╮: box drawings light arc down and left [box_drawing]'
    '╯: box drawings light arc up and left [box_drawing]'
    '╰: box drawings light arc up and right [box_drawing]'
    '╱: box drawings light diagonal upper right to lower left [box_drawing]'
    '╲: box drawings light diagonal upper left to lower right [box_drawing]'
    '╳: box drawings light diagonal cross [box_drawing]'
    '╴: box drawings light left [box_drawing]'
    '╵: box drawings light up [box_drawing]'
    '╶: box drawings light right [box_drawing]'
    '╷: box drawings light down [box_drawing]'
    '╸: box drawings heavy left [box_drawing]'
    '╹: box drawings heavy up [box_drawing]'
    '╺: box drawings heavy right [box_drawing]'
    '╻: box drawings heavy down [box_drawing]'
    '╼: box drawings light left and heavy right [box_drawing]'
    '╽: box drawings light up and heavy down [box_drawing]'
    '╾: box drawings heavy left and light right [box_drawing]'
    '╿: box drawings heavy up and light down [box_drawing]'
)
