emojis=(
'😀: grinning face [face | grin | grinning face]'
'😁: beaming face with smiling eyes [beaming face with smiling eyes | eye | face | grin | smile]'
'😂: face with tears of joy [face | face with tears of joy | joy | laugh | tear]'
'🤣: rolling on the floor laughing [face | floor | laugh | rolling | rolling on the floor laughing]'
'😃: grinning face with big eyes [face | grinning face with big eyes | mouth | open | smile]'
'😄: grinning face with smiling eyes [eye | face | grinning face with smiling eyes | mouth | open | smile]'
'😅: grinning face with sweat [cold | face | grinning face with sweat | open | smile | sweat]'
'😆: grinning squinting face [face | grinning squinting face | laugh | mouth | open | satisfied | smile]'
'😉: winking face [face | wink | winking face]'
'😊: smiling face with smiling eyes [blush | eye | face | smile | smiling face with smiling eyes]'
'😋: face savoring food [delicious | face | face savoring food | savouring | smile | um | yum]'
'😎: smiling face with sunglasses [bright | cool | eye | eyewear | face | glasses | smile | smiling face with sunglasses | sun | sunglasses]'
'😍: smiling face with heart-eyes [eye | face | love | smile | smiling face with heart-eyes]'
'😘: face blowing a kiss [face | face blowing a kiss | kiss]'
'🥰: ⊛ smiling face with 3 hearts [adore | crush | in love]'
'😗: kissing face [face | kiss | kissing face]'
'😙: kissing face with smiling eyes [eye | face | kiss | kissing face with smiling eyes | smile]'
'😚: kissing face with closed eyes [closed | eye | face | kiss | kissing face with closed eyes]'
'☺: smiling face [face | outlined | relaxed | smile | smiling face]'
'🙂: slightly smiling face [face | slightly smiling face | smile]'
'🤗: hugging face [face | hug | hugging]'
'🤩: star-struck [eyes | face | grinning | star | star-struck | starry-eyed]'
'🤔: thinking face [face | thinking]'
'🤨: face with raised eyebrow [distrust | face with raised eyebrow | skeptic | disapproval | disbelief | mild surprise | scepticism]'
'😐: neutral face [deadpan | face | neutral]'
'😑: expressionless face [expressionless | face | inexpressive | unexpressive]'
'😶: face without mouth [face | face without mouth | mouth | quiet | silent]'
'🙄: face with rolling eyes [eyes | face | face with rolling eyes | rolling]'
'😏: smirking face [face | smirk | smirking face]'
'😣: persevering face [face | persevere | persevering face]'
'😥: sad but relieved face [disappointed | face | relieved | sad but relieved face | whew]'
'😮: face with open mouth [face | face with open mouth | mouth | open | sympathy]'
'🤐: zipper-mouth face [face | mouth | zipper | zipper-mouth face]'
'😯: hushed face [face | hushed | stunned | surprised]'
'😪: sleepy face [face | sleep | sleepy face]'
'😫: tired face [face | tired]'
'😴: sleeping face [face | sleep | sleeping face | zzz]'
'😌: relieved face [face | relieved]'
'😛: face with tongue [face | face with tongue | tongue]'
'😜: winking face with tongue [eye | face | joke | tongue | wink | winking face with tongue]'
'😝: squinting face with tongue [eye | face | horrible | squinting face with tongue | taste | tongue]'
'🤤: drooling face [drooling | face]'
'😒: unamused face [face | unamused | unhappy]'
'😓: downcast face with sweat [cold | downcast face with sweat | face | sweat]'
'😔: pensive face [dejected | face | pensive]'
'😕: confused face [confused | face]'
'🙃: upside-down face [face | upside-down]'
'🤑: money-mouth face [face | money | money-mouth face | mouth]'
'😲: astonished face [astonished | face | shocked | totally]'
'☹: frowning face [face | frown | frowning face]'
'🙁: slightly frowning face [face | frown | slightly frowning face]'
'😖: confounded face [confounded | face]'
'😞: disappointed face [disappointed | face]'
'😟: worried face [face | worried]'
'😤: face with steam from nose [face | face with steam from nose | triumph | won]'
'😢: crying face [cry | crying face | face | sad | tear]'
'😭: loudly crying face [cry | face | loudly crying face | sad | sob | tear]'
'😦: frowning face with open mouth [face | frown | frowning face with open mouth | mouth | open]'
'😧: anguished face [anguished | face]'
'😨: fearful face [face | fear | fearful | scared]'
'😩: weary face [face | tired | weary]'
'🤯: exploding head [exploding head | shocked]'
'😬: grimacing face [face | grimace | grimacing face]'
'😰: anxious face with sweat [anxious face with sweat | blue | cold | face | mouth | open | rushed | sweat]'
'😱: face screaming in fear [face | face screaming in fear | fear | fearful | munch | scared | scream]'
'🥵: ⊛ hot face [feverish | heat stroke | hot | red-faced | sweating]'
'🥶: ⊛ cold face [blue-faced | cold | freezing | frostbite | icicles]'
'😳: flushed face [dazed | face | flushed]'
'🤪: zany face [eye | goofy | large | small | zany face]'
'😵: dizzy face [dizzy | face]'
'😡: pouting face [angry | face | mad | pouting | rage | red]'
'😠: angry face [angry | face | mad]'
'🤬: face with symbols on mouth [face with symbols on mouth | swearing | cursing]'
'😷: face with medical mask [cold | doctor | face | face with medical mask | mask | medicine | sick]'
'🤒: face with thermometer [face | face with thermometer | ill | sick | thermometer]'
'🤕: face with head-bandage [bandage | face | face with head-bandage | hurt | injury]'
'🤢: nauseated face [face | nauseated | vomit]'
'🤮: face vomiting [face vomiting | sick | vomit]'
'🤧: sneezing face [face | gesundheit | sneeze | sneezing face]'
'😇: smiling face with halo [angel | face | fairy tale | fantasy | halo | innocent | smile | smiling face with halo]'
'🤠: cowboy hat face [cowboy | cowgirl | face | hat]'
'🥳: ⊛ partying face [celebration | hat | horn | party]'
'🥴: ⊛ woozy face [dizzy | intoxicated | tipsy | uneven eyes | wavy mouth]'
'🥺: ⊛ pleading face [begging | mercy | puppy eyes]'
'🤥: lying face [face | lie | lying face | pinocchio]'
'🤫: shushing face [quiet | shush | shushing face]'
'🤭: face with hand over mouth [face with hand over mouth | whoops | shock | sudden realization | surprise]'
'🧐: face with monocle [face with monocle | stuffy | wealthy]'
'🤓: nerd face [face | geek | nerd]'
'😈: smiling face with horns [face | fairy tale | fantasy | horns | smile | smiling face with horns]'
'👿: angry face with horns [angry face with horns | demon | devil | face | fairy tale | fantasy | imp]'
'🤡: clown face [clown | face]'
'👹: ogre [creature | face | fairy tale | fantasy | monster | ogre | troll]'
'👺: goblin [creature | face | fairy tale | fantasy | goblin | monster]'
'💀: skull [death | face | fairy tale | monster | skull]'
'☠: skull and crossbones [crossbones | death | face | monster | skull | skull and crossbones]'
'👻: ghost [creature | face | fairy tale | fantasy | ghost | monster]'
'👽: alien [alien | creature | extraterrestrial | face | fairy tale | fantasy | monster | ufo]'
'👾: alien monster [alien | creature | extraterrestrial | face | fairy tale | fantasy | monster | ufo]'
'🤖: robot face [face | monster | robot]'
'💩: pile of poo [comic | dung | face | monster | pile of poo | poo | poop]'
'😺: grinning cat face [cat | face | grinning cat face | mouth | open | smile]'
'😸: grinning cat face with smiling eyes [cat | eye | face | grin | grinning cat face with smiling eyes | smile]'
'😹: cat face with tears of joy [cat | cat face with tears of joy | face | joy | tear]'
'😻: smiling cat face with heart-eyes [cat | eye | face | love | smile | smiling cat face with heart-eyes]'
'😼: cat face with wry smile [cat | cat face with wry smile | face | ironic | smile | wry]'
'😽: kissing cat face [cat | eye | face | kiss | kissing cat face]'
'🙀: weary cat face [cat | face | oh | surprised | weary]'
'😿: crying cat face [cat | cry | crying cat face | face | sad | tear]'
'😾: pouting cat face [cat | face | pouting]'
'🙈: see-no-evil monkey [evil | face | forbidden | gesture | monkey | no | not | prohibited | see | see-no-evil monkey]'
'🙉: hear-no-evil monkey [evil | face | forbidden | gesture | hear | hear-no-evil monkey | monkey | no | not | prohibited]'
'🙊: speak-no-evil monkey [evil | face | forbidden | gesture | monkey | no | not | prohibited | speak | speak-no-evil monkey]'
'👶: baby [baby | young]'
'🧒: child [child | gender-neutral | young | (no specific gender)]'
'👦: boy [boy | young]'
'👧: girl [girl | Virgo | young | zodiac]'
'🧑: adult [adult | gender-neutral | (no specific gender)]'
'👨: man [man]'
'👩: woman [woman]'
'🧓: older adult [gender-neutral | old | older adult | (no specific gender)]'
'👴: old man [man | old]'
'👵: old woman [old | woman]'
'👨‍⚕️: man health worker [doctor | healthcare | man | man health worker | nurse | therapist]'
'👩‍⚕️: woman health worker [doctor | healthcare | nurse | therapist | woman | woman health worker]'
'👨‍🎓: man student [graduate | man | student]'
'👩‍🎓: woman student [graduate | student | woman]'
'👨‍🏫: man teacher [instructor | man | professor | teacher]'
'👩‍🏫: woman teacher [instructor | professor | teacher | woman]'
'👨‍⚖️: man judge [justice | man | man judge | scales]'
'👩‍⚖️: woman judge [judge | scales | woman]'
'👨‍🌾: man farmer [farmer | gardener | man | rancher]'
'👩‍🌾: woman farmer [farmer | gardener | rancher | woman]'
'👨‍🍳: man cook [chef | cook | man]'
'👩‍🍳: woman cook [chef | cook | woman]'
'👨‍🔧: man mechanic [electrician | man | mechanic | plumber | tradesperson]'
'👩‍🔧: woman mechanic [electrician | mechanic | plumber | tradesperson | woman]'
'👨‍🏭: man factory worker [assembly | factory | industrial | man | worker]'
'👩‍🏭: woman factory worker [assembly | factory | industrial | woman | worker]'
'👨‍💼: man office worker [architect | business | man | man office worker | manager | office | white-collar]'
'👩‍💼: woman office worker [architect | business | manager | office | white-collar | woman | woman office worker]'
'👨‍🔬: man scientist [biologist | chemist | engineer | man | mathematician | physicist | scientist]'
'👩‍🔬: woman scientist [biologist | chemist | engineer | mathematician | physicist | scientist | woman]'
'👨‍💻: man technologist [coder | developer | inventor | man | software | technologist]'
'👩‍💻: woman technologist [coder | developer | inventor | software | technologist | woman]'
'👨‍🎤: man singer [actor | entertainer | man | rock | singer | star]'
'👩‍🎤: woman singer [actor | entertainer | rock | singer | star | woman]'
'👨‍🎨: man artist [artist | man | palette]'
'👩‍🎨: woman artist [artist | palette | woman]'
'👨‍✈️: man pilot [man | pilot | plane]'
'👩‍✈️: woman pilot [pilot | plane | woman]'
'👨‍🚀: man astronaut [astronaut | man | rocket]'
'👩‍🚀: woman astronaut [astronaut | rocket | woman]'
'👨‍🚒: man firefighter [firefighter | firetruck | man]'
'👩‍🚒: woman firefighter [firefighter | firetruck | woman]'
'👮: police officer [cop | officer | police]'
'👮‍♂️: man police officer [cop | man | officer | police]'
'👮‍♀️: woman police officer [cop | officer | police | woman]'
'🕵: detective [detective | sleuth | spy]'
'🕵️‍♂️: man detective [detective | man | sleuth | spy]'
'🕵️‍♀️: woman detective [detective | sleuth | spy | woman]'
'💂: guard [guard]'
'💂‍♂️: man guard [guard | man]'
'💂‍♀️: woman guard [guard | woman]'
'👷: construction worker [construction | hat | worker]'
'👷‍♂️: man construction worker [construction | man | worker]'
'👷‍♀️: woman construction worker [construction | woman | worker]'
'🤴: prince [prince]'
'👸: princess [fairy tale | fantasy | princess]'
'👳: person wearing turban [person wearing turban | turban]'
'👳‍♂️: man wearing turban [man | man wearing turban | turban]'
'👳‍♀️: woman wearing turban [turban | woman | woman wearing turban]'
'👲: man with Chinese cap [gua pi mao | hat | man | man with Chinese cap]'
'🧕: woman with headscarf [headscarf | hijab | mantilla | tichel | woman with headscarf | bandana | head kerchief]'
'🧔: bearded person [beard | bearded person | bewhiskered]'
'👱: blond-haired person [blond | blond-haired person]'
'👱‍♂️: blond-haired man [blond | blond-haired man | man]'
'👱‍♀️: blond-haired woman [blond-haired woman | blonde | woman]'
'👨‍🦰: ⊛ man, red haired []'
'👩‍🦰: ⊛ woman, red haired []'
'👨‍🦱: ⊛ man, curly haired []'
'👩‍🦱: ⊛ woman, curly haired []'
'👨‍🦲: ⊛ man, bald []'
'👩‍🦲: ⊛ woman, bald []'
'👨‍🦳: ⊛ man, white haired []'
'👩‍🦳: ⊛ woman, white haired []'
'🤵: man in tuxedo [groom | man | man in tuxedo | tuxedo]'
'👰: bride with veil [bride | bride with veil | veil | wedding]'
'🤰: pregnant woman [pregnant | woman]'
'🤱: breast-feeding [baby | breast | breast-feeding | nursing]'
'👼: baby angel [angel | baby | face | fairy tale | fantasy]'
'🎅: Santa Claus [celebration | Christmas | claus | father | santa | Santa Claus]'
'🤶: Mrs. Claus [celebration | Christmas | claus | mother | Mrs. | Mrs. Claus]'
'🦸: ⊛ superhero [good | hero | heroine | superpowers]'
'🦸‍♀️: ⊛ woman superhero []'
'🦸‍♂️: ⊛ man superhero []'
'🦹: ⊛ supervillain [bad | criminal | evil | superpowers | villain]'
'🦹‍♀️: ⊛ woman supervillain []'
'🦹‍♂️: ⊛ man supervillain []'
'🧙: mage [mage | sorcerer | sorceress | witch | wizard]'
'🧙‍♀️: woman mage [sorceress | witch | woman mage]'
'🧙‍♂️: man mage [man mage | sorcerer | wizard]'
'🧚: fairy [fairy | Oberon | Puck | Titania]'
'🧚‍♀️: woman fairy [Titania | woman fairy]'
'🧚‍♂️: man fairy [man fairy | Oberon | Puck]'
'🧛: vampire [Dracula | undead | vampire]'
'🧛‍♀️: woman vampire [undead | woman vampire]'
'🧛‍♂️: man vampire [Dracula | man vampire | undead]'
'🧜: merperson [mermaid | merman | merperson | merwoman]'
'🧜‍♀️: mermaid [mermaid | merwoman]'
'🧜‍♂️: merman [merman | Triton]'
'🧝: elf [elf | magical | LOTR style]'
'🧝‍♀️: woman elf [magical | woman elf]'
'🧝‍♂️: man elf [magical | man elf]'
'🧞: genie [djinn | genie | (non-human color)]'
'🧞‍♀️: woman genie [djinn | woman genie]'
'🧞‍♂️: man genie [djinn | man genie]'
'🧟: zombie [undead | walking dead | zombie | (non-human color)]'
'🧟‍♀️: woman zombie [undead | walking dead | woman zombie]'
'🧟‍♂️: man zombie [man zombie | undead | walking dead]'
'🙍: person frowning [frown | gesture | person frowning]'
'🙍‍♂️: man frowning [frowning | gesture | man]'
'🙍‍♀️: woman frowning [frowning | gesture | woman]'
'🙎: person pouting [gesture | person pouting | pouting]'
'🙎‍♂️: man pouting [gesture | man | pouting]'
'🙎‍♀️: woman pouting [gesture | pouting | woman]'
'🙅: person gesturing NO [forbidden | gesture | hand | no | not | person gesturing NO | prohibited]'
'🙅‍♂️: man gesturing NO [forbidden | gesture | hand | man | man gesturing NO | no | prohibited]'
'🙅‍♀️: woman gesturing NO [forbidden | gesture | hand | no | prohibited | woman | woman gesturing NO]'
'🙆: person gesturing OK [gesture | hand | OK | person gesturing OK]'
'🙆‍♂️: man gesturing OK [gesture | hand | man | man gesturing OK | OK]'
'🙆‍♀️: woman gesturing OK [gesture | hand | OK | woman | woman gesturing OK]'
'💁: person tipping hand [hand | help | information | person tipping hand | sassy | tipping]'
'💁‍♂️: man tipping hand [man | man tipping hand | sassy | tipping hand]'
'💁‍♀️: woman tipping hand [sassy | tipping hand | woman | woman tipping hand]'
'🙋: person raising hand [gesture | hand | happy | person raising hand | raised]'
'🙋‍♂️: man raising hand [gesture | man | man raising hand | raising hand]'
'🙋‍♀️: woman raising hand [gesture | raising hand | woman | woman raising hand]'
'🙇: person bowing [apology | bow | gesture | person bowing | sorry]'
'🙇‍♂️: man bowing [apology | bowing | favor | gesture | man | sorry]'
'🙇‍♀️: woman bowing [apology | bowing | favor | gesture | sorry | woman]'
'🤦: person facepalming [disbelief | exasperation | face | palm | person facepalming]'
'🤦‍♂️: man facepalming [disbelief | exasperation | facepalm | man | man facepalming]'
'🤦‍♀️: woman facepalming [disbelief | exasperation | facepalm | woman | woman facepalming]'
'🤷: person shrugging [doubt | ignorance | indifference | person shrugging | shrug]'
'🤷‍♂️: man shrugging [doubt | ignorance | indifference | man | man shrugging | shrug]'
'🤷‍♀️: woman shrugging [doubt | ignorance | indifference | shrug | woman | woman shrugging]'
'💆: person getting massage [face | massage | person getting massage | salon]'
'💆‍♂️: man getting massage [face | man | man getting massage | massage]'
'💆‍♀️: woman getting massage [face | massage | woman | woman getting massage]'
'💇: person getting haircut [barber | beauty | haircut | parlor | person getting haircut]'
'💇‍♂️: man getting haircut [haircut | man | man getting haircut]'
'💇‍♀️: woman getting haircut [haircut | woman | woman getting haircut]'
'🚶: person walking [hike | person walking | walk | walking]'
'🚶‍♂️: man walking [hike | man | man walking | walk]'
'🚶‍♀️: woman walking [hike | walk | woman | woman walking]'
'🏃: person running [marathon | person running | running]'
'🏃‍♂️: man running [man | marathon | racing | running]'
'🏃‍♀️: woman running [marathon | racing | running | woman]'
'💃: woman dancing [dancing | woman]'
'🕺: man dancing [dance | man | man dancing]'
'👯: people with bunny ears [bunny ear | dancer | partying | people with bunny ears]'
'👯‍♂️: men with bunny ears [bunny ear | dancer | men | men with bunny ears | partying]'
'👯‍♀️: women with bunny ears [bunny ear | dancer | partying | women | women with bunny ears]'
'🧖: person in steamy room [person in steamy room | sauna | steam room | hamam | steambath]'
'🧖‍♀️: woman in steamy room [sauna | steam room | woman in steamy room]'
'🧖‍♂️: man in steamy room [man in steamy room | sauna | steam room]'
'🧗: person climbing [climber | person climbing]'
'🧗‍♀️: woman climbing [climber | woman climbing]'
'🧗‍♂️: man climbing [climber | man climbing]'
'🧘: person in lotus position [meditation | person in lotus position | yoga | serenity]'
'🧘‍♀️: woman in lotus position [meditation | woman in lotus position | yoga]'
'🧘‍♂️: man in lotus position [man in lotus position | meditation | yoga]'
'🛀: person taking bath [bath | bathtub | person taking bath]'
'🛌: person in bed [hotel | person in bed | sleep]'
'🕴: man in suit levitating [business | man | man in suit levitating | suit]'
'🗣: speaking head [face | head | silhouette | speak | speaking]'
'👤: bust in silhouette [bust | bust in silhouette | silhouette]'
'👥: busts in silhouette [bust | busts in silhouette | silhouette]'
'🤺: person fencing [fencer | fencing | person fencing | sword]'
'🏇: horse racing [horse | jockey | racehorse | racing]'
'⛷: skier [ski | skier | snow]'
'🏂: snowboarder [ski | snow | snowboard | snowboarder]'
'🏌: person golfing [ball | golf | person golfing]'
'🏌️‍♂️: man golfing [golf | man | man golfing]'
'🏌️‍♀️: woman golfing [golf | woman | woman golfing]'
'🏄: person surfing [person surfing | surfing]'
'🏄‍♂️: man surfing [man | surfing]'
'🏄‍♀️: woman surfing [surfing | woman]'
'🚣: person rowing boat [boat | person rowing boat | rowboat]'
'🚣‍♂️: man rowing boat [boat | man | man rowing boat | rowboat]'
'🚣‍♀️: woman rowing boat [boat | rowboat | woman | woman rowing boat]'
'🏊: person swimming [person swimming | swim]'
'🏊‍♂️: man swimming [man | man swimming | swim]'
'🏊‍♀️: woman swimming [swim | woman | woman swimming]'
'⛹: person bouncing ball [ball | person bouncing ball]'
'⛹️‍♂️: man bouncing ball [ball | man | man bouncing ball]'
'⛹️‍♀️: woman bouncing ball [ball | woman | woman bouncing ball]'
'🏋: person lifting weights [lifter | person lifting weights | weight]'
'🏋️‍♂️: man lifting weights [man | man lifting weights | weight lifter]'
'🏋️‍♀️: woman lifting weights [weight lifter | woman | woman lifting weights]'
'🚴: person biking [bicycle | biking | cyclist | person biking]'
'🚴‍♂️: man biking [bicycle | biking | cyclist | man]'
'🚴‍♀️: woman biking [bicycle | biking | cyclist | woman]'
'🚵: person mountain biking [bicycle | bicyclist | bike | cyclist | mountain | person mountain biking]'
'🚵‍♂️: man mountain biking [bicycle | bike | cyclist | man | man mountain biking | mountain]'
'🚵‍♀️: woman mountain biking [bicycle | bike | biking | cyclist | mountain | woman]'
'🏎: racing car [car | racing]'
'🏍: motorcycle [motorcycle | racing]'
'🤸: person cartwheeling [cartwheel | gymnastics | person cartwheeling]'
'🤸‍♂️: man cartwheeling [cartwheel | gymnastics | man | man cartwheeling]'
'🤸‍♀️: woman cartwheeling [cartwheel | gymnastics | woman | woman cartwheeling]'
'🤼: people wrestling [people wrestling | wrestle | wrestler]'
'🤼‍♂️: men wrestling [men | men wrestling | wrestle]'
'🤼‍♀️: women wrestling [women | women wrestling | wrestle]'
'🤽: person playing water polo [person playing water polo | polo | water]'
'🤽‍♂️: man playing water polo [man | man playing water polo | water polo]'
'🤽‍♀️: woman playing water polo [water polo | woman | woman playing water polo]'
'🤾: person playing handball [ball | handball | person playing handball]'
'🤾‍♂️: man playing handball [handball | man | man playing handball]'
'🤾‍♀️: woman playing handball [handball | woman | woman playing handball]'
'🤹: person juggling [balance | juggle | multitask | person juggling | skill]'
'🤹‍♂️: man juggling [juggling | man | multitask]'
'🤹‍♀️: woman juggling [juggling | multitask | woman]'
'👫: man and woman holding hands [couple | hand | hold | man | man and woman holding hands | woman]'
'👬: two men holding hands [couple | Gemini | hand | hold | man | twins | two men holding hands | zodiac]'
'👭: two women holding hands [couple | hand | hold | two women holding hands | woman]'
'💏: kiss [couple | kiss]'
'👩‍❤️‍💋‍👨: kiss: woman, man [couple | kiss | man | woman]'
'👨‍❤️‍💋‍👨: kiss: man, man [couple | kiss | man]'
'👩‍❤️‍💋‍👩: kiss: woman, woman [couple | kiss | woman]'
'💑: couple with heart [couple | couple with heart | love]'
'👩‍❤️‍👨: couple with heart: woman, man [couple | couple with heart | love | man | woman]'
'👨‍❤️‍👨: couple with heart: man, man [couple | couple with heart | love | man]'
'👩‍❤️‍👩: couple with heart: woman, woman [couple | couple with heart | love | woman]'
'👪: family [family]'
'👨‍👩‍👦: family: man, woman, boy [boy | family | man | woman]'
'👨‍👩‍👧: family: man, woman, girl [family | girl | man | woman]'
'👨‍👩‍👧‍👦: family: man, woman, girl, boy [boy | family | girl | man | woman]'
'👨‍👩‍👦‍👦: family: man, woman, boy, boy [boy | family | man | woman]'
'👨‍👩‍👧‍👧: family: man, woman, girl, girl [family | girl | man | woman]'
'👨‍👨‍👦: family: man, man, boy [boy | family | man]'
'👨‍👨‍👧: family: man, man, girl [family | girl | man]'
'👨‍👨‍👧‍👦: family: man, man, girl, boy [boy | family | girl | man]'
'👨‍👨‍👦‍👦: family: man, man, boy, boy [boy | family | man]'
'👨‍👨‍👧‍👧: family: man, man, girl, girl [family | girl | man]'
'👩‍👩‍👦: family: woman, woman, boy [boy | family | woman]'
'👩‍👩‍👧: family: woman, woman, girl [family | girl | woman]'
'👩‍👩‍👧‍👦: family: woman, woman, girl, boy [boy | family | girl | woman]'
'👩‍👩‍👦‍👦: family: woman, woman, boy, boy [boy | family | woman]'
'👩‍👩‍👧‍👧: family: woman, woman, girl, girl [family | girl | woman]'
'👨‍👦: family: man, boy [boy | family | man]'
'👨‍👦‍👦: family: man, boy, boy [boy | family | man]'
'👨‍👧: family: man, girl [family | girl | man]'
'👨‍👧‍👦: family: man, girl, boy [boy | family | girl | man]'
'👨‍👧‍👧: family: man, girl, girl [family | girl | man]'
'👩‍👦: family: woman, boy [boy | family | woman]'
'👩‍👦‍👦: family: woman, boy, boy [boy | family | woman]'
'👩‍👧: family: woman, girl [family | girl | woman]'
'👩‍👧‍👦: family: woman, girl, boy [boy | family | girl | woman]'
'👩‍👧‍👧: family: woman, girl, girl [family | girl | woman]'
'🤳: selfie [camera | phone | selfie]'
'💪: flexed biceps [biceps | comic | flex | flexed biceps | muscle]'
'🦵: ⊛ leg [kick | limb]'
'🦶: ⊛ foot [kick | stomp]'
'👈: backhand index pointing left [backhand | backhand index pointing left | finger | hand | index | point]'
'👉: backhand index pointing right [backhand | backhand index pointing right | finger | hand | index | point]'
'☝: index pointing up [finger | hand | index | index pointing up | point | up]'
'👆: backhand index pointing up [backhand | backhand index pointing up | finger | hand | index | point | up]'
'🖕: middle finger [finger | hand | middle finger]'
'👇: backhand index pointing down [backhand | backhand index pointing down | down | finger | hand | index | point]'
'✌: victory hand [hand | v | victory]'
'🤞: crossed fingers [cross | crossed fingers | finger | hand | luck]'
'🖖: vulcan salute [finger | hand | spock | vulcan | vulcan salute]'
'🤘: sign of the horns [finger | hand | horns | rock-on | sign of the horns]'
'🤙: call me hand [call | call me hand | hand]'
'🖐: hand with fingers splayed [finger | hand | hand with fingers splayed | splayed]'
'✋: raised hand [hand | raised hand]'
'👌: OK hand [hand | OK]'
'👍: thumbs up [+1 | hand | thumb | thumbs up | up]'
'👎: thumbs down [-1 | down | hand | thumb | thumbs down]'
'✊: raised fist [clenched | fist | hand | punch | raised fist]'
'👊: oncoming fist [clenched | fist | hand | oncoming fist | punch]'
'🤛: left-facing fist [fist | left-facing fist | leftwards]'
'🤜: right-facing fist [fist | right-facing fist | rightwards]'
'🤚: raised back of hand [backhand | raised | raised back of hand]'
'👋: waving hand [hand | wave | waving]'
'🤟: love-you gesture [hand | ILY | love-you gesture]'
'✍: writing hand [hand | write | writing hand]'
'👏: clapping hands [clap | clapping hands | hand]'
'👐: open hands [hand | open | open hands]'
'🙌: raising hands [celebration | gesture | hand | hooray | raised | raising hands]'
'🤲: palms up together [palms up together | prayer | cupped hands]'
'🙏: folded hands [ask | bow | folded | folded hands | gesture | hand | please | pray | thanks]'
'🤝: handshake [agreement | hand | handshake | meeting | shake]'
'💅: nail polish [care | cosmetics | manicure | nail | polish]'
'👂: ear [body | ear]'
'👃: nose [body | nose]'
'🦰: ⊛ red-haired [ginger | redhead]'
'🦱: ⊛ curly-haired [afro | curly | ringlets]'
'🦲: ⊛ bald [chemotherapy | hairless | no hair | shaven]'
'🦳: ⊛ white-haired [gray | hair | old | white]'
'👣: footprints [clothing | footprint | footprints | print]'
'👀: eyes [eye | eyes | face]'
'👁: eye [body | eye]'
'👁️‍🗨️: eye in speech bubble [eye | eye in speech bubble | speech bubble | witness]'
'🧠: brain [brain | intelligent]'
'🦴: ⊛ bone [skeleton]'
'🦷: ⊛ tooth [dentist]'
'👅: tongue [body | tongue]'
'👄: mouth [lips | mouth]'
'💋: kiss mark [kiss | kiss mark | lips]'
'💘: heart with arrow [arrow | cupid | heart with arrow]'
'❤: red heart [heart | red heart]'
'💓: beating heart [beating | beating heart | heartbeat | pulsating]'
'💔: broken heart [break | broken | broken heart]'
'💕: two hearts [love | two hearts]'
'💖: sparkling heart [excited | sparkle | sparkling heart]'
'💗: growing heart [excited | growing | growing heart | nervous | pulse]'
'💙: blue heart [blue | blue heart]'
'💚: green heart [green | green heart]'
'💛: yellow heart [yellow | yellow heart]'
'🧡: orange heart [orange | orange heart]'
'💜: purple heart [purple | purple heart]'
'🖤: black heart [black | black heart | evil | wicked]'
'💝: heart with ribbon [heart with ribbon | ribbon | valentine]'
'💞: revolving hearts [revolving | revolving hearts]'
'💟: heart decoration [heart | heart decoration]'
'❣: heavy heart exclamation [exclamation | heavy heart exclamation | mark | punctuation]'
'💌: love letter [heart | letter | love | mail]'
'💤: zzz [comic | sleep | zzz]'
'💢: anger symbol [anger symbol | angry | comic | mad]'
'💣: bomb [bomb | comic]'
'💥: collision [boom | collision | comic]'
'💦: sweat droplets [comic | splashing | sweat | sweat droplets]'
'💨: dashing away [comic | dash | dashing away | running]'
'💫: dizzy [comic | dizzy | star]'
'💬: speech balloon [balloon | bubble | comic | dialog | speech]'
'🗨: left speech bubble [dialog | left speech bubble | speech]'
'🗯: right anger bubble [angry | balloon | bubble | mad | right anger bubble]'
'💭: thought balloon [balloon | bubble | comic | thought]'
'🕳: hole [hole]'
'👓: glasses [clothing | eye | eyeglasses | eyewear | glasses]'
'🕶: sunglasses [dark | eye | eyewear | glasses | sunglasses]'
'🥽: ⊛ goggles [eye protection | swimming | welding]'
'🥼: ⊛ lab coat [doctor | experiment | scientist]'
'👔: necktie [clothing | necktie | tie]'
'👕: t-shirt [clothing | shirt | t-shirt | tshirt]'
'👖: jeans [clothing | jeans | pants | trousers]'
'🧣: scarf [neck | scarf]'
'🧤: gloves [gloves | hand]'
'🧥: coat [coat | jacket]'
'🧦: socks [socks | stocking]'
'👗: dress [clothing | dress]'
'👘: kimono [clothing | kimono]'
'👙: bikini [bikini | clothing | swim]'
'👚: woman’s clothes [clothing | woman | woman’s clothes]'
'👛: purse [clothing | coin | purse]'
'👜: handbag [bag | clothing | handbag | purse]'
'👝: clutch bag [bag | clothing | clutch bag | pouch]'
'🛍: shopping bags [bag | hotel | shopping | shopping bags]'
'🎒: backpack [backpack | bag | rucksack | satchel | school]'
'👞: man’s shoe [clothing | man | man’s shoe | shoe]'
'👟: running shoe [athletic | clothing | running shoe | shoe | sneaker]'
'🥾: ⊛ hiking boot [backpacking | boot | camping | hiking]'
'🥿: ⊛ flat shoe [ballet flat | slip-on | slipper]'
'👠: high-heeled shoe [clothing | heel | high-heeled shoe | shoe | woman]'
'👡: woman’s sandal [clothing | sandal | shoe | woman | woman’s sandal]'
'👢: woman’s boot [boot | clothing | shoe | woman | woman’s boot]'
'👑: crown [clothing | crown | king | queen]'
'👒: woman’s hat [clothing | hat | woman | woman’s hat]'
'🎩: top hat [clothing | hat | top | tophat]'
'🎓: graduation cap [cap | celebration | clothing | graduation | hat]'
'🧢: billed cap [baseball cap | billed cap]'
'⛑: rescue worker’s helmet [aid | cross | face | hat | helmet | rescue worker’s helmet]'
'📿: prayer beads [beads | clothing | necklace | prayer | religion]'
'💄: lipstick [cosmetics | lipstick | makeup]'
'💍: ring [diamond | ring]'
'💎: gem stone [diamond | gem | gem stone | jewel]'
'🐵: monkey face [face | monkey]'
'🐒: monkey [monkey]'
'🦍: gorilla [gorilla]'
'🐶: dog face [dog | face | pet]'
'🐕: dog [dog | pet]'
'🐩: poodle [dog | poodle]'
'🐺: wolf face [face | wolf]'
'🦊: fox face [face | fox]'
'🦝: ⊛ raccoon [curious | sly]'
'🐱: cat face [cat | face | pet]'
'🐈: cat [cat | pet]'
'🦁: lion face [face | Leo | lion | zodiac]'
'🐯: tiger face [face | tiger]'
'🐅: tiger [tiger]'
'🐆: leopard [leopard]'
'🐴: horse face [face | horse]'
'🐎: horse [equestrian | horse | racehorse | racing]'
'🦄: unicorn face [face | unicorn]'
'🦓: zebra [stripe | zebra]'
'🦌: deer [deer]'
'🐮: cow face [cow | face]'
'🐂: ox [bull | ox | Taurus | zodiac]'
'🐃: water buffalo [buffalo | water]'
'🐄: cow [cow]'
'🐷: pig face [face | pig]'
'🐖: pig [pig | sow]'
'🐗: boar [boar | pig]'
'🐽: pig nose [face | nose | pig]'
'🐏: ram [Aries | male | ram | sheep | zodiac]'
'🐑: ewe [ewe | female | sheep]'
'🐐: goat [Capricorn | goat | zodiac]'
'🐪: camel [camel | dromedary | hump]'
'🐫: two-hump camel [bactrian | camel | hump | two-hump camel]'
'🦙: ⊛ llama [alpaca | guanaco | vicuña | wool]'
'🦒: giraffe [giraffe | spots]'
'🐘: elephant [elephant]'
'🦏: rhinoceros [rhinoceros]'
'🦛: ⊛ hippopotamus [hippo]'
'🐭: mouse face [face | mouse]'
'🐁: mouse [mouse]'
'🐀: rat [rat]'
'🐹: hamster face [face | hamster | pet]'
'🐰: rabbit face [bunny | face | pet | rabbit]'
'🐇: rabbit [bunny | pet | rabbit]'
'🐿: chipmunk [chipmunk | squirrel]'
'🦔: hedgehog [hedgehog | spiny]'
'🦇: bat [bat | vampire]'
'🐻: bear face [bear | face]'
'🐨: koala [bear | koala]'
'🐼: panda face [face | panda]'
'🦘: ⊛ kangaroo [Australia | joey | jump | marsupial]'
'🦡: ⊛ badger [honey badger | pester]'
'🐾: paw prints [feet | paw | paw prints | print]'
'🦃: turkey [bird | turkey]'
'🐔: chicken [bird | chicken]'
'🐓: rooster [bird | rooster]'
'🐣: hatching chick [baby | bird | chick | hatching]'
'🐤: baby chick [baby | bird | chick]'
'🐥: front-facing baby chick [baby | bird | chick | front-facing baby chick]'
'🐦: bird [bird]'
'🐧: penguin [bird | penguin]'
'🕊: dove [bird | dove | fly | peace]'
'🦅: eagle [bird | eagle]'
'🦆: duck [bird | duck]'
'🦢: ⊛ swan [bird | cygnet | ugly duckling]'
'🦉: owl [bird | owl | wise]'
'🦚: ⊛ peacock [bird | ostentatious | peahen | proud]'
'🦜: ⊛ parrot [bird | pirate | talk]'
'🐸: frog face [face | frog]'
'🐊: crocodile [crocodile]'
'🐢: turtle [terrapin | tortoise | turtle]'
'🦎: lizard [lizard | reptile]'
'🐍: snake [bearer | Ophiuchus | serpent | snake | zodiac]'
'🐲: dragon face [dragon | face | fairy tale]'
'🐉: dragon [dragon | fairy tale]'
'🦕: sauropod [brachiosaurus | brontosaurus | diplodocus | sauropod]'
'🦖: T-Rex [T-Rex | Tyrannosaurus Rex]'
'🐳: spouting whale [face | spouting | whale]'
'🐋: whale [whale]'
'🐬: dolphin [dolphin | flipper]'
'🐟: fish [fish | Pisces | zodiac]'
'🐠: tropical fish [fish | tropical]'
'🐡: blowfish [blowfish | fish]'
'🦈: shark [fish | shark]'
'🐙: octopus [octopus]'
'🐚: spiral shell [shell | spiral]'
'🦀: crab [Cancer | crab | zodiac]'
'🦞: ⊛ lobster [bisque | claws | seafood]'
'🦐: shrimp [food | shellfish | shrimp | small]'
'🦑: squid [food | molusc | squid]'
'🐌: snail [snail]'
'🦋: butterfly [butterfly | insect | pretty]'
'🐛: bug [bug | insect]'
'🐜: ant [ant | insect]'
'🐝: honeybee [bee | honeybee | insect]'
'🐞: lady beetle [beetle | insect | lady beetle | ladybird | ladybug]'
'🦗: cricket [cricket | grasshopper | Orthoptera]'
'🕷: spider [insect | spider]'
'🕸: spider web [spider | web]'
'🦂: scorpion [scorpio | Scorpio | scorpion | zodiac]'
'🦟: ⊛ mosquito [disease | fever | insect | malaria | virus]'
'🦠: ⊛ microbe [amoeba | bacteria | virus]'
'💐: bouquet [bouquet | flower]'
'🌸: cherry blossom [blossom | cherry | flower]'
'💮: white flower [flower | white flower]'
'🏵: rosette [plant | rosette]'
'🌹: rose [flower | rose]'
'🥀: wilted flower [flower | wilted]'
'🌺: hibiscus [flower | hibiscus]'
'🌻: sunflower [flower | sun | sunflower]'
'🌼: blossom [blossom | flower]'
'🌷: tulip [flower | tulip]'
'🌱: seedling [seedling | young]'
'🌲: evergreen tree [evergreen tree | tree]'
'🌳: deciduous tree [deciduous | shedding | tree]'
'🌴: palm tree [palm | tree]'
'🌵: cactus [cactus | plant]'
'🌾: sheaf of rice [ear | grain | rice | sheaf of rice]'
'🌿: herb [herb | leaf]'
'☘: shamrock [plant | shamrock]'
'🍀: four leaf clover [4 | clover | four | four-leaf clover | leaf]'
'🍁: maple leaf [falling | leaf | maple]'
'🍂: fallen leaf [fallen leaf | falling | leaf]'
'🍃: leaf fluttering in wind [blow | flutter | leaf | leaf fluttering in wind | wind]'
'🍇: grapes [fruit | grape | grapes]'
'🍈: melon [fruit | melon]'
'🍉: watermelon [fruit | watermelon]'
'🍊: tangerine [fruit | orange | tangerine]'
'🍋: lemon [citrus | fruit | lemon]'
'🍌: banana [banana | fruit]'
'🍍: pineapple [fruit | pineapple]'
'🥭: ⊛ mango [shaker | tropical]'
'🍎: red apple [apple | fruit | red]'
'🍏: green apple [apple | fruit | green]'
'🍐: pear [fruit | pear]'
'🍑: peach [fruit | peach]'
'🍒: cherries [berries | cherries | cherry | fruit | red]'
'🍓: strawberry [berry | fruit | strawberry]'
'🥝: kiwi fruit [food | fruit | kiwi]'
'🍅: tomato [fruit | tomato | vegetable]'
'🥥: coconut [coconut | palm | piña colada]'
'🥑: avocado [avocado | food | fruit]'
'🍆: eggplant [aubergine | eggplant | vegetable]'
'🥔: potato [food | potato | vegetable]'
'🥕: carrot [carrot | food | vegetable]'
'🌽: ear of corn [corn | ear | ear of corn | maize | maze]'
'🌶: hot pepper [hot | pepper]'
'🥒: cucumber [cucumber | food | pickle | vegetable]'
'🥬: ⊛ leafy green [bok choy | cabbage | kale | lettuce]'
'🥦: broccoli [broccoli | wild cabbage]'
'🍄: mushroom [mushroom | toadstool]'
'🥜: peanuts [food | nut | peanut | peanuts | vegetable]'
'🌰: chestnut [chestnut | plant]'
'🍞: bread [bread | loaf]'
'🥐: croissant [bread | crescent roll | croissant | food | french]'
'🥖: baguette bread [baguette | bread | food | french]'
'🥨: pretzel [pretzel | twisted | convoluted]'
'🥯: ⊛ bagel [bakery | schmear]'
'🥞: pancakes [crêpe | food | hotcake | pancake | pancakes]'
'🧀: cheese wedge [cheese | cheese wedge]'
'🍖: meat on bone [bone | meat | meat on bone]'
'🍗: poultry leg [bone | chicken | drumstick | leg | poultry]'
'🥩: cut of meat [chop | cut of meat | lambchop | porkchop | steak]'
'🥓: bacon [bacon | food | meat]'
'🍔: hamburger [burger | hamburger]'
'🍟: french fries [french | fries]'
'🍕: pizza [cheese | pizza | slice]'
'🌭: hot dog [frankfurter | hot dog | hotdog | sausage]'
'🥪: sandwich [bread | sandwich]'
'🌮: taco [mexican | taco]'
'🌯: burrito [burrito | mexican | wrap]'
'🥙: stuffed flatbread [falafel | flatbread | food | gyro | kebab | stuffed]'
'🥚: egg [egg | food]'
'🍳: cooking [cooking | egg | frying | pan]'
'🥘: shallow pan of food [casserole | food | paella | pan | shallow | shallow pan of food]'
'🍲: pot of food [pot | pot of food | stew]'
'🥣: bowl with spoon [bowl with spoon | breakfast | cereal | congee | oatmeal | porridge]'
'🥗: green salad [food | green | salad]'
'🍿: popcorn [popcorn]'
'🧂: ⊛ salt [condiment | shaker]'
'🥫: canned food [can | canned food]'
'🍱: bento box [bento | box]'
'🍘: rice cracker [cracker | rice]'
'🍙: rice ball [ball | Japanese | rice]'
'🍚: cooked rice [cooked | rice]'
'🍛: curry rice [curry | rice]'
'🍜: steaming bowl [bowl | noodle | ramen | steaming]'
'🍝: spaghetti [pasta | spaghetti]'
'🍠: roasted sweet potato [potato | roasted | sweet]'
'🍢: oden [kebab | oden | seafood | skewer | stick]'
'🍣: sushi [sushi]'
'🍤: fried shrimp [fried | prawn | shrimp | tempura]'
'🍥: fish cake with swirl [cake | fish | fish cake with swirl | pastry | swirl]'
'🥮: ⊛ moon cake [autumn | festival | yuèbǐng]'
'🍡: dango [dango | dessert | Japanese | skewer | stick | sweet]'
'🥟: dumpling [dumpling | empanada | gyōza | jiaozi | pierogi | potsticker]'
'🥠: fortune cookie [fortune cookie | prophecy]'
'🥡: takeout box [oyster pail | takeout box]'
'🍦: soft ice cream [cream | dessert | ice | icecream | soft | sweet]'
'🍧: shaved ice [dessert | ice | shaved | sweet]'
'🍨: ice cream [cream | dessert | ice | sweet]'
'🍩: doughnut [dessert | donut | doughnut | sweet]'
'🍪: cookie [cookie | dessert | sweet]'
'🎂: birthday cake [birthday | cake | celebration | dessert | pastry | sweet]'
'🍰: shortcake [cake | dessert | pastry | shortcake | slice | sweet]'
'🧁: ⊛ cupcake [bakery | sweet]'
'🥧: pie [filling | pastry | pie | fruit | meat]'
'🍫: chocolate bar [bar | chocolate | dessert | sweet]'
'🍬: candy [candy | dessert | sweet]'
'🍭: lollipop [candy | dessert | lollipop | sweet]'
'🍮: custard [custard | dessert | pudding | sweet]'
'🍯: honey pot [honey | honeypot | pot | sweet]'
'🍼: baby bottle [baby | bottle | drink | milk]'
'🥛: glass of milk [drink | glass | glass of milk | milk]'
'☕: hot beverage [beverage | coffee | drink | hot | steaming | tea]'
'🍵: teacup without handle [beverage | cup | drink | tea | teacup | teacup without handle]'
'🍶: sake [bar | beverage | bottle | cup | drink | sake]'
'🍾: bottle with popping cork [bar | bottle | bottle with popping cork | cork | drink | popping]'
'🍷: wine glass [bar | beverage | drink | glass | wine]'
'🍸: cocktail glass [bar | cocktail | drink | glass]'
'🍹: tropical drink [bar | drink | tropical]'
'🍺: beer mug [bar | beer | drink | mug]'
'🍻: clinking beer mugs [bar | beer | clink | clinking beer mugs | drink | mug]'
'🥂: clinking glasses [celebrate | clink | clinking glasses | drink | glass]'
'🥃: tumbler glass [glass | liquor | shot | tumbler | whisky]'
'🥤: cup with straw [cup with straw | juice | soda | malt | soft drink | water]'
'🥢: chopsticks [chopsticks | hashi | jeotgarak | kuaizi]'
'🍽: fork and knife with plate [cooking | fork | fork and knife with plate | knife | plate]'
'🍴: fork and knife [cooking | cutlery | fork | fork and knife | knife]'
'🥄: spoon [spoon | tableware]'
'🔪: kitchen knife [cooking | hocho | kitchen knife | knife | tool | weapon]'
'🏺: amphora [amphora | Aquarius | cooking | drink | jug | tool | weapon | zodiac]'
'🌍: globe showing Europe-Africa [Africa | earth | Europe | globe | globe showing Europe-Africa | world]'
'🌎: globe showing Americas [Americas | earth | globe | globe showing Americas | world]'
'🌏: globe showing Asia-Australia [Asia | Australia | earth | globe | globe showing Asia-Australia | world]'
'🌐: globe with meridians [earth | globe | globe with meridians | meridians | world]'
'🗺: world map [map | world]'
'🗾: map of Japan [Japan | map | map of Japan]'
'🧭: ⊛ compass [magnetic | navigation | orienteering]'
'🏔: snow-capped mountain [cold | mountain | snow | snow-capped mountain]'
'⛰: mountain [mountain]'
'🌋: volcano [eruption | mountain | volcano]'
'🗻: mount fuji [fuji | mount fuji | mountain]'
'🏕: camping [camping]'
'🏖: beach with umbrella [beach | beach with umbrella | umbrella]'
'🏜: desert [desert]'
'🏝: desert island [desert | island]'
'🏞: national park [national park | park]'
'🏟: stadium [stadium]'
'🏛: classical building [classical | classical building]'
'🏗: building construction [building construction | construction]'
'🧱: ⊛ brick [bricks | clay | mortar | wall]'
'🏘: houses [houses]'
'🏚: derelict house [derelict | house]'
'🏠: house [home | house]'
'🏡: house with garden [garden | home | house | house with garden]'
'🏢: office building [building | office building]'
'🏣: Japanese post office [Japanese | Japanese post office | post]'
'🏤: post office [European | post | post office]'
'🏥: hospital [doctor | hospital | medicine]'
'🏦: bank [bank | building]'
'🏨: hotel [building | hotel]'
'🏩: love hotel [hotel | love]'
'🏪: convenience store [convenience | store]'
'🏫: school [building | school]'
'🏬: department store [department | store]'
'🏭: factory [building | factory]'
'🏯: Japanese castle [castle | Japanese]'
'🏰: castle [castle | European]'
'💒: wedding [chapel | romance | wedding]'
'🗼: Tokyo tower [Tokyo | tower]'
'🗽: Statue of Liberty [liberty | statue | Statue of Liberty]'
'⛪: church [Christian | church | cross | religion]'
'🕌: mosque [islam | mosque | Muslim | religion]'
'🕍: synagogue [Jew | Jewish | religion | synagogue | temple]'
'⛩: shinto shrine [religion | shinto | shrine]'
'🕋: kaaba [islam | kaaba | Muslim | religion]'
'⛲: fountain [fountain]'
'⛺: tent [camping | tent]'
'🌁: foggy [fog | foggy]'
'🌃: night with stars [night | night with stars | star]'
'🏙: cityscape [city | cityscape]'
'🌄: sunrise over mountains [morning | mountain | sun | sunrise | sunrise over mountains]'
'🌅: sunrise [morning | sun | sunrise]'
'🌆: cityscape at dusk [city | cityscape at dusk | dusk | evening | landscape | sun | sunset]'
'🌇: sunset [dusk | sun | sunset]'
'🌉: bridge at night [bridge | bridge at night | night]'
'♨: hot springs [hot | hotsprings | springs | steaming]'
'🌌: milky way [milky way | space]'
'🎠: carousel horse [carousel | horse]'
'🎡: ferris wheel [amusement park | ferris | wheel]'
'🎢: roller coaster [amusement park | coaster | roller]'
'💈: barber pole [barber | haircut | pole]'
'🎪: circus tent [circus | tent]'
'🚂: locomotive [engine | locomotive | railway | steam | train]'
'🚃: railway car [car | electric | railway | train | tram | trolleybus]'
'🚄: high-speed train [high-speed train | railway | shinkansen | speed | train]'
'🚅: bullet train [bullet | railway | shinkansen | speed | train]'
'🚆: train [railway | train]'
'🚇: metro [metro | subway]'
'🚈: light rail [light rail | railway]'
'🚉: station [railway | station | train]'
'🚊: tram [tram | trolleybus]'
'🚝: monorail [monorail | vehicle]'
'🚞: mountain railway [car | mountain | railway]'
'🚋: tram car [car | tram | trolleybus]'
'🚌: bus [bus | vehicle]'
'🚍: oncoming bus [bus | oncoming]'
'🚎: trolleybus [bus | tram | trolley | trolleybus]'
'🚐: minibus [bus | minibus]'
'🚑: ambulance [ambulance | vehicle]'
'🚒: fire engine [engine | fire | truck]'
'🚓: police car [car | patrol | police]'
'🚔: oncoming police car [car | oncoming | police]'
'🚕: taxi [taxi | vehicle]'
'🚖: oncoming taxi [oncoming | taxi]'
'🚗: automobile [automobile | car]'
'🚘: oncoming automobile [automobile | car | oncoming]'
'🚙: sport utility vehicle [recreational | sport utility | sport utility vehicle]'
'🚚: delivery truck [delivery | truck]'
'🚛: articulated lorry [articulated lorry | lorry | semi | truck]'
'🚜: tractor [tractor | vehicle]'
'🚲: bicycle [bicycle | bike]'
'🛴: kick scooter [kick | scooter]'
'🛹: ⊛ skateboard [board]'
'🛵: motor scooter [motor | scooter]'
'🚏: bus stop [bus | busstop | stop]'
'🛣: motorway [highway | motorway | road]'
'🛤: railway track [railway | railway track | train]'
'🛢: oil drum [drum | oil]'
'⛽: fuel pump [diesel | fuel | fuelpump | gas | pump | station]'
'🚨: police car light [beacon | car | light | police | revolving]'
'🚥: horizontal traffic light [horizontal traffic light | light | signal | traffic]'
'🚦: vertical traffic light [light | signal | traffic | vertical traffic light]'
'🛑: stop sign [octagonal | sign | stop]'
'🚧: construction [barrier | construction]'
'⚓: anchor [anchor | ship | tool]'
'⛵: sailboat [boat | resort | sailboat | sea | yacht]'
'🛶: canoe [boat | canoe]'
'🚤: speedboat [boat | speedboat]'
'🛳: passenger ship [passenger | ship]'
'⛴: ferry [boat | ferry | passenger]'
'🛥: motor boat [boat | motor boat | motorboat]'
'🚢: ship [boat | passenger | ship]'
'✈: airplane [aeroplane | airplane]'
'🛩: small airplane [aeroplane | airplane | small airplane]'
'🛫: airplane departure [aeroplane | airplane | check-in | departure | departures]'
'🛬: airplane arrival [aeroplane | airplane | airplane arrival | arrivals | arriving | landing]'
'💺: seat [chair | seat]'
'🚁: helicopter [helicopter | vehicle]'
'🚟: suspension railway [railway | suspension]'
'🚠: mountain cableway [cable | gondola | mountain | mountain cableway]'
'🚡: aerial tramway [aerial | cable | car | gondola | tramway]'
'🛰: satellite [satellite | space]'
'🚀: rocket [rocket | space]'
'🛸: flying saucer [flying saucer | UFO]'
'🛎: bellhop bell [bell | bellhop | hotel]'
'🧳: ⊛ luggage [packing | travel]'
'⌛: hourglass done [hourglass done | sand | timer]'
'⏳: hourglass not done [hourglass | hourglass not done | sand | timer]'
'⌚: watch [clock | watch]'
'⏰: alarm clock [alarm | clock]'
'⏱: stopwatch [clock | stopwatch]'
'⏲: timer clock [clock | timer]'
'🕰: mantelpiece clock [clock | mantelpiece clock]'
'🕛: twelve o’clock [00 | 12 | 12:00 | clock | o’clock | twelve]'
'🕧: twelve-thirty [12 | 12:30 | 30 | clock | thirty | twelve | twelve-thirty]'
'🕐: one o’clock [00 | 1 | 1:00 | clock | o’clock | one]'
'🕜: one-thirty [1 | 1:30 | 30 | clock | one | one-thirty | thirty]'
'🕑: two o’clock [00 | 2 | 2:00 | clock | o’clock | two]'
'🕝: two-thirty [2 | 2:30 | 30 | clock | thirty | two | two-thirty]'
'🕒: three o’clock [00 | 3 | 3:00 | clock | o’clock | three]'
'🕞: three-thirty [3 | 3:30 | 30 | clock | thirty | three | three-thirty]'
'🕓: four o’clock [00 | 4 | 4:00 | clock | four | o’clock]'
'🕟: four-thirty [30 | 4 | 4:30 | clock | four | four-thirty | thirty]'
'🕔: five o’clock [00 | 5 | 5:00 | clock | five | o’clock]'
'🕠: five-thirty [30 | 5 | 5:30 | clock | five | five-thirty | thirty]'
'🕕: six o’clock [00 | 6 | 6:00 | clock | o’clock | six]'
'🕡: six-thirty [30 | 6 | 6:30 | clock | six | six-thirty | thirty]'
'🕖: seven o’clock [00 | 7 | 7:00 | clock | o’clock | seven]'
'🕢: seven-thirty [30 | 7 | 7:30 | clock | seven | seven-thirty | thirty]'
'🕗: eight o’clock [00 | 8 | 8:00 | clock | eight | o’clock]'
'🕣: eight-thirty [30 | 8 | 8:30 | clock | eight | eight-thirty | thirty]'
'🕘: nine o’clock [00 | 9 | 9:00 | clock | nine | o’clock]'
'🕤: nine-thirty [30 | 9 | 9:30 | clock | nine | nine-thirty | thirty]'
'🕙: ten o’clock [00 | 10 | 10:00 | clock | o’clock | ten]'
'🕥: ten-thirty [10 | 10:30 | 30 | clock | ten | ten-thirty | thirty]'
'🕚: eleven o’clock [00 | 11 | 11:00 | clock | eleven | o’clock]'
'🕦: eleven-thirty [11 | 11:30 | 30 | clock | eleven | eleven-thirty | thirty]'
'🌑: new moon [dark | moon | new moon]'
'🌒: waxing crescent moon [crescent | moon | waxing]'
'🌓: first quarter moon [first quarter moon | moon | quarter]'
'🌔: waxing gibbous moon [gibbous | moon | waxing]'
'🌕: full moon [full | moon]'
'🌖: waning gibbous moon [gibbous | moon | waning]'
'🌗: last quarter moon [last quarter moon | moon | quarter]'
'🌘: waning crescent moon [crescent | moon | waning]'
'🌙: crescent moon [crescent | moon]'
'🌚: new moon face [face | moon | new moon face]'
'🌛: first quarter moon face [face | first quarter moon face | moon | quarter]'
'🌜: last quarter moon face [face | last quarter moon face | moon | quarter]'
'🌡: thermometer [thermometer | weather]'
'☀: sun [bright | rays | sun | sunny]'
'🌝: full moon face [bright | face | full | moon]'
'🌞: sun with face [bright | face | sun | sun with face]'
'⭐: star [star]'
'🌟: glowing star [glittery | glow | glowing star | shining | sparkle | star]'
'🌠: shooting star [falling | shooting | star]'
'☁: cloud [cloud | weather]'
'⛅: sun behind cloud [cloud | sun | sun behind cloud]'
'⛈: cloud with lightning and rain [cloud | cloud with lightning and rain | rain | thunder]'
'🌤: sun behind small cloud [cloud | sun | sun behind small cloud]'
'🌥: sun behind large cloud [cloud | sun | sun behind large cloud]'
'🌦: sun behind rain cloud [cloud | rain | sun | sun behind rain cloud]'
'🌧: cloud with rain [cloud | cloud with rain | rain]'
'🌨: cloud with snow [cloud | cloud with snow | cold | snow]'
'🌩: cloud with lightning [cloud | cloud with lightning | lightning]'
'🌪: tornado [cloud | tornado | whirlwind]'
'🌫: fog [cloud | fog]'
'🌬: wind face [blow | cloud | face | wind]'
'🌀: cyclone [cyclone | dizzy | hurricane | twister | typhoon]'
'🌈: rainbow [rain | rainbow]'
'🌂: closed umbrella [closed umbrella | clothing | rain | umbrella]'
'☂: umbrella [clothing | rain | umbrella]'
'☔: umbrella with rain drops [clothing | drop | rain | umbrella | umbrella with rain drops]'
'⛱: umbrella on ground [rain | sun | umbrella | umbrella on ground]'
'⚡: high voltage [danger | electric | electricity | high voltage | lightning | voltage | zap]'
'❄: snowflake [cold | snow | snowflake]'
'☃: snowman [cold | snow | snowman]'
'⛄: snowman without snow [cold | snow | snowman | snowman without snow]'
'☄: comet [comet | space]'
'🔥: fire [fire | flame | tool]'
'💧: droplet [cold | comic | drop | droplet | sweat]'
'🌊: water wave [ocean | water | wave]'
'🎃: jack-o-lantern [celebration | halloween | jack | jack-o-lantern | lantern]'
'🎄: Christmas tree [celebration | Christmas | tree]'
'🎆: fireworks [celebration | fireworks]'
'🎇: sparkler [celebration | fireworks | sparkle | sparkler]'
'🧨: ⊛ firecracker [dynamite | explosive | fireworks]'
'✨: sparkles [sparkle | sparkles | star]'
'🎈: balloon [balloon | celebration]'
'🎉: party popper [celebration | party | popper | tada]'
'🎊: confetti ball [ball | celebration | confetti]'
'🎋: tanabata tree [banner | celebration | Japanese | tanabata tree | tree]'
'🎍: pine decoration [bamboo | celebration | Japanese | pine | pine decoration]'
'🎎: Japanese dolls [celebration | doll | festival | Japanese | Japanese dolls]'
'🎏: carp streamer [carp | celebration | streamer]'
'🎐: wind chime [bell | celebration | chime | wind]'
'🎑: moon viewing ceremony [celebration | ceremony | moon | moon viewing ceremony]'
'🧧: ⊛ red envelope [gift | good luck | hóngbāo | lai see | money]'
'🎀: ribbon [celebration | ribbon]'
'🎁: wrapped gift [box | celebration | gift | present | wrapped]'
'🎗: reminder ribbon [celebration | reminder | ribbon]'
'🎟: admission tickets [admission | admission tickets | ticket]'
'🎫: ticket [admission | ticket]'
'🎖: military medal [celebration | medal | military]'
'🏆: trophy [prize | trophy]'
'🏅: sports medal [medal | sports medal]'
'🥇: 1st place medal [1st place medal | first | gold | medal]'
'🥈: 2nd place medal [2nd place medal | medal | second | silver]'
'🥉: 3rd place medal [3rd place medal | bronze | medal | third]'
'⚽: soccer ball [ball | football | soccer]'
'⚾: baseball [ball | baseball]'
'🥎: ⊛ softball [ball | glove | underarm]'
'🏀: basketball [ball | basketball | hoop]'
'🏐: volleyball [ball | game | volleyball]'
'🏈: american football [american | ball | football]'
'🏉: rugby football [ball | football | rugby]'
'🎾: tennis [ball | racquet | tennis]'
'🥏: ⊛ flying disc [ultimate]'
'🎳: bowling [ball | bowling | game]'
'🏏: cricket game [ball | bat | cricket game | game]'
'🏑: field hockey [ball | field | game | hockey | stick]'
'🏒: ice hockey [game | hockey | ice | puck | stick]'
'🥍: ⊛ lacrosse [ball | goal | stick]'
'🏓: ping pong [ball | bat | game | paddle | ping pong | table tennis]'
'🏸: badminton [badminton | birdie | game | racquet | shuttlecock]'
'🥊: boxing glove [boxing | glove]'
'🥋: martial arts uniform [judo | karate | martial arts | martial arts uniform | taekwondo | uniform]'
'🥅: goal net [goal | net]'
'⛳: flag in hole [flag in hole | golf | hole]'
'⛸: ice skate [ice | skate]'
'🎣: fishing pole [fish | fishing pole | pole]'
'🎽: running shirt [athletics | running | sash | shirt]'
'🎿: skis [ski | skis | snow]'
'🛷: sled [sled | sledge | sleigh | luge | toboggan]'
'🥌: curling stone [curling stone | game | rock]'
'🎯: direct hit [bull | bullseye | dart | direct hit | eye | game | hit | target]'
'🎱: pool 8 ball [8 | ball | billiard | eight | game | pool 8 ball]'
'🔮: crystal ball [ball | crystal | fairy tale | fantasy | fortune | tool]'
'🧿: ⊛ nazar amulet [bead | charm | evil-eye | nazar | talisman]'
'🎮: video game [controller | game | video game]'
'🕹: joystick [game | joystick | video game]'
'🎰: slot machine [game | slot | slot machine]'
'🎲: game die [dice | die | game]'
'🧩: ⊛ jigsaw [clue | interlocking | piece | puzzle]'
'🧸: ⊛ teddy bear [plaything | plush | stuffed | toy]'
'♠: spade suit [card | game | spade suit]'
'♥: heart suit [card | game | heart suit]'
'♦: diamond suit [card | diamond suit | game]'
'♣: club suit [card | club suit | game]'
'♟: ⊛ chess pawn [chess | dupe | expendable | red shirt]'
'🃏: joker [card | game | joker | wildcard]'
'🀄: mahjong red dragon [game | mahjong | mahjong red dragon | red]'
'🎴: flower playing cards [card | flower | flower playing cards | game | Japanese | playing]'
'🎭: performing arts [art | mask | performing | performing arts | theater | theatre]'
'🖼: framed picture [art | frame | framed picture | museum | painting | picture]'
'🎨: artist palette [art | artist palette | museum | painting | palette]'
'🧵: ⊛ thread [needle | sewing | spool | string]'
'🧶: ⊛ yarn [ball | crochet | knit]'
'🔇: muted speaker [mute | muted speaker | quiet | silent | speaker]'
'🔈: speaker low volume [soft | speaker low volume]'
'🔉: speaker medium volume [medium | speaker medium volume]'
'🔊: speaker high volume [loud | speaker high volume]'
'📢: loudspeaker [loud | loudspeaker | public address]'
'📣: megaphone [cheering | megaphone]'
'📯: postal horn [horn | post | postal]'
'🔔: bell [bell]'
'🔕: bell with slash [bell | bell with slash | forbidden | mute | no | not | prohibited | quiet | silent]'
'🎼: musical score [music | musical score | score]'
'🎵: musical note [music | musical note | note]'
'🎶: musical notes [music | musical notes | note | notes]'
'🎙: studio microphone [mic | microphone | music | studio]'
'🎚: level slider [level | music | slider]'
'🎛: control knobs [control | knobs | music]'
'🎤: microphone [karaoke | mic | microphone]'
'🎧: headphone [earbud | headphone]'
'📻: radio [radio | video]'
'🎷: saxophone [instrument | music | sax | saxophone]'
'🎸: guitar [guitar | instrument | music]'
'🎹: musical keyboard [instrument | keyboard | music | musical keyboard | piano]'
'🎺: trumpet [instrument | music | trumpet]'
'🎻: violin [instrument | music | violin]'
'🥁: drum [drum | drumsticks | music]'
'📱: mobile phone [cell | mobile | phone | telephone]'
'📲: mobile phone with arrow [arrow | call | cell | mobile | mobile phone with arrow | phone | receive | telephone]'
'☎: telephone [phone | telephone]'
'📞: telephone receiver [phone | receiver | telephone]'
'📟: pager [pager]'
'📠: fax machine [fax | fax machine]'
'🔋: battery [battery]'
'🔌: electric plug [electric | electricity | plug]'
'💻: laptop computer [computer | laptop computer | pc | personal]'
'🖥: desktop computer [computer | desktop]'
'🖨: printer [computer | printer]'
'⌨: keyboard [computer | keyboard]'
'🖱: computer mouse [computer | computer mouse]'
'🖲: trackball [computer | trackball]'
'💽: computer disk [computer | disk | minidisk | optical]'
'💾: floppy disk [computer | disk | floppy]'
'💿: optical disk [cd | computer | disk | optical]'
'📀: dvd [blu-ray | computer | disk | dvd | optical]'
'🧮: ⊛ abacus [calculation]'
'🎥: movie camera [camera | cinema | movie]'
'🎞: film frames [cinema | film | frames | movie]'
'📽: film projector [cinema | film | movie | projector | video]'
'🎬: clapper board [clapper | clapper board | movie]'
'📺: television [television | tv | video]'
'📷: camera [camera | video]'
'📸: camera with flash [camera | camera with flash | flash | video]'
'📹: video camera [camera | video]'
'📼: videocassette [tape | vhs | video | videocassette]'
'🔍: magnifying glass tilted left [glass | magnifying | magnifying glass tilted left | search | tool]'
'🔎: magnifying glass tilted right [glass | magnifying | magnifying glass tilted right | search | tool]'
'🕯: candle [candle | light]'
'💡: light bulb [bulb | comic | electric | idea | light]'
'🔦: flashlight [electric | flashlight | light | tool | torch]'
'🏮: red paper lantern [bar | lantern | light | red | red paper lantern]'
'📔: notebook with decorative cover [book | cover | decorated | notebook | notebook with decorative cover]'
'📕: closed book [book | closed]'
'📖: open book [book | open]'
'📗: green book [book | green]'
'📘: blue book [blue | book]'
'📙: orange book [book | orange]'
'📚: books [book | books]'
'📓: notebook [notebook]'
'📒: ledger [ledger | notebook]'
'📃: page with curl [curl | document | page | page with curl]'
'📜: scroll [paper | scroll]'
'📄: page facing up [document | page | page facing up]'
'📰: newspaper [news | newspaper | paper]'
'🗞: rolled-up newspaper [news | newspaper | paper | rolled | rolled-up newspaper]'
'📑: bookmark tabs [bookmark | mark | marker | tabs]'
'🔖: bookmark [bookmark | mark]'
'🏷: label [label]'
'💰: money bag [bag | dollar | money | moneybag]'
'💴: yen banknote [bank | banknote | bill | currency | money | note | yen]'
'💵: dollar banknote [bank | banknote | bill | currency | dollar | money | note]'
'💶: euro banknote [bank | banknote | bill | currency | euro | money | note]'
'💷: pound banknote [bank | banknote | bill | currency | money | note | pound]'
'💸: money with wings [bank | banknote | bill | dollar | fly | money | money with wings | note | wings]'
'💳: credit card [bank | card | credit | money]'
'🧾: ⊛ receipt [accounting | bookkeeping | evidence | proof]'
'💹: chart increasing with yen [bank | chart | chart increasing with yen | currency | graph | growth | market | money | rise | trend | upward | yen]'
'💱: currency exchange [bank | currency | exchange | money]'
'💲: heavy dollar sign [currency | dollar | heavy dollar sign | money]'
'✉: envelope [email | envelope | letter]'
'📧: e-mail [e-mail | email | letter | mail]'
'📨: incoming envelope [e-mail | email | envelope | incoming | letter | mail | receive]'
'📩: envelope with arrow [arrow | down | e-mail | email | envelope | envelope with arrow | letter | mail | outgoing | sent]'
'📤: outbox tray [box | letter | mail | outbox | sent | tray]'
'📥: inbox tray [box | inbox | letter | mail | receive | tray]'
'📦: package [box | package | parcel]'
'📫: closed mailbox with raised flag [closed | closed mailbox with raised flag | mail | mailbox | postbox]'
'📪: closed mailbox with lowered flag [closed | closed mailbox with lowered flag | lowered | mail | mailbox | postbox]'
'📬: open mailbox with raised flag [mail | mailbox | open | open mailbox with raised flag | postbox]'
'📭: open mailbox with lowered flag [lowered | mail | mailbox | open | open mailbox with lowered flag | postbox]'
'📮: postbox [mail | mailbox | postbox]'
'🗳: ballot box with ballot [ballot | ballot box with ballot | box]'
'✏: pencil [pencil]'
'✒: black nib [black nib | nib | pen]'
'🖋: fountain pen [fountain | pen]'
'🖊: pen [ballpoint | pen]'
'🖌: paintbrush [paintbrush | painting]'
'🖍: crayon [crayon]'
'📝: memo [memo | pencil]'
'💼: briefcase [briefcase]'
'📁: file folder [file | folder]'
'📂: open file folder [file | folder | open]'
'🗂: card index dividers [card | dividers | index]'
'📅: calendar [calendar | date]'
'📆: tear-off calendar [calendar | tear-off calendar]'
'🗒: spiral notepad [note | pad | spiral | spiral notepad]'
'🗓: spiral calendar [calendar | pad | spiral]'
'📇: card index [card | index | rolodex]'
'📈: chart increasing [chart | chart increasing | graph | growth | trend | upward]'
'📉: chart decreasing [chart | chart decreasing | down | graph | trend]'
'📊: bar chart [bar | chart | graph]'
'📋: clipboard [clipboard]'
'📌: pushpin [pin | pushpin]'
'📍: round pushpin [pin | pushpin | round pushpin]'
'📎: paperclip [paperclip]'
'🖇: linked paperclips [link | linked paperclips | paperclip]'
'📏: straight ruler [ruler | straight edge | straight ruler]'
'📐: triangular ruler [ruler | set | triangle | triangular ruler]'
'✂: scissors [cutting | scissors | tool]'
'🗃: card file box [box | card | file]'
'🗄: file cabinet [cabinet | file | filing]'
'🗑: wastebasket [wastebasket]'
'🔒: locked [closed | locked]'
'🔓: unlocked [lock | open | unlock | unlocked]'
'🔏: locked with pen [ink | lock | locked with pen | nib | pen | privacy]'
'🔐: locked with key [closed | key | lock | locked with key | secure]'
'🔑: key [key | lock | password]'
'🗝: old key [clue | key | lock | old]'
'🔨: hammer [hammer | tool]'
'⛏: pick [mining | pick | tool]'
'⚒: hammer and pick [hammer | hammer and pick | pick | tool]'
'🛠: hammer and wrench [hammer | hammer and wrench | spanner | tool | wrench]'
'🗡: dagger [dagger | knife | weapon]'
'⚔: crossed swords [crossed | swords | weapon]'
'🔫: pistol [gun | handgun | pistol | revolver | tool | weapon]'
'🏹: bow and arrow [archer | archery | arrow | bow | bow and arrow | Sagittarius | tool | weapon | zodiac]'
'🛡: shield [shield | weapon]'
'🔧: wrench [spanner | tool | wrench]'
'🔩: nut and bolt [bolt | nut | nut and bolt | tool]'
'⚙: gear [cog | cogwheel | gear | tool]'
'🗜: clamp [clamp | compress | tool | vice]'
'⚖: balance scale [balance | balance scale | justice | Libra | scales | tool | weight | zodiac]'
'🔗: link [link]'
'⛓: chains [chain | chains]'
'🧰: ⊛ toolbox [chest | mechanic | tool]'
'🧲: ⊛ magnet [attraction | horseshoe | magnetic]'
'⚗: alembic [alembic | chemistry | tool]'
'🧪: ⊛ test tube [chemist | chemistry | experiment | lab | science]'
'🧫: ⊛ petri dish [bacteria | biologist | biology | culture | lab]'
'🧬: ⊛ dna [biologist | evolution | gene | genetics | life]'
'🔬: microscope [microscope | science | tool]'
'🔭: telescope [science | telescope | tool]'
'📡: satellite antenna [antenna | dish | satellite]'
'💉: syringe [doctor | medicine | needle | shot | sick | syringe | tool]'
'💊: pill [doctor | medicine | pill | sick]'
'🚪: door [door]'
'🛏: bed [bed | hotel | sleep]'
'🛋: couch and lamp [couch | couch and lamp | hotel | lamp]'
'🚽: toilet [toilet]'
'🚿: shower [shower | water]'
'🛁: bathtub [bath | bathtub]'
'🧴: ⊛ lotion bottle [lotion | moisturizer | shampoo | sunscreen]'
'🧷: ⊛ safety pin [diaper | punk rock]'
'🧹: ⊛ broom [cleaning | sweeping | witch]'
'🧺: ⊛ basket [farming | laundry | picnic]'
'🧻: ⊛ roll of paper [paper towels | toilet paper]'
'🧼: ⊛ soap [bar | bathing | cleaning | lather | soapdish]'
'🧽: ⊛ sponge [absorbing | cleaning | porous]'
'🧯: ⊛ fire extinguisher [extinguish | fire | quench]'
'🛒: shopping cart [cart | shopping | trolley]'
'🚬: cigarette [cigarette | smoking]'
'⚰: coffin [coffin | death]'
'⚱: funeral urn [ashes | death | funeral | urn]'
'🗿: moai [face | moai | moyai | statue]'
'🏧: ATM sign [atm | ATM sign | automated | bank | teller]'
'🚮: litter in bin sign [litter | litter bin | litter in bin sign]'
'🚰: potable water [drinking | potable | water]'
'♿: wheelchair symbol [access | wheelchair symbol]'
'🚹: men’s room [lavatory | man | men’s room | restroom | wc]'
'🚺: women’s room [lavatory | restroom | wc | woman | women’s room]'
'🚻: restroom [lavatory | restroom | WC]'
'🚼: baby symbol [baby | baby symbol | changing]'
'🚾: water closet [closet | lavatory | restroom | water | wc]'
'🛂: passport control [control | passport]'
'🛃: customs [customs]'
'🛄: baggage claim [baggage | claim]'
'🛅: left luggage [baggage | left luggage | locker | luggage]'
'⚠: warning [warning]'
'🚸: children crossing [child | children crossing | crossing | pedestrian | traffic]'
'⛔: no entry [entry | forbidden | no | not | prohibited | traffic]'
'🚫: prohibited [entry | forbidden | no | not | prohibited]'
'🚳: no bicycles [bicycle | bike | forbidden | no | no bicycles | not | prohibited]'
'🚭: no smoking [forbidden | no | not | prohibited | smoking]'
'🚯: no littering [forbidden | litter | no | no littering | not | prohibited]'
'🚱: non-potable water [non-drinking | non-potable | water]'
'🚷: no pedestrians [forbidden | no | no pedestrians | not | pedestrian | prohibited]'
'📵: no mobile phones [cell | forbidden | mobile | no | no mobile phones | not | phone | prohibited | telephone]'
'🔞: no one under eighteen [18 | age restriction | eighteen | forbidden | no | no one under eighteen | not | prohibited | underage]'
'☢: radioactive [radioactive | sign]'
'☣: biohazard [biohazard | sign]'
'⬆: up arrow [arrow | cardinal | direction | north | up arrow]'
'↗: up-right arrow [arrow | direction | intercardinal | northeast | up-right arrow]'
'➡: right arrow [arrow | cardinal | direction | east | right arrow]'
'↘: down-right arrow [arrow | direction | down-right arrow | intercardinal | southeast]'
'⬇: down arrow [arrow | cardinal | direction | down | south]'
'↙: down-left arrow [arrow | direction | down-left arrow | intercardinal | southwest]'
'⬅: left arrow [arrow | cardinal | direction | left arrow | west]'
'↖: up-left arrow [arrow | direction | intercardinal | northwest | up-left arrow]'
'↕: up-down arrow [arrow | up-down arrow]'
'↔: left-right arrow [arrow | left-right arrow]'
'↩: right arrow curving left [arrow | right arrow curving left]'
'↪: left arrow curving right [arrow | left arrow curving right]'
'⤴: right arrow curving up [arrow | right arrow curving up]'
'⤵: right arrow curving down [arrow | down | right arrow curving down]'
'🔃: clockwise vertical arrows [arrow | clockwise | clockwise vertical arrows | reload]'
'🔄: counterclockwise arrows button [anticlockwise | arrow | counterclockwise | counterclockwise arrows button | withershins]'
'🔙: BACK arrow [arrow | back | BACK arrow]'
'🔚: END arrow [arrow | end | END arrow]'
'🔛: ON! arrow [arrow | mark | on | ON! arrow]'
'🔜: SOON arrow [arrow | soon | SOON arrow]'
'🔝: TOP arrow [arrow | top | TOP arrow | up]'
'🛐: place of worship [place of worship | religion | worship]'
'⚛: atom symbol [atheist | atom | atom symbol]'
'🕉: om [Hindu | om | religion]'
'✡: star of David [David | Jew | Jewish | religion | star | star of David]'
'☸: wheel of dharma [Buddhist | dharma | religion | wheel | wheel of dharma]'
'☯: yin yang [religion | tao | taoist | yang | yin]'
'✝: latin cross [Christian | cross | latin cross | religion]'
'☦: orthodox cross [Christian | cross | orthodox cross | religion]'
'☪: star and crescent [islam | Muslim | religion | star and crescent]'
'☮: peace symbol [peace | peace symbol]'
'🕎: menorah [candelabrum | candlestick | menorah | religion]'
'🔯: dotted six-pointed star [dotted six-pointed star | fortune | star]'
'♈: Aries [Aries | ram | zodiac]'
'♉: Taurus [bull | ox | Taurus | zodiac]'
'♊: Gemini [Gemini | twins | zodiac]'
'♋: Cancer [Cancer | crab | zodiac]'
'♌: Leo [Leo | lion | zodiac]'
'♍: Virgo [Virgo | zodiac]'
'♎: Libra [balance | justice | Libra | scales | zodiac]'
'♏: Scorpio [Scorpio | scorpion | scorpius | zodiac]'
'♐: Sagittarius [archer | Sagittarius | zodiac]'
'♑: Capricorn [Capricorn | goat | zodiac]'
'♒: Aquarius [Aquarius | bearer | water | zodiac]'
'♓: Pisces [fish | Pisces | zodiac]'
'⛎: Ophiuchus [bearer | Ophiuchus | serpent | snake | zodiac]'
'🔀: shuffle tracks button [arrow | crossed | shuffle tracks button]'
'🔁: repeat button [arrow | clockwise | repeat | repeat button]'
'🔂: repeat single button [arrow | clockwise | once | repeat single button]'
'▶: play button [arrow | play | play button | right | triangle]'
'⏩: fast-forward button [arrow | double | fast | fast-forward button | forward]'
'⏭: next track button [arrow | next scene | next track | next track button | triangle]'
'⏯: play or pause button [arrow | pause | play | play or pause button | right | triangle]'
'◀: reverse button [arrow | left | reverse | reverse button | triangle]'
'⏪: fast reverse button [arrow | double | fast reverse button | rewind]'
'⏮: last track button [arrow | last track button | previous scene | previous track | triangle]'
'🔼: upwards button [arrow | button | red | upwards button]'
'⏫: fast up button [arrow | double | fast up button]'
'🔽: downwards button [arrow | button | down | downwards button | red]'
'⏬: fast down button [arrow | double | down | fast down button]'
'⏸: pause button [bar | double | pause | pause button | vertical]'
'⏹: stop button [square | stop | stop button]'
'⏺: record button [circle | record | record button]'
'⏏: eject button [eject | eject button]'
'🎦: cinema [camera | cinema | film | movie]'
'🔅: dim button [brightness | dim | dim button | low]'
'🔆: bright button [bright | bright button | brightness]'
'📶: antenna bars [antenna | antenna bars | bar | cell | mobile | phone | signal | telephone]'
'📳: vibration mode [cell | mobile | mode | phone | telephone | vibration]'
'📴: mobile phone off [cell | mobile | off | phone | telephone]'
'♀: female sign [female sign | woman]'
'♂: male sign [male sign | man]'
'⚕: medical symbol [aesculapius | medical symbol | medicine | staff]'
'♾: ⊛ infinity [forever | unbounded | universal]'
'♻: recycling symbol [recycle | recycling symbol]'
'⚜: fleur-de-lis [fleur-de-lis]'
'🔱: trident emblem [anchor | emblem | ship | tool | trident]'
'📛: name badge [badge | name]'
'🔰: Japanese symbol for beginner [beginner | chevron | green | Japanese | Japanese symbol for beginner | leaf | tool | yellow]'
'⭕: heavy large circle [circle | heavy large circle | o]'
'✅: white heavy check mark [check | mark | white heavy check mark]'
'☑: ballot box with check [ballot | ballot box with check | box | check]'
'✔: heavy check mark [check | heavy check mark | mark]'
'✖: heavy multiplication x [cancel | heavy multiplication x | multiplication | multiply | x]'
'❌: cross mark [cancel | cross mark | mark | multiplication | multiply | x]'
'❎: cross mark button [cross mark button | mark | square]'
'➕: heavy plus sign [heavy plus sign | math | plus]'
'➖: heavy minus sign [heavy minus sign | math | minus]'
'➗: heavy division sign [division | heavy division sign | math]'
'➰: curly loop [curl | curly loop | loop]'
'➿: double curly loop [curl | double | double curly loop | loop]'
'〽: part alternation mark [mark | part | part alternation mark]'
'✳: eight-spoked asterisk [asterisk | eight-spoked asterisk]'
'✴: eight-pointed star [eight-pointed star | star]'
'❇: sparkle [sparkle]'
'‼: double exclamation mark [bangbang | double exclamation mark | exclamation | mark | punctuation]'
'⁉: exclamation question mark [exclamation | interrobang | mark | punctuation | question]'
'❓: question mark [mark | punctuation | question]'
'❔: white question mark [mark | outlined | punctuation | question | white question mark]'
'❕: white exclamation mark [exclamation | mark | outlined | punctuation | white exclamation mark]'
'❗: exclamation mark [exclamation | mark | punctuation]'
'〰: wavy dash [dash | punctuation | wavy]'
'©: copyright [copyright]'
'®: registered [registered]'
'™: trade mark [mark | tm | trade mark | trademark]'
'#️⃣: keycap: # [keycap]'
'*️⃣: keycap: * [keycap]'
'0️⃣: keycap: 0 [keycap]'
'1️⃣: keycap: 1 [keycap]'
'2️⃣: keycap: 2 [keycap]'
'3️⃣: keycap: 3 [keycap]'
'4️⃣: keycap: 4 [keycap]'
'5️⃣: keycap: 5 [keycap]'
'6️⃣: keycap: 6 [keycap]'
'7️⃣: keycap: 7 [keycap]'
'8️⃣: keycap: 8 [keycap]'
'9️⃣: keycap: 9 [keycap]'
'🔟: keycap: 10 [keycap]'
'💯: hundred points [100 | full | hundred | hundred points | score]'
'🔠: input latin uppercase [ABCD | input | latin | letters | uppercase]'
'🔡: input latin lowercase [abcd | input | latin | letters | lowercase]'
'🔢: input numbers [1234 | input | numbers]'
'🔣: input symbols [〒♪&% | input | input symbols]'
'🔤: input latin letters [abc | alphabet | input | latin | letters]'
'🅰: A button (blood type) [a | A button (blood type) | blood type]'
'🆎: AB button (blood type) [ab | AB button (blood type) | blood type]'
'🅱: B button (blood type) [b | B button (blood type) | blood type]'
'🆑: CL button [cl | CL button]'
'🆒: COOL button [cool | COOL button]'
'🆓: FREE button [free | FREE button]'
'ℹ: information [i | information]'
'🆔: ID button [id | ID button | identity]'
'Ⓜ: circled M [circle | circled M | m]'
'🆕: NEW button [new | NEW button]'
'🆖: NG button [ng | NG button]'
'🅾: O button (blood type) [blood type | o | O button (blood type)]'
'🆗: OK button [OK | OK button]'
'🅿: P button [P button | parking]'
'🆘: SOS button [help | sos | SOS button]'
'🆙: UP! button [mark | up | UP! button]'
'🆚: VS button [versus | vs | VS button]'
'🈁: Japanese “here” button [“here” | Japanese | Japanese “here” button | katakana | ココ]'
'🈂: Japanese “service charge” button [“service charge” | Japanese | Japanese “service charge” button | katakana | サ]'
'🈷: Japanese “monthly amount” button [“monthly amount” | ideograph | Japanese | Japanese “monthly amount” button | 月]'
'🈶: Japanese “not free of charge” button [“not free of charge” | ideograph | Japanese | Japanese “not free of charge” button | 有]'
'🈯: Japanese “reserved” button [“reserved” | ideograph | Japanese | Japanese “reserved” button | 指]'
'🉐: Japanese “bargain” button [“bargain” | ideograph | Japanese | Japanese “bargain” button | 得]'
'🈹: Japanese “discount” button [“discount” | ideograph | Japanese | Japanese “discount” button | 割]'
'🈚: Japanese “free of charge” button [“free of charge” | ideograph | Japanese | Japanese “free of charge” button | 無]'
'🈲: Japanese “prohibited” button [“prohibited” | ideograph | Japanese | Japanese “prohibited” button | 禁]'
'🉑: Japanese “acceptable” button [“acceptable” | ideograph | Japanese | Japanese “acceptable” button | 可]'
'🈸: Japanese “application” button [“application” | ideograph | Japanese | Japanese “application” button | 申]'
'🈴: Japanese “passing grade” button [“passing grade” | ideograph | Japanese | Japanese “passing grade” button | 合]'
'🈳: Japanese “vacancy” button [“vacancy” | ideograph | Japanese | Japanese “vacancy” button | 空]'
'㊗: Japanese “congratulations” button [“congratulations” | ideograph | Japanese | Japanese “congratulations” button | 祝]'
'㊙: Japanese “secret” button [“secret” | ideograph | Japanese | Japanese “secret” button | 秘]'
'🈺: Japanese “open for business” button [“open for business” | ideograph | Japanese | Japanese “open for business” button | 営]'
'🈵: Japanese “no vacancy” button [“no vacancy” | ideograph | Japanese | Japanese “no vacancy” button | 満]'
'▪: black small square [black small square | geometric | square]'
'▫: white small square [geometric | square | white small square]'
'◻: white medium square [geometric | square | white medium square]'
'◼: black medium square [black medium square | geometric | square]'
'◽: white medium-small square [geometric | square | white medium-small square]'
'◾: black medium-small square [black medium-small square | geometric | square]'
'⬛: black large square [black large square | geometric | square]'
'⬜: white large square [geometric | square | white large square]'
'🔶: large orange diamond [diamond | geometric | large orange diamond | orange]'
'🔷: large blue diamond [blue | diamond | geometric | large blue diamond]'
'🔸: small orange diamond [diamond | geometric | orange | small orange diamond]'
'🔹: small blue diamond [blue | diamond | geometric | small blue diamond]'
'🔺: red triangle pointed up [geometric | red | red triangle pointed up]'
'🔻: red triangle pointed down [down | geometric | red | red triangle pointed down]'
'💠: diamond with a dot [comic | diamond | diamond with a dot | geometric | inside]'
'🔘: radio button [button | geometric | radio]'
'🔲: black square button [black square button | button | geometric | square]'
'🔳: white square button [button | geometric | outlined | square | white square button]'
'⚪: white circle [circle | geometric | white circle]'
'⚫: black circle [black circle | circle | geometric]'
'🔴: red circle [circle | geometric | red]'
'🔵: blue circle [blue | circle | geometric]'
'🏁: chequered flag [checkered | chequered | chequered flag | racing]'
'🚩: triangular flag [post | triangular flag]'
'🎌: crossed flags [celebration | cross | crossed | crossed flags | Japanese]'
'🏴: black flag [black flag | waving]'
'🏳: white flag [waving | white flag]'
'🏳️‍🌈: rainbow flag [rainbow | rainbow flag]'
'🏴‍☠️: ⊛ pirate flag [Jolly Roger | pirate | plunder | treasure]'
'🇦🇨: Ascension Island [flag]'
'🇦🇩: Andorra [flag]'
'🇦🇪: United Arab Emirates [flag]'
'🇦🇫: Afghanistan [flag]'
'🇦🇬: Antigua & Barbuda [flag]'
'🇦🇮: Anguilla [flag]'
'🇦🇱: Albania [flag]'
'🇦🇲: Armenia [flag]'
'🇦🇴: Angola [flag]'
'🇦🇶: Antarctica [flag]'
'🇦🇷: Argentina [flag]'
'🇦🇸: American Samoa [flag]'
'🇦🇹: Austria [flag]'
'🇦🇺: Australia [flag]'
'🇦🇼: Aruba [flag]'
'🇦🇽: Åland Islands [flag]'
'🇦🇿: Azerbaijan [flag]'
'🇧🇦: Bosnia & Herzegovina [flag]'
'🇧🇧: Barbados [flag]'
'🇧🇩: Bangladesh [flag]'
'🇧🇪: Belgium [flag]'
'🇧🇫: Burkina Faso [flag]'
'🇧🇬: Bulgaria [flag]'
'🇧🇭: Bahrain [flag]'
'🇧🇮: Burundi [flag]'
'🇧🇯: Benin [flag]'
'🇧🇱: St. Barthélemy [flag]'
'🇧🇲: Bermuda [flag]'
'🇧🇳: Brunei [flag]'
'🇧🇴: Bolivia [flag]'
'🇧🇶: Caribbean Netherlands [flag]'
'🇧🇷: Brazil [flag]'
'🇧🇸: Bahamas [flag]'
'🇧🇹: Bhutan [flag]'
'🇧🇻: Bouvet Island [flag]'
'🇧🇼: Botswana [flag]'
'🇧🇾: Belarus [flag]'
'🇧🇿: Belize [flag]'
'🇨🇦: Canada [flag]'
'🇨🇨: Cocos (Keeling) Islands [flag]'
'🇨🇩: Congo - Kinshasa [flag]'
'🇨🇫: Central African Republic [flag]'
'🇨🇬: Congo - Brazzaville [flag]'
'🇨🇭: Switzerland [flag]'
'🇨🇮: Côte d’Ivoire [flag]'
'🇨🇰: Cook Islands [flag]'
'🇨🇱: Chile [flag]'
'🇨🇲: Cameroon [flag]'
'🇨🇳: China [flag]'
'🇨🇴: Colombia [flag]'
'🇨🇵: Clipperton Island [flag]'
'🇨🇷: Costa Rica [flag]'
'🇨🇺: Cuba [flag]'
'🇨🇻: Cape Verde [flag]'
'🇨🇼: Curaçao [flag]'
'🇨🇽: Christmas Island [flag]'
'🇨🇾: Cyprus [flag]'
'🇨🇿: Czechia [flag]'
'🇩🇪: Germany [flag]'
'🇩🇬: Diego Garcia [flag]'
'🇩🇯: Djibouti [flag]'
'🇩🇰: Denmark [flag]'
'🇩🇲: Dominica [flag]'
'🇩🇴: Dominican Republic [flag]'
'🇩🇿: Algeria [flag]'
'🇪🇦: Ceuta & Melilla [flag]'
'🇪🇨: Ecuador [flag]'
'🇪🇪: Estonia [flag]'
'🇪🇬: Egypt [flag]'
'🇪🇭: Western Sahara [flag]'
'🇪🇷: Eritrea [flag]'
'🇪🇸: Spain [flag]'
'🇪🇹: Ethiopia [flag]'
'🇪🇺: European Union [flag]'
'🇫🇮: Finland [flag]'
'🇫🇯: Fiji [flag]'
'🇫🇰: Falkland Islands [flag]'
'🇫🇲: Micronesia [flag]'
'🇫🇴: Faroe Islands [flag]'
'🇫🇷: France [flag]'
'🇬🇦: Gabon [flag]'
'🇬🇧: United Kingdom [flag]'
'🇬🇩: Grenada [flag]'
'🇬🇪: Georgia [flag]'
'🇬🇫: French Guiana [flag]'
'🇬🇬: Guernsey [flag]'
'🇬🇭: Ghana [flag]'
'🇬🇮: Gibraltar [flag]'
'🇬🇱: Greenland [flag]'
'🇬🇲: Gambia [flag]'
'🇬🇳: Guinea [flag]'
'🇬🇵: Guadeloupe [flag]'
'🇬🇶: Equatorial Guinea [flag]'
'🇬🇷: Greece [flag]'
'🇬🇸: South Georgia & South Sandwich Islands [flag]'
'🇬🇹: Guatemala [flag]'
'🇬🇺: Guam [flag]'
'🇬🇼: Guinea-Bissau [flag]'
'🇬🇾: Guyana [flag]'
'🇭🇰: Hong Kong SAR China [flag]'
'🇭🇲: Heard & McDonald Islands [flag]'
'🇭🇳: Honduras [flag]'
'🇭🇷: Croatia [flag]'
'🇭🇹: Haiti [flag]'
'🇭🇺: Hungary [flag]'
'🇮🇨: Canary Islands [flag]'
'🇮🇩: Indonesia [flag]'
'🇮🇪: Ireland [flag]'
'🇮🇱: Israel [flag]'
'🇮🇲: Isle of Man [flag]'
'🇮🇳: India [flag]'
'🇮🇴: British Indian Ocean Territory [flag]'
'🇮🇶: Iraq [flag]'
'🇮🇷: Iran [flag]'
'🇮🇸: Iceland [flag]'
'🇮🇹: Italy [flag]'
'🇯🇪: Jersey [flag]'
'🇯🇲: Jamaica [flag]'
'🇯🇴: Jordan [flag]'
'🇯🇵: Japan [flag]'
'🇰🇪: Kenya [flag]'
'🇰🇬: Kyrgyzstan [flag]'
'🇰🇭: Cambodia [flag]'
'🇰🇮: Kiribati [flag]'
'🇰🇲: Comoros [flag]'
'🇰🇳: St. Kitts & Nevis [flag]'
'🇰🇵: North Korea [flag]'
'🇰🇷: South Korea [flag]'
'🇰🇼: Kuwait [flag]'
'🇰🇾: Cayman Islands [flag]'
'🇰🇿: Kazakhstan [flag]'
'🇱🇦: Laos [flag]'
'🇱🇧: Lebanon [flag]'
'🇱🇨: St. Lucia [flag]'
'🇱🇮: Liechtenstein [flag]'
'🇱🇰: Sri Lanka [flag]'
'🇱🇷: Liberia [flag]'
'🇱🇸: Lesotho [flag]'
'🇱🇹: Lithuania [flag]'
'🇱🇺: Luxembourg [flag]'
'🇱🇻: Latvia [flag]'
'🇱🇾: Libya [flag]'
'🇲🇦: Morocco [flag]'
'🇲🇨: Monaco [flag]'
'🇲🇩: Moldova [flag]'
'🇲🇪: Montenegro [flag]'
'🇲🇫: St. Martin [flag]'
'🇲🇬: Madagascar [flag]'
'🇲🇭: Marshall Islands [flag]'
'🇲🇰: Macedonia [flag]'
'🇲🇱: Mali [flag]'
'🇲🇲: Myanmar (Burma) [flag]'
'🇲🇳: Mongolia [flag]'
'🇲🇴: Macau SAR China [flag]'
'🇲🇵: Northern Mariana Islands [flag]'
'🇲🇶: Martinique [flag]'
'🇲🇷: Mauritania [flag]'
'🇲🇸: Montserrat [flag]'
'🇲🇹: Malta [flag]'
'🇲🇺: Mauritius [flag]'
'🇲🇻: Maldives [flag]'
'🇲🇼: Malawi [flag]'
'🇲🇽: Mexico [flag]'
'🇲🇾: Malaysia [flag]'
'🇲🇿: Mozambique [flag]'
'🇳🇦: Namibia [flag]'
'🇳🇨: New Caledonia [flag]'
'🇳🇪: Niger [flag]'
'🇳🇫: Norfolk Island [flag]'
'🇳🇬: Nigeria [flag]'
'🇳🇮: Nicaragua [flag]'
'🇳🇱: Netherlands [flag]'
'🇳🇴: Norway [flag]'
'🇳🇵: Nepal [flag]'
'🇳🇷: Nauru [flag]'
'🇳🇺: Niue [flag]'
'🇳🇿: New Zealand [flag]'
'🇴🇲: Oman [flag]'
'🇵🇦: Panama [flag]'
'🇵🇪: Peru [flag]'
'🇵🇫: French Polynesia [flag]'
'🇵🇬: Papua New Guinea [flag]'
'🇵🇭: Philippines [flag]'
'🇵🇰: Pakistan [flag]'
'🇵🇱: Poland [flag]'
'🇵🇲: St. Pierre & Miquelon [flag]'
'🇵🇳: Pitcairn Islands [flag]'
'🇵🇷: Puerto Rico [flag]'
'🇵🇸: Palestinian Territories [flag]'
'🇵🇹: Portugal [flag]'
'🇵🇼: Palau [flag]'
'🇵🇾: Paraguay [flag]'
'🇶🇦: Qatar [flag]'
'🇷🇪: Réunion [flag]'
'🇷🇴: Romania [flag]'
'🇷🇸: Serbia [flag]'
'🇷🇺: Russia [flag]'
'🇷🇼: Rwanda [flag]'
'🇸🇦: Saudi Arabia [flag]'
'🇸🇧: Solomon Islands [flag]'
'🇸🇨: Seychelles [flag]'
'🇸🇩: Sudan [flag]'
'🇸🇪: Sweden [flag]'
'🇸🇬: Singapore [flag]'
'🇸🇭: St. Helena [flag]'
'🇸🇮: Slovenia [flag]'
'🇸🇯: Svalbard & Jan Mayen [flag]'
'🇸🇰: Slovakia [flag]'
'🇸🇱: Sierra Leone [flag]'
'🇸🇲: San Marino [flag]'
'🇸🇳: Senegal [flag]'
'🇸🇴: Somalia [flag]'
'🇸🇷: Suriname [flag]'
'🇸🇸: South Sudan [flag]'
'🇸🇹: São Tomé & Príncipe [flag]'
'🇸🇻: El Salvador [flag]'
'🇸🇽: Sint Maarten [flag]'
'🇸🇾: Syria [flag]'
'🇸🇿: Swaziland [flag]'
'🇹🇦: Tristan da Cunha [flag]'
'🇹🇨: Turks & Caicos Islands [flag]'
'🇹🇩: Chad [flag]'
'🇹🇫: French Southern Territories [flag]'
'🇹🇬: Togo [flag]'
'🇹🇭: Thailand [flag]'
'🇹🇯: Tajikistan [flag]'
'🇹🇰: Tokelau [flag]'
'🇹🇱: Timor-Leste [flag]'
'🇹🇲: Turkmenistan [flag]'
'🇹🇳: Tunisia [flag]'
'🇹🇴: Tonga [flag]'
'🇹🇷: Turkey [flag]'
'🇹🇹: Trinidad & Tobago [flag]'
'🇹🇻: Tuvalu [flag]'
'🇹🇼: Taiwan [flag]'
'🇹🇿: Tanzania [flag]'
'🇺🇦: Ukraine [flag]'
'🇺🇬: Uganda [flag]'
'🇺🇲: U.S. Outlying Islands [flag]'
'🇺🇳: United Nations [flag]'
'🇺🇸: United States [flag]'
'🇺🇾: Uruguay [flag]'
'🇺🇿: Uzbekistan [flag]'
'🇻🇦: Vatican City [flag]'
'🇻🇨: St. Vincent & Grenadines [flag]'
'🇻🇪: Venezuela [flag]'
'🇻🇬: British Virgin Islands [flag]'
'🇻🇮: U.S. Virgin Islands [flag]'
'🇻🇳: Vietnam [flag]'
'🇻🇺: Vanuatu [flag]'
'🇼🇫: Wallis & Futuna [flag]'
'🇼🇸: Samoa [flag]'
'🇽🇰: Kosovo [flag]'
'🇾🇪: Yemen [flag]'
'🇾🇹: Mayotte [flag]'
'🇿🇦: South Africa [flag]'
'🇿🇲: Zambia [flag]'
'🇿🇼: Zimbabwe [flag]'
'🏴󠁧󠁢󠁥󠁮󠁧󠁿: England [flag]'
'🏴󠁧󠁢󠁳󠁣󠁴󠁿: Scotland [flag]'
'🏴󠁧󠁢󠁷󠁬󠁳󠁿: Wales [flag]'
)
