emojis=(
    '#️⃣: keycap # [Symbols]'
    '*️⃣: keycap * [Symbols]'
    '0️⃣: keycap 0 [Symbols]'
    '1️⃣: keycap 1 [Symbols]'
    '2️⃣: keycap 2 [Symbols]'
    '3️⃣: keycap 3 [Symbols]'
    '4️⃣: keycap 4 [Symbols]'
    '5️⃣: keycap 5 [Symbols]'
    '6️⃣: keycap 6 [Symbols]'
    '7️⃣: keycap 7 [Symbols]'
    '8️⃣: keycap 8 [Symbols]'
    '9️⃣: keycap 9 [Symbols]'
    '©️: copyright [Symbols]'
    '®️: registered [Symbols]'
    '‼️: double exclamation mark [Symbols]'
    '⁉️: exclamation question mark [Symbols]'
    '™️: trade mark [Symbols]'
    'ℹ️: information [Symbols]'
    '↔️: left-right arrow [Symbols]'
    '↕️: up-down arrow [Symbols]'
    '↖️: up-left arrow [Symbols]'
    '↗️: up-right arrow [Symbols]'
    '↘️: down-right arrow [Symbols]'
    '↙️: down-left arrow [Symbols]'
    '↩️: right arrow curving left [Symbols]'
    '↪️: left arrow curving right [Symbols]'
    '⌚: watch [Travel & Places]'
    '⌛: hourglass done [Travel & Places]'
    '⌨️: keyboard [Objects]'
    '⏏️: eject button [Symbols]'
    '⏩: fast-forward button [Symbols]'
    '⏪: fast reverse button [Symbols]'
    '⏫: fast up button [Symbols]'
    '⏬: fast down button [Symbols]'
    '⏭️: next track button [Symbols]'
    '⏮️: last track button [Symbols]'
    '⏯️: play or pause button [Symbols]'
    '⏰: alarm clock [Travel & Places]'
    '⏱️: stopwatch [Travel & Places]'
    '⏲️: timer clock [Travel & Places]'
    '⏳: hourglass not done [Travel & Places]'
    '⏸️: pause button [Symbols]'
    '⏹️: stop button [Symbols]'
    '⏺️: record button [Symbols]'
    'Ⓜ️: circled M [Symbols]'
    '▪️: black small square [Symbols]'
    '▫️: white small square [Symbols]'
    '▶️: play button [Symbols]'
    '◀️: reverse button [Symbols]'
    '◻️: white medium square [Symbols]'
    '◼️: black medium square [Symbols]'
    '◽: white medium-small square [Symbols]'
    '◾: black medium-small square [Symbols]'
    '☀️: sun [Travel & Places]'
    '☁️: cloud [Travel & Places]'
    '☂️: umbrella [Travel & Places]'
    '☃️: snowman [Travel & Places]'
    '☄️: comet [Travel & Places]'
    '☎️: telephone [Objects]'
    '☑️: check box with check [Symbols]'
    '☔: umbrella with rain drops [Travel & Places]'
    '☕: hot beverage [Food & Drink]'
    '☘️: shamrock [Animals & Nature]'
    '☝️: index pointing up [People & Body]'
    '☠️: skull and crossbones [Smileys & Emotion]'
    '☢️: radioactive [Symbols]'
    '☣️: biohazard [Symbols]'
    '☦️: orthodox cross [Symbols]'
    '☪️: star and crescent [Symbols]'
    '☮️: peace symbol [Symbols]'
    '☯️: yin yang [Symbols]'
    '☸️: wheel of dharma [Symbols]'
    '☹️: frowning face [Smileys & Emotion]'
    '☺️: smiling face [Smileys & Emotion]'
    '♀️: female sign [Symbols]'
    '♂️: male sign [Symbols]'
    '♈: Aries [Symbols]'
    '♉: Taurus [Symbols]'
    '♊: Gemini [Symbols]'
    '♋: Cancer [Symbols]'
    '♌: Leo [Symbols]'
    '♍: Virgo [Symbols]'
    '♎: Libra [Symbols]'
    '♏: Scorpio [Symbols]'
    '♐: Sagittarius [Symbols]'
    '♑: Capricorn [Symbols]'
    '♒: Aquarius [Symbols]'
    '♓: Pisces [Symbols]'
    '♟️: chess pawn [Activities]'
    '♠️: spade suit [Activities]'
    '♣️: club suit [Activities]'
    '♥️: heart suit [Activities]'
    '♦️: diamond suit [Activities]'
    '♨️: hot springs [Travel & Places]'
    '♻️: recycling symbol [Symbols]'
    '♾️: infinity [Symbols]'
    '♿: wheelchair symbol [Symbols]'
    '⚒️: hammer and pick [Objects]'
    '⚓: anchor [Travel & Places]'
    '⚔️: crossed swords [Objects]'
    '⚕️: medical symbol [Symbols]'
    '⚖️: balance scale [Objects]'
    '⚗️: alembic [Objects]'
    '⚙️: gear [Objects]'
    '⚛️: atom symbol [Symbols]'
    '⚜️: fleur-de-lis [Symbols]'
    '⚠️: warning [Symbols]'
    '⚡: high voltage [Travel & Places]'
    '⚧️: transgender symbol [Symbols]'
    '⚪: white circle [Symbols]'
    '⚫: black circle [Symbols]'
    '⚰️: coffin [Objects]'
    '⚱️: funeral urn [Objects]'
    '⚽: soccer ball [Activities]'
    '⚾: baseball [Activities]'
    '⛄: snowman without snow [Travel & Places]'
    '⛅: sun behind cloud [Travel & Places]'
    '⛈️: cloud with lightning and rain [Travel & Places]'
    '⛎: Ophiuchus [Symbols]'
    '⛏️: pick [Objects]'
    '⛑️: rescue worker’s helmet [Objects]'
    '⛓️: chains [Objects]'
    '⛔: no entry [Symbols]'
    '⛩️: shinto shrine [Travel & Places]'
    '⛪: church [Travel & Places]'
    '⛰️: mountain [Travel & Places]'
    '⛱️: umbrella on ground [Travel & Places]'
    '⛲: fountain [Travel & Places]'
    '⛳: flag in hole [Activities]'
    '⛴️: ferry [Travel & Places]'
    '⛵: sailboat [Travel & Places]'
    '⛷️: skier [People & Body]'
    '⛸️: ice skate [Activities]'
    '⛹️: person bouncing ball [People & Body]'
    '⛹️‍♀️: woman bouncing ball [People & Body]'
    '⛹️‍♂️: man bouncing ball [People & Body]'
    '⛺: tent [Travel & Places]'
    '⛽: fuel pump [Travel & Places]'
    '✂️: scissors [Objects]'
    '✅: check mark button [Symbols]'
    '✈️: airplane [Travel & Places]'
    '✉️: envelope [Objects]'
    '✊: raised fist [People & Body]'
    '✋: raised hand [People & Body]'
    '✌️: victory hand [People & Body]'
    '✍️: writing hand [People & Body]'
    '✏️: pencil [Objects]'
    '✒️: black nib [Objects]'
    '✔️: check mark [Symbols]'
    '✖️: multiply [Symbols]'
    '✝️: latin cross [Symbols]'
    '✡️: star of David [Symbols]'
    '✨: sparkles [Activities]'
    '✳️: eight-spoked asterisk [Symbols]'
    '✴️: eight-pointed star [Symbols]'
    '❄️: snowflake [Travel & Places]'
    '❇️: sparkle [Symbols]'
    '❌: cross mark [Symbols]'
    '❎: cross mark button [Symbols]'
    '❓: red question mark [Symbols]'
    '❔: white question mark [Symbols]'
    '❕: white exclamation mark [Symbols]'
    '❗: red exclamation mark [Symbols]'
    '❣️: heart exclamation [Smileys & Emotion]'
    '❤️: red heart [Smileys & Emotion]'
    '❤️‍🔥: heart on fire [Smileys & Emotion]'
    '❤️‍🩹: mending heart [Smileys & Emotion]'
    '➕: plus [Symbols]'
    '➖: minus [Symbols]'
    '➗: divide [Symbols]'
    '➡️: right arrow [Symbols]'
    '➰: curly loop [Symbols]'
    '➿: double curly loop [Symbols]'
    '⤴️: right arrow curving up [Symbols]'
    '⤵️: right arrow curving down [Symbols]'
    '⬅️: left arrow [Symbols]'
    '⬆️: up arrow [Symbols]'
    '⬇️: down arrow [Symbols]'
    '⬛: black large square [Symbols]'
    '⬜: white large square [Symbols]'
    '⭐: star [Travel & Places]'
    '⭕: hollow red circle [Symbols]'
    '〰️: wavy dash [Symbols]'
    '〽️: part alternation mark [Symbols]'
    '㊗️: Japanese “congratulations” button [Symbols]'
    '㊙️: Japanese “secret” button [Symbols]'
    '🀄: mahjong red dragon [Activities]'
    '🃏: joker [Activities]'
    '🅰️: A button (blood type) [Symbols]'
    '🅱️: B button (blood type) [Symbols]'
    '🅾️: O button (blood type) [Symbols]'
    '🅿️: P button [Symbols]'
    '🆎: AB button (blood type) [Symbols]'
    '🆑: CL button [Symbols]'
    '🆒: COOL button [Symbols]'
    '🆓: FREE button [Symbols]'
    '🆔: ID button [Symbols]'
    '🆕: NEW button [Symbols]'
    '🆖: NG button [Symbols]'
    '🆗: OK button [Symbols]'
    '🆘: SOS button [Symbols]'
    '🆙: UP! button [Symbols]'
    '🆚: VS button [Symbols]'
    '🇦🇨: flag Ascension Island [Flags]'
    '🇦🇩: flag Andorra [Flags]'
    '🇦🇪: flag United Arab Emirates [Flags]'
    '🇦🇫: flag Afghanistan [Flags]'
    '🇦🇬: flag Antigua & Barbuda [Flags]'
    '🇦🇮: flag Anguilla [Flags]'
    '🇦🇱: flag Albania [Flags]'
    '🇦🇲: flag Armenia [Flags]'
    '🇦🇴: flag Angola [Flags]'
    '🇦🇶: flag Antarctica [Flags]'
    '🇦🇷: flag Argentina [Flags]'
    '🇦🇸: flag American Samoa [Flags]'
    '🇦🇹: flag Austria [Flags]'
    '🇦🇺: flag Australia [Flags]'
    '🇦🇼: flag Aruba [Flags]'
    '🇦🇽: flag Åland Islands [Flags]'
    '🇦🇿: flag Azerbaijan [Flags]'
    '🇧🇦: flag Bosnia & Herzegovina [Flags]'
    '🇧🇧: flag Barbados [Flags]'
    '🇧🇩: flag Bangladesh [Flags]'
    '🇧🇪: flag Belgium [Flags]'
    '🇧🇫: flag Burkina Faso [Flags]'
    '🇧🇬: flag Bulgaria [Flags]'
    '🇧🇭: flag Bahrain [Flags]'
    '🇧🇮: flag Burundi [Flags]'
    '🇧🇯: flag Benin [Flags]'
    '🇧🇱: flag St. Barthélemy [Flags]'
    '🇧🇲: flag Bermuda [Flags]'
    '🇧🇳: flag Brunei [Flags]'
    '🇧🇴: flag Bolivia [Flags]'
    '🇧🇶: flag Caribbean Netherlands [Flags]'
    '🇧🇷: flag Brazil [Flags]'
    '🇧🇸: flag Bahamas [Flags]'
    '🇧🇹: flag Bhutan [Flags]'
    '🇧🇻: flag Bouvet Island [Flags]'
    '🇧🇼: flag Botswana [Flags]'
    '🇧🇾: flag Belarus [Flags]'
    '🇧🇿: flag Belize [Flags]'
    '🇨🇦: flag Canada [Flags]'
    '🇨🇨: flag Cocos (Keeling) Islands [Flags]'
    '🇨🇩: flag Congo - Kinshasa [Flags]'
    '🇨🇫: flag Central African Republic [Flags]'
    '🇨🇬: flag Congo - Brazzaville [Flags]'
    '🇨🇭: flag Switzerland [Flags]'
    '🇨🇮: flag Côte d’Ivoire [Flags]'
    '🇨🇰: flag Cook Islands [Flags]'
    '🇨🇱: flag Chile [Flags]'
    '🇨🇲: flag Cameroon [Flags]'
    '🇨🇳: flag China [Flags]'
    '🇨🇴: flag Colombia [Flags]'
    '🇨🇵: flag Clipperton Island [Flags]'
    '🇨🇷: flag Costa Rica [Flags]'
    '🇨🇺: flag Cuba [Flags]'
    '🇨🇻: flag Cape Verde [Flags]'
    '🇨🇼: flag Curaçao [Flags]'
    '🇨🇽: flag Christmas Island [Flags]'
    '🇨🇾: flag Cyprus [Flags]'
    '🇨🇿: flag Czechia [Flags]'
    '🇩🇪: flag Germany [Flags]'
    '🇩🇬: flag Diego Garcia [Flags]'
    '🇩🇯: flag Djibouti [Flags]'
    '🇩🇰: flag Denmark [Flags]'
    '🇩🇲: flag Dominica [Flags]'
    '🇩🇴: flag Dominican Republic [Flags]'
    '🇩🇿: flag Algeria [Flags]'
    '🇪🇦: flag Ceuta & Melilla [Flags]'
    '🇪🇨: flag Ecuador [Flags]'
    '🇪🇪: flag Estonia [Flags]'
    '🇪🇬: flag Egypt [Flags]'
    '🇪🇭: flag Western Sahara [Flags]'
    '🇪🇷: flag Eritrea [Flags]'
    '🇪🇸: flag Spain [Flags]'
    '🇪🇹: flag Ethiopia [Flags]'
    '🇪🇺: flag European Union [Flags]'
    '🇫🇮: flag Finland [Flags]'
    '🇫🇯: flag Fiji [Flags]'
    '🇫🇰: flag Falkland Islands [Flags]'
    '🇫🇲: flag Micronesia [Flags]'
    '🇫🇴: flag Faroe Islands [Flags]'
    '🇫🇷: flag France [Flags]'
    '🇬🇦: flag Gabon [Flags]'
    '🇬🇧: flag United Kingdom [Flags]'
    '🇬🇩: flag Grenada [Flags]'
    '🇬🇪: flag Georgia [Flags]'
    '🇬🇫: flag French Guiana [Flags]'
    '🇬🇬: flag Guernsey [Flags]'
    '🇬🇭: flag Ghana [Flags]'
    '🇬🇮: flag Gibraltar [Flags]'
    '🇬🇱: flag Greenland [Flags]'
    '🇬🇲: flag Gambia [Flags]'
    '🇬🇳: flag Guinea [Flags]'
    '🇬🇵: flag Guadeloupe [Flags]'
    '🇬🇶: flag Equatorial Guinea [Flags]'
    '🇬🇷: flag Greece [Flags]'
    '🇬🇸: flag South Georgia & South Sandwich Islands [Flags]'
    '🇬🇹: flag Guatemala [Flags]'
    '🇬🇺: flag Guam [Flags]'
    '🇬🇼: flag Guinea-Bissau [Flags]'
    '🇬🇾: flag Guyana [Flags]'
    '🇭🇰: flag Hong Kong SAR China [Flags]'
    '🇭🇲: flag Heard & McDonald Islands [Flags]'
    '🇭🇳: flag Honduras [Flags]'
    '🇭🇷: flag Croatia [Flags]'
    '🇭🇹: flag Haiti [Flags]'
    '🇭🇺: flag Hungary [Flags]'
    '🇮🇨: flag Canary Islands [Flags]'
    '🇮🇩: flag Indonesia [Flags]'
    '🇮🇪: flag Ireland [Flags]'
    '🇮🇱: flag Israel [Flags]'
    '🇮🇲: flag Isle of Man [Flags]'
    '🇮🇳: flag India [Flags]'
    '🇮🇴: flag British Indian Ocean Territory [Flags]'
    '🇮🇶: flag Iraq [Flags]'
    '🇮🇷: flag Iran [Flags]'
    '🇮🇸: flag Iceland [Flags]'
    '🇮🇹: flag Italy [Flags]'
    '🇯🇪: flag Jersey [Flags]'
    '🇯🇲: flag Jamaica [Flags]'
    '🇯🇴: flag Jordan [Flags]'
    '🇯🇵: flag Japan [Flags]'
    '🇰🇪: flag Kenya [Flags]'
    '🇰🇬: flag Kyrgyzstan [Flags]'
    '🇰🇭: flag Cambodia [Flags]'
    '🇰🇮: flag Kiribati [Flags]'
    '🇰🇲: flag Comoros [Flags]'
    '🇰🇳: flag St. Kitts & Nevis [Flags]'
    '🇰🇵: flag North Korea [Flags]'
    '🇰🇷: flag South Korea [Flags]'
    '🇰🇼: flag Kuwait [Flags]'
    '🇰🇾: flag Cayman Islands [Flags]'
    '🇰🇿: flag Kazakhstan [Flags]'
    '🇱🇦: flag Laos [Flags]'
    '🇱🇧: flag Lebanon [Flags]'
    '🇱🇨: flag St. Lucia [Flags]'
    '🇱🇮: flag Liechtenstein [Flags]'
    '🇱🇰: flag Sri Lanka [Flags]'
    '🇱🇷: flag Liberia [Flags]'
    '🇱🇸: flag Lesotho [Flags]'
    '🇱🇹: flag Lithuania [Flags]'
    '🇱🇺: flag Luxembourg [Flags]'
    '🇱🇻: flag Latvia [Flags]'
    '🇱🇾: flag Libya [Flags]'
    '🇲🇦: flag Morocco [Flags]'
    '🇲🇨: flag Monaco [Flags]'
    '🇲🇩: flag Moldova [Flags]'
    '🇲🇪: flag Montenegro [Flags]'
    '🇲🇫: flag St. Martin [Flags]'
    '🇲🇬: flag Madagascar [Flags]'
    '🇲🇭: flag Marshall Islands [Flags]'
    '🇲🇰: flag North Macedonia [Flags]'
    '🇲🇱: flag Mali [Flags]'
    '🇲🇲: flag Myanmar (Burma) [Flags]'
    '🇲🇳: flag Mongolia [Flags]'
    '🇲🇴: flag Macao SAR China [Flags]'
    '🇲🇵: flag Northern Mariana Islands [Flags]'
    '🇲🇶: flag Martinique [Flags]'
    '🇲🇷: flag Mauritania [Flags]'
    '🇲🇸: flag Montserrat [Flags]'
    '🇲🇹: flag Malta [Flags]'
    '🇲🇺: flag Mauritius [Flags]'
    '🇲🇻: flag Maldives [Flags]'
    '🇲🇼: flag Malawi [Flags]'
    '🇲🇽: flag Mexico [Flags]'
    '🇲🇾: flag Malaysia [Flags]'
    '🇲🇿: flag Mozambique [Flags]'
    '🇳🇦: flag Namibia [Flags]'
    '🇳🇨: flag New Caledonia [Flags]'
    '🇳🇪: flag Niger [Flags]'
    '🇳🇫: flag Norfolk Island [Flags]'
    '🇳🇬: flag Nigeria [Flags]'
    '🇳🇮: flag Nicaragua [Flags]'
    '🇳🇱: flag Netherlands [Flags]'
    '🇳🇴: flag Norway [Flags]'
    '🇳🇵: flag Nepal [Flags]'
    '🇳🇷: flag Nauru [Flags]'
    '🇳🇺: flag Niue [Flags]'
    '🇳🇿: flag New Zealand [Flags]'
    '🇴🇲: flag Oman [Flags]'
    '🇵🇦: flag Panama [Flags]'
    '🇵🇪: flag Peru [Flags]'
    '🇵🇫: flag French Polynesia [Flags]'
    '🇵🇬: flag Papua New Guinea [Flags]'
    '🇵🇭: flag Philippines [Flags]'
    '🇵🇰: flag Pakistan [Flags]'
    '🇵🇱: flag Poland [Flags]'
    '🇵🇲: flag St. Pierre & Miquelon [Flags]'
    '🇵🇳: flag Pitcairn Islands [Flags]'
    '🇵🇷: flag Puerto Rico [Flags]'
    '🇵🇸: flag Palestinian Territories [Flags]'
    '🇵🇹: flag Portugal [Flags]'
    '🇵🇼: flag Palau [Flags]'
    '🇵🇾: flag Paraguay [Flags]'
    '🇶🇦: flag Qatar [Flags]'
    '🇷🇪: flag Réunion [Flags]'
    '🇷🇴: flag Romania [Flags]'
    '🇷🇸: flag Serbia [Flags]'
    '🇷🇺: flag Russia [Flags]'
    '🇷🇼: flag Rwanda [Flags]'
    '🇸🇦: flag Saudi Arabia [Flags]'
    '🇸🇧: flag Solomon Islands [Flags]'
    '🇸🇨: flag Seychelles [Flags]'
    '🇸🇩: flag Sudan [Flags]'
    '🇸🇪: flag Sweden [Flags]'
    '🇸🇬: flag Singapore [Flags]'
    '🇸🇭: flag St. Helena [Flags]'
    '🇸🇮: flag Slovenia [Flags]'
    '🇸🇯: flag Svalbard & Jan Mayen [Flags]'
    '🇸🇰: flag Slovakia [Flags]'
    '🇸🇱: flag Sierra Leone [Flags]'
    '🇸🇲: flag San Marino [Flags]'
    '🇸🇳: flag Senegal [Flags]'
    '🇸🇴: flag Somalia [Flags]'
    '🇸🇷: flag Suriname [Flags]'
    '🇸🇸: flag South Sudan [Flags]'
    '🇸🇹: flag São Tomé & Príncipe [Flags]'
    '🇸🇻: flag El Salvador [Flags]'
    '🇸🇽: flag Sint Maarten [Flags]'
    '🇸🇾: flag Syria [Flags]'
    '🇸🇿: flag Eswatini [Flags]'
    '🇹🇦: flag Tristan da Cunha [Flags]'
    '🇹🇨: flag Turks & Caicos Islands [Flags]'
    '🇹🇩: flag Chad [Flags]'
    '🇹🇫: flag French Southern Territories [Flags]'
    '🇹🇬: flag Togo [Flags]'
    '🇹🇭: flag Thailand [Flags]'
    '🇹🇯: flag Tajikistan [Flags]'
    '🇹🇰: flag Tokelau [Flags]'
    '🇹🇱: flag Timor-Leste [Flags]'
    '🇹🇲: flag Turkmenistan [Flags]'
    '🇹🇳: flag Tunisia [Flags]'
    '🇹🇴: flag Tonga [Flags]'
    '🇹🇷: flag Turkey [Flags]'
    '🇹🇹: flag Trinidad & Tobago [Flags]'
    '🇹🇻: flag Tuvalu [Flags]'
    '🇹🇼: flag Taiwan [Flags]'
    '🇹🇿: flag Tanzania [Flags]'
    '🇺🇦: flag Ukraine [Flags]'
    '🇺🇬: flag Uganda [Flags]'
    '🇺🇲: flag U.S. Outlying Islands [Flags]'
    '🇺🇳: flag United Nations [Flags]'
    '🇺🇸: flag United States [Flags]'
    '🇺🇾: flag Uruguay [Flags]'
    '🇺🇿: flag Uzbekistan [Flags]'
    '🇻🇦: flag Vatican City [Flags]'
    '🇻🇨: flag St. Vincent & Grenadines [Flags]'
    '🇻🇪: flag Venezuela [Flags]'
    '🇻🇬: flag British Virgin Islands [Flags]'
    '🇻🇮: flag U.S. Virgin Islands [Flags]'
    '🇻🇳: flag Vietnam [Flags]'
    '🇻🇺: flag Vanuatu [Flags]'
    '🇼🇫: flag Wallis & Futuna [Flags]'
    '🇼🇸: flag Samoa [Flags]'
    '🇽🇰: flag Kosovo [Flags]'
    '🇾🇪: flag Yemen [Flags]'
    '🇾🇹: flag Mayotte [Flags]'
    '🇿🇦: flag South Africa [Flags]'
    '🇿🇲: flag Zambia [Flags]'
    '🇿🇼: flag Zimbabwe [Flags]'
    '🈁: Japanese “here” button [Symbols]'
    '🈂️: Japanese “service charge” button [Symbols]'
    '🈚: Japanese “free of charge” button [Symbols]'
    '🈯: Japanese “reserved” button [Symbols]'
    '🈲: Japanese “prohibited” button [Symbols]'
    '🈳: Japanese “vacancy” button [Symbols]'
    '🈴: Japanese “passing grade” button [Symbols]'
    '🈵: Japanese “no vacancy” button [Symbols]'
    '🈶: Japanese “not free of charge” button [Symbols]'
    '🈷️: Japanese “monthly amount” button [Symbols]'
    '🈸: Japanese “application” button [Symbols]'
    '🈹: Japanese “discount” button [Symbols]'
    '🈺: Japanese “open for business” button [Symbols]'
    '🉐: Japanese “bargain” button [Symbols]'
    '🉑: Japanese “acceptable” button [Symbols]'
    '🌀: cyclone [Travel & Places]'
    '🌁: foggy [Travel & Places]'
    '🌂: closed umbrella [Travel & Places]'
    '🌃: night with stars [Travel & Places]'
    '🌄: sunrise over mountains [Travel & Places]'
    '🌅: sunrise [Travel & Places]'
    '🌆: cityscape at dusk [Travel & Places]'
    '🌇: sunset [Travel & Places]'
    '🌈: rainbow [Travel & Places]'
    '🌉: bridge at night [Travel & Places]'
    '🌊: water wave [Travel & Places]'
    '🌋: volcano [Travel & Places]'
    '🌌: milky way [Travel & Places]'
    '🌍: globe showing Europe-Africa [Travel & Places]'
    '🌎: globe showing Americas [Travel & Places]'
    '🌏: globe showing Asia-Australia [Travel & Places]'
    '🌐: globe with meridians [Travel & Places]'
    '🌑: new moon [Travel & Places]'
    '🌒: waxing crescent moon [Travel & Places]'
    '🌓: first quarter moon [Travel & Places]'
    '🌔: waxing gibbous moon [Travel & Places]'
    '🌕: full moon [Travel & Places]'
    '🌖: waning gibbous moon [Travel & Places]'
    '🌗: last quarter moon [Travel & Places]'
    '🌘: waning crescent moon [Travel & Places]'
    '🌙: crescent moon [Travel & Places]'
    '🌚: new moon face [Travel & Places]'
    '🌛: first quarter moon face [Travel & Places]'
    '🌜: last quarter moon face [Travel & Places]'
    '🌝: full moon face [Travel & Places]'
    '🌞: sun with face [Travel & Places]'
    '🌟: glowing star [Travel & Places]'
    '🌠: shooting star [Travel & Places]'
    '🌡️: thermometer [Travel & Places]'
    '🌤️: sun behind small cloud [Travel & Places]'
    '🌥️: sun behind large cloud [Travel & Places]'
    '🌦️: sun behind rain cloud [Travel & Places]'
    '🌧️: cloud with rain [Travel & Places]'
    '🌨️: cloud with snow [Travel & Places]'
    '🌩️: cloud with lightning [Travel & Places]'
    '🌪️: tornado [Travel & Places]'
    '🌫️: fog [Travel & Places]'
    '🌬️: wind face [Travel & Places]'
    '🌭: hot dog [Food & Drink]'
    '🌮: taco [Food & Drink]'
    '🌯: burrito [Food & Drink]'
    '🌰: chestnut [Food & Drink]'
    '🌱: seedling [Animals & Nature]'
    '🌲: evergreen tree [Animals & Nature]'
    '🌳: deciduous tree [Animals & Nature]'
    '🌴: palm tree [Animals & Nature]'
    '🌵: cactus [Animals & Nature]'
    '🌶️: hot pepper [Food & Drink]'
    '🌷: tulip [Animals & Nature]'
    '🌸: cherry blossom [Animals & Nature]'
    '🌹: rose [Animals & Nature]'
    '🌺: hibiscus [Animals & Nature]'
    '🌻: sunflower [Animals & Nature]'
    '🌼: blossom [Animals & Nature]'
    '🌽: ear of corn [Food & Drink]'
    '🌾: sheaf of rice [Animals & Nature]'
    '🌿: herb [Animals & Nature]'
    '🍀: four leaf clover [Animals & Nature]'
    '🍁: maple leaf [Animals & Nature]'
    '🍂: fallen leaf [Animals & Nature]'
    '🍃: leaf fluttering in wind [Animals & Nature]'
    '🍄: mushroom [Food & Drink]'
    '🍅: tomato [Food & Drink]'
    '🍆: eggplant [Food & Drink]'
    '🍇: grapes [Food & Drink]'
    '🍈: melon [Food & Drink]'
    '🍉: watermelon [Food & Drink]'
    '🍊: tangerine [Food & Drink]'
    '🍋: lemon [Food & Drink]'
    '🍌: banana [Food & Drink]'
    '🍍: pineapple [Food & Drink]'
    '🍎: red apple [Food & Drink]'
    '🍏: green apple [Food & Drink]'
    '🍐: pear [Food & Drink]'
    '🍑: peach [Food & Drink]'
    '🍒: cherries [Food & Drink]'
    '🍓: strawberry [Food & Drink]'
    '🍔: hamburger [Food & Drink]'
    '🍕: pizza [Food & Drink]'
    '🍖: meat on bone [Food & Drink]'
    '🍗: poultry leg [Food & Drink]'
    '🍘: rice cracker [Food & Drink]'
    '🍙: rice ball [Food & Drink]'
    '🍚: cooked rice [Food & Drink]'
    '🍛: curry rice [Food & Drink]'
    '🍜: steaming bowl [Food & Drink]'
    '🍝: spaghetti [Food & Drink]'
    '🍞: bread [Food & Drink]'
    '🍟: french fries [Food & Drink]'
    '🍠: roasted sweet potato [Food & Drink]'
    '🍡: dango [Food & Drink]'
    '🍢: oden [Food & Drink]'
    '🍣: sushi [Food & Drink]'
    '🍤: fried shrimp [Food & Drink]'
    '🍥: fish cake with swirl [Food & Drink]'
    '🍦: soft ice cream [Food & Drink]'
    '🍧: shaved ice [Food & Drink]'
    '🍨: ice cream [Food & Drink]'
    '🍩: doughnut [Food & Drink]'
    '🍪: cookie [Food & Drink]'
    '🍫: chocolate bar [Food & Drink]'
    '🍬: candy [Food & Drink]'
    '🍭: lollipop [Food & Drink]'
    '🍮: custard [Food & Drink]'
    '🍯: honey pot [Food & Drink]'
    '🍰: shortcake [Food & Drink]'
    '🍱: bento box [Food & Drink]'
    '🍲: pot of food [Food & Drink]'
    '🍳: cooking [Food & Drink]'
    '🍴: fork and knife [Food & Drink]'
    '🍵: teacup without handle [Food & Drink]'
    '🍶: sake [Food & Drink]'
    '🍷: wine glass [Food & Drink]'
    '🍸: cocktail glass [Food & Drink]'
    '🍹: tropical drink [Food & Drink]'
    '🍺: beer mug [Food & Drink]'
    '🍻: clinking beer mugs [Food & Drink]'
    '🍼: baby bottle [Food & Drink]'
    '🍽️: fork and knife with plate [Food & Drink]'
    '🍾: bottle with popping cork [Food & Drink]'
    '🍿: popcorn [Food & Drink]'
    '🎀: ribbon [Activities]'
    '🎁: wrapped gift [Activities]'
    '🎂: birthday cake [Food & Drink]'
    '🎃: jack-o-lantern [Activities]'
    '🎄: Christmas tree [Activities]'
    '🎅: Santa Claus [People & Body]'
    '🎆: fireworks [Activities]'
    '🎇: sparkler [Activities]'
    '🎈: balloon [Activities]'
    '🎉: party popper [Activities]'
    '🎊: confetti ball [Activities]'
    '🎋: tanabata tree [Activities]'
    '🎌: crossed flags [Flags]'
    '🎍: pine decoration [Activities]'
    '🎎: Japanese dolls [Activities]'
    '🎏: carp streamer [Activities]'
    '🎐: wind chime [Activities]'
    '🎑: moon viewing ceremony [Activities]'
    '🎒: backpack [Objects]'
    '🎓: graduation cap [Objects]'
    '🎖️: military medal [Activities]'
    '🎗️: reminder ribbon [Activities]'
    '🎙️: studio microphone [Objects]'
    '🎚️: level slider [Objects]'
    '🎛️: control knobs [Objects]'
    '🎞️: film frames [Objects]'
    '🎟️: admission tickets [Activities]'
    '🎠: carousel horse [Travel & Places]'
    '🎡: ferris wheel [Travel & Places]'
    '🎢: roller coaster [Travel & Places]'
    '🎣: fishing pole [Activities]'
    '🎤: microphone [Objects]'
    '🎥: movie camera [Objects]'
    '🎦: cinema [Symbols]'
    '🎧: headphone [Objects]'
    '🎨: artist palette [Activities]'
    '🎩: top hat [Objects]'
    '🎪: circus tent [Travel & Places]'
    '🎫: ticket [Activities]'
    '🎬: clapper board [Objects]'
    '🎭: performing arts [Activities]'
    '🎮: video game [Activities]'
    '🎯: bullseye [Activities]'
    '🎰: slot machine [Activities]'
    '🎱: pool 8 ball [Activities]'
    '🎲: game die [Activities]'
    '🎳: bowling [Activities]'
    '🎴: flower playing cards [Activities]'
    '🎵: musical note [Objects]'
    '🎶: musical notes [Objects]'
    '🎷: saxophone [Objects]'
    '🎸: guitar [Objects]'
    '🎹: musical keyboard [Objects]'
    '🎺: trumpet [Objects]'
    '🎻: violin [Objects]'
    '🎼: musical score [Objects]'
    '🎽: running shirt [Activities]'
    '🎾: tennis [Activities]'
    '🎿: skis [Activities]'
    '🏀: basketball [Activities]'
    '🏁: chequered flag [Flags]'
    '🏂: snowboarder [People & Body]'
    '🏃: person running [People & Body]'
    '🏃‍♀️: woman running [People & Body]'
    '🏃‍♂️: man running [People & Body]'
    '🏄: person surfing [People & Body]'
    '🏄‍♀️: woman surfing [People & Body]'
    '🏄‍♂️: man surfing [People & Body]'
    '🏅: sports medal [Activities]'
    '🏆: trophy [Activities]'
    '🏇: horse racing [People & Body]'
    '🏈: american football [Activities]'
    '🏉: rugby football [Activities]'
    '🏊: person swimming [People & Body]'
    '🏊‍♀️: woman swimming [People & Body]'
    '🏊‍♂️: man swimming [People & Body]'
    '🏋️: person lifting weights [People & Body]'
    '🏋️‍♀️: woman lifting weights [People & Body]'
    '🏋️‍♂️: man lifting weights [People & Body]'
    '🏌️: person golfing [People & Body]'
    '🏌️‍♀️: woman golfing [People & Body]'
    '🏌️‍♂️: man golfing [People & Body]'
    '🏍️: motorcycle [Travel & Places]'
    '🏎️: racing car [Travel & Places]'
    '🏏: cricket game [Activities]'
    '🏐: volleyball [Activities]'
    '🏑: field hockey [Activities]'
    '🏒: ice hockey [Activities]'
    '🏓: ping pong [Activities]'
    '🏔️: snow-capped mountain [Travel & Places]'
    '🏕️: camping [Travel & Places]'
    '🏖️: beach with umbrella [Travel & Places]'
    '🏗️: building construction [Travel & Places]'
    '🏘️: houses [Travel & Places]'
    '🏙️: cityscape [Travel & Places]'
    '🏚️: derelict house [Travel & Places]'
    '🏛️: classical building [Travel & Places]'
    '🏜️: desert [Travel & Places]'
    '🏝️: desert island [Travel & Places]'
    '🏞️: national park [Travel & Places]'
    '🏟️: stadium [Travel & Places]'
    '🏠: house [Travel & Places]'
    '🏡: house with garden [Travel & Places]'
    '🏢: office building [Travel & Places]'
    '🏣: Japanese post office [Travel & Places]'
    '🏤: post office [Travel & Places]'
    '🏥: hospital [Travel & Places]'
    '🏦: bank [Travel & Places]'
    '🏧: ATM sign [Symbols]'
    '🏨: hotel [Travel & Places]'
    '🏩: love hotel [Travel & Places]'
    '🏪: convenience store [Travel & Places]'
    '🏫: school [Travel & Places]'
    '🏬: department store [Travel & Places]'
    '🏭: factory [Travel & Places]'
    '🏮: red paper lantern [Objects]'
    '🏯: Japanese castle [Travel & Places]'
    '🏰: castle [Travel & Places]'
    '🏳️: white flag [Flags]'
    '🏳️‍⚧️: transgender flag [Flags]'
    '🏳️‍🌈: rainbow flag [Flags]'
    '🏴: black flag [Flags]'
    '🏴‍☠️: pirate flag [Flags]'
    '🏴󠁧󠁢󠁥󠁮󠁧󠁿: flag England [Flags]'
    '🏴󠁧󠁢󠁳󠁣󠁴󠁿: flag Scotland [Flags]'
    '🏴󠁧󠁢󠁷󠁬󠁳󠁿: flag Wales [Flags]'
    '🏵️: rosette [Animals & Nature]'
    '🏷️: label [Objects]'
    '🏸: badminton [Activities]'
    '🏹: bow and arrow [Objects]'
    '🏺: amphora [Food & Drink]'
    '🐀: rat [Animals & Nature]'
    '🐁: mouse [Animals & Nature]'
    '🐂: ox [Animals & Nature]'
    '🐃: water buffalo [Animals & Nature]'
    '🐄: cow [Animals & Nature]'
    '🐅: tiger [Animals & Nature]'
    '🐆: leopard [Animals & Nature]'
    '🐇: rabbit [Animals & Nature]'
    '🐈: cat [Animals & Nature]'
    '🐈‍⬛: black cat [Animals & Nature]'
    '🐉: dragon [Animals & Nature]'
    '🐊: crocodile [Animals & Nature]'
    '🐋: whale [Animals & Nature]'
    '🐌: snail [Animals & Nature]'
    '🐍: snake [Animals & Nature]'
    '🐎: horse [Animals & Nature]'
    '🐏: ram [Animals & Nature]'
    '🐐: goat [Animals & Nature]'
    '🐑: ewe [Animals & Nature]'
    '🐒: monkey [Animals & Nature]'
    '🐓: rooster [Animals & Nature]'
    '🐔: chicken [Animals & Nature]'
    '🐕: dog [Animals & Nature]'
    '🐕‍🦺: service dog [Animals & Nature]'
    '🐖: pig [Animals & Nature]'
    '🐗: boar [Animals & Nature]'
    '🐘: elephant [Animals & Nature]'
    '🐙: octopus [Animals & Nature]'
    '🐚: spiral shell [Animals & Nature]'
    '🐛: bug [Animals & Nature]'
    '🐜: ant [Animals & Nature]'
    '🐝: honeybee [Animals & Nature]'
    '🐞: lady beetle [Animals & Nature]'
    '🐟: fish [Animals & Nature]'
    '🐠: tropical fish [Animals & Nature]'
    '🐡: blowfish [Animals & Nature]'
    '🐢: turtle [Animals & Nature]'
    '🐣: hatching chick [Animals & Nature]'
    '🐤: baby chick [Animals & Nature]'
    '🐥: front-facing baby chick [Animals & Nature]'
    '🐦: bird [Animals & Nature]'
    '🐧: penguin [Animals & Nature]'
    '🐨: koala [Animals & Nature]'
    '🐩: poodle [Animals & Nature]'
    '🐪: camel [Animals & Nature]'
    '🐫: two-hump camel [Animals & Nature]'
    '🐬: dolphin [Animals & Nature]'
    '🐭: mouse face [Animals & Nature]'
    '🐮: cow face [Animals & Nature]'
    '🐯: tiger face [Animals & Nature]'
    '🐰: rabbit face [Animals & Nature]'
    '🐱: cat face [Animals & Nature]'
    '🐲: dragon face [Animals & Nature]'
    '🐳: spouting whale [Animals & Nature]'
    '🐴: horse face [Animals & Nature]'
    '🐵: monkey face [Animals & Nature]'
    '🐶: dog face [Animals & Nature]'
    '🐷: pig face [Animals & Nature]'
    '🐸: frog [Animals & Nature]'
    '🐹: hamster [Animals & Nature]'
    '🐺: wolf [Animals & Nature]'
    '🐻: bear [Animals & Nature]'
    '🐻‍❄️: polar bear [Animals & Nature]'
    '🐼: panda [Animals & Nature]'
    '🐽: pig nose [Animals & Nature]'
    '🐾: paw prints [Animals & Nature]'
    '🐿️: chipmunk [Animals & Nature]'
    '👀: eyes [People & Body]'
    '👁️: eye [People & Body]'
    '👁️‍🗨️: eye in speech bubble [Smileys & Emotion]'
    '👂: ear [People & Body]'
    '👃: nose [People & Body]'
    '👄: mouth [People & Body]'
    '👅: tongue [People & Body]'
    '👆: backhand index pointing up [People & Body]'
    '👇: backhand index pointing down [People & Body]'
    '👈: backhand index pointing left [People & Body]'
    '👉: backhand index pointing right [People & Body]'
    '👊: oncoming fist [People & Body]'
    '👋: waving hand [People & Body]'
    '👌: OK hand [People & Body]'
    '👍: thumbs up [People & Body]'
    '👎: thumbs down [People & Body]'
    '👏: clapping hands [People & Body]'
    '👐: open hands [People & Body]'
    '👑: crown [Objects]'
    '👒: woman’s hat [Objects]'
    '👓: glasses [Objects]'
    '👔: necktie [Objects]'
    '👕: t-shirt [Objects]'
    '👖: jeans [Objects]'
    '👗: dress [Objects]'
    '👘: kimono [Objects]'
    '👙: bikini [Objects]'
    '👚: woman’s clothes [Objects]'
    '👛: purse [Objects]'
    '👜: handbag [Objects]'
    '👝: clutch bag [Objects]'
    '👞: man’s shoe [Objects]'
    '👟: running shoe [Objects]'
    '👠: high-heeled shoe [Objects]'
    '👡: woman’s sandal [Objects]'
    '👢: woman’s boot [Objects]'
    '👣: footprints [People & Body]'
    '👤: bust in silhouette [People & Body]'
    '👥: busts in silhouette [People & Body]'
    '👦: boy [People & Body]'
    '👧: girl [People & Body]'
    '👨: man [People & Body]'
    '👨‍⚕️: man health worker [People & Body]'
    '👨‍⚖️: man judge [People & Body]'
    '👨‍✈️: man pilot [People & Body]'
    '👨‍❤️‍👨: couple with heart man, man [People & Body]'
    '👨‍❤️‍💋‍👨: kiss man, man [People & Body]'
    '👨‍🌾: man farmer [People & Body]'
    '👨‍🍳: man cook [People & Body]'
    '👨‍🍼: man feeding baby [People & Body]'
    '👨‍🎓: man student [People & Body]'
    '👨‍🎤: man singer [People & Body]'
    '👨‍🎨: man artist [People & Body]'
    '👨‍🏫: man teacher [People & Body]'
    '👨‍🏭: man factory worker [People & Body]'
    '👨‍👦: family man, boy [People & Body]'
    '👨‍👦‍👦: family man, boy, boy [People & Body]'
    '👨‍👧: family man, girl [People & Body]'
    '👨‍👧‍👦: family man, girl, boy [People & Body]'
    '👨‍👧‍👧: family man, girl, girl [People & Body]'
    '👨‍👨‍👦: family man, man, boy [People & Body]'
    '👨‍👨‍👦‍👦: family man, man, boy, boy [People & Body]'
    '👨‍👨‍👧: family man, man, girl [People & Body]'
    '👨‍👨‍👧‍👦: family man, man, girl, boy [People & Body]'
    '👨‍👨‍👧‍👧: family man, man, girl, girl [People & Body]'
    '👨‍👩‍👦: family man, woman, boy [People & Body]'
    '👨‍👩‍👦‍👦: family man, woman, boy, boy [People & Body]'
    '👨‍👩‍👧: family man, woman, girl [People & Body]'
    '👨‍👩‍👧‍👦: family man, woman, girl, boy [People & Body]'
    '👨‍👩‍👧‍👧: family man, woman, girl, girl [People & Body]'
    '👨‍💻: man technologist [People & Body]'
    '👨‍💼: man office worker [People & Body]'
    '👨‍🔧: man mechanic [People & Body]'
    '👨‍🔬: man scientist [People & Body]'
    '👨‍🚀: man astronaut [People & Body]'
    '👨‍🚒: man firefighter [People & Body]'
    '👨‍🦯: man with white cane [People & Body]'
    '👨‍🦰: man red hair [People & Body]'
    '👨‍🦱: man curly hair [People & Body]'
    '👨‍🦲: man bald [People & Body]'
    '👨‍🦳: man white hair [People & Body]'
    '👨‍🦼: man in motorized wheelchair [People & Body]'
    '👨‍🦽: man in manual wheelchair [People & Body]'
    '👩: woman [People & Body]'
    '👩‍⚕️: woman health worker [People & Body]'
    '👩‍⚖️: woman judge [People & Body]'
    '👩‍✈️: woman pilot [People & Body]'
    '👩‍❤️‍👨: couple with heart woman, man [People & Body]'
    '👩‍❤️‍👩: couple with heart woman, woman [People & Body]'
    '👩‍❤️‍💋‍👨: kiss woman, man [People & Body]'
    '👩‍❤️‍💋‍👩: kiss woman, woman [People & Body]'
    '👩‍🌾: woman farmer [People & Body]'
    '👩‍🍳: woman cook [People & Body]'
    '👩‍🍼: woman feeding baby [People & Body]'
    '👩‍🎓: woman student [People & Body]'
    '👩‍🎤: woman singer [People & Body]'
    '👩‍🎨: woman artist [People & Body]'
    '👩‍🏫: woman teacher [People & Body]'
    '👩‍🏭: woman factory worker [People & Body]'
    '👩‍👦: family woman, boy [People & Body]'
    '👩‍👦‍👦: family woman, boy, boy [People & Body]'
    '👩‍👧: family woman, girl [People & Body]'
    '👩‍👧‍👦: family woman, girl, boy [People & Body]'
    '👩‍👧‍👧: family woman, girl, girl [People & Body]'
    '👩‍👩‍👦: family woman, woman, boy [People & Body]'
    '👩‍👩‍👦‍👦: family woman, woman, boy, boy [People & Body]'
    '👩‍👩‍👧: family woman, woman, girl [People & Body]'
    '👩‍👩‍👧‍👦: family woman, woman, girl, boy [People & Body]'
    '👩‍👩‍👧‍👧: family woman, woman, girl, girl [People & Body]'
    '👩‍💻: woman technologist [People & Body]'
    '👩‍💼: woman office worker [People & Body]'
    '👩‍🔧: woman mechanic [People & Body]'
    '👩‍🔬: woman scientist [People & Body]'
    '👩‍🚀: woman astronaut [People & Body]'
    '👩‍🚒: woman firefighter [People & Body]'
    '👩‍🦯: woman with white cane [People & Body]'
    '👩‍🦰: woman red hair [People & Body]'
    '👩‍🦱: woman curly hair [People & Body]'
    '👩‍🦲: woman bald [People & Body]'
    '👩‍🦳: woman white hair [People & Body]'
    '👩‍🦼: woman in motorized wheelchair [People & Body]'
    '👩‍🦽: woman in manual wheelchair [People & Body]'
    '👪: family [People & Body]'
    '👫: woman and man holding hands [People & Body]'
    '👬: men holding hands [People & Body]'
    '👭: women holding hands [People & Body]'
    '👮: police officer [People & Body]'
    '👮‍♀️: woman police officer [People & Body]'
    '👮‍♂️: man police officer [People & Body]'
    '👯: people with bunny ears [People & Body]'
    '👯‍♀️: women with bunny ears [People & Body]'
    '👯‍♂️: men with bunny ears [People & Body]'
    '👰: person with veil [People & Body]'
    '👰‍♀️: woman with veil [People & Body]'
    '👰‍♂️: man with veil [People & Body]'
    '👱: person blond hair [People & Body]'
    '👱‍♀️: woman blond hair [People & Body]'
    '👱‍♂️: man blond hair [People & Body]'
    '👲: person with skullcap [People & Body]'
    '👳: person wearing turban [People & Body]'
    '👳‍♀️: woman wearing turban [People & Body]'
    '👳‍♂️: man wearing turban [People & Body]'
    '👴: old man [People & Body]'
    '👵: old woman [People & Body]'
    '👶: baby [People & Body]'
    '👷: construction worker [People & Body]'
    '👷‍♀️: woman construction worker [People & Body]'
    '👷‍♂️: man construction worker [People & Body]'
    '👸: princess [People & Body]'
    '👹: ogre [Smileys & Emotion]'
    '👺: goblin [Smileys & Emotion]'
    '👻: ghost [Smileys & Emotion]'
    '👼: baby angel [People & Body]'
    '👽: alien [Smileys & Emotion]'
    '👾: alien monster [Smileys & Emotion]'
    '👿: angry face with horns [Smileys & Emotion]'
    '💀: skull [Smileys & Emotion]'
    '💁: person tipping hand [People & Body]'
    '💁‍♀️: woman tipping hand [People & Body]'
    '💁‍♂️: man tipping hand [People & Body]'
    '💂: guard [People & Body]'
    '💂‍♀️: woman guard [People & Body]'
    '💂‍♂️: man guard [People & Body]'
    '💃: woman dancing [People & Body]'
    '💄: lipstick [Objects]'
    '💅: nail polish [People & Body]'
    '💆: person getting massage [People & Body]'
    '💆‍♀️: woman getting massage [People & Body]'
    '💆‍♂️: man getting massage [People & Body]'
    '💇: person getting haircut [People & Body]'
    '💇‍♀️: woman getting haircut [People & Body]'
    '💇‍♂️: man getting haircut [People & Body]'
    '💈: barber pole [Travel & Places]'
    '💉: syringe [Objects]'
    '💊: pill [Objects]'
    '💋: kiss mark [Smileys & Emotion]'
    '💌: love letter [Smileys & Emotion]'
    '💍: ring [Objects]'
    '💎: gem stone [Objects]'
    '💏: kiss [People & Body]'
    '💐: bouquet [Animals & Nature]'
    '💑: couple with heart [People & Body]'
    '💒: wedding [Travel & Places]'
    '💓: beating heart [Smileys & Emotion]'
    '💔: broken heart [Smileys & Emotion]'
    '💕: two hearts [Smileys & Emotion]'
    '💖: sparkling heart [Smileys & Emotion]'
    '💗: growing heart [Smileys & Emotion]'
    '💘: heart with arrow [Smileys & Emotion]'
    '💙: blue heart [Smileys & Emotion]'
    '💚: green heart [Smileys & Emotion]'
    '💛: yellow heart [Smileys & Emotion]'
    '💜: purple heart [Smileys & Emotion]'
    '💝: heart with ribbon [Smileys & Emotion]'
    '💞: revolving hearts [Smileys & Emotion]'
    '💟: heart decoration [Smileys & Emotion]'
    '💠: diamond with a dot [Symbols]'
    '💡: light bulb [Objects]'
    '💢: anger symbol [Smileys & Emotion]'
    '💣: bomb [Smileys & Emotion]'
    '💤: zzz [Smileys & Emotion]'
    '💥: collision [Smileys & Emotion]'
    '💦: sweat droplets [Smileys & Emotion]'
    '💧: droplet [Travel & Places]'
    '💨: dashing away [Smileys & Emotion]'
    '💩: pile of poo [Smileys & Emotion]'
    '💪: flexed biceps [People & Body]'
    '💫: dizzy [Smileys & Emotion]'
    '💬: speech balloon [Smileys & Emotion]'
    '💭: thought balloon [Smileys & Emotion]'
    '💮: white flower [Animals & Nature]'
    '💯: hundred points [Smileys & Emotion]'
    '💰: money bag [Objects]'
    '💱: currency exchange [Symbols]'
    '💲: heavy dollar sign [Symbols]'
    '💳: credit card [Objects]'
    '💴: yen banknote [Objects]'
    '💵: dollar banknote [Objects]'
    '💶: euro banknote [Objects]'
    '💷: pound banknote [Objects]'
    '💸: money with wings [Objects]'
    '💹: chart increasing with yen [Objects]'
    '💺: seat [Travel & Places]'
    '💻: laptop [Objects]'
    '💼: briefcase [Objects]'
    '💽: computer disk [Objects]'
    '💾: floppy disk [Objects]'
    '💿: optical disk [Objects]'
    '📀: dvd [Objects]'
    '📁: file folder [Objects]'
    '📂: open file folder [Objects]'
    '📃: page with curl [Objects]'
    '📄: page facing up [Objects]'
    '📅: calendar [Objects]'
    '📆: tear-off calendar [Objects]'
    '📇: card index [Objects]'
    '📈: chart increasing [Objects]'
    '📉: chart decreasing [Objects]'
    '📊: bar chart [Objects]'
    '📋: clipboard [Objects]'
    '📌: pushpin [Objects]'
    '📍: round pushpin [Objects]'
    '📎: paperclip [Objects]'
    '📏: straight ruler [Objects]'
    '📐: triangular ruler [Objects]'
    '📑: bookmark tabs [Objects]'
    '📒: ledger [Objects]'
    '📓: notebook [Objects]'
    '📔: notebook with decorative cover [Objects]'
    '📕: closed book [Objects]'
    '📖: open book [Objects]'
    '📗: green book [Objects]'
    '📘: blue book [Objects]'
    '📙: orange book [Objects]'
    '📚: books [Objects]'
    '📛: name badge [Symbols]'
    '📜: scroll [Objects]'
    '📝: memo [Objects]'
    '📞: telephone receiver [Objects]'
    '📟: pager [Objects]'
    '📠: fax machine [Objects]'
    '📡: satellite antenna [Objects]'
    '📢: loudspeaker [Objects]'
    '📣: megaphone [Objects]'
    '📤: outbox tray [Objects]'
    '📥: inbox tray [Objects]'
    '📦: package [Objects]'
    '📧: e-mail [Objects]'
    '📨: incoming envelope [Objects]'
    '📩: envelope with arrow [Objects]'
    '📪: closed mailbox with lowered flag [Objects]'
    '📫: closed mailbox with raised flag [Objects]'
    '📬: open mailbox with raised flag [Objects]'
    '📭: open mailbox with lowered flag [Objects]'
    '📮: postbox [Objects]'
    '📯: postal horn [Objects]'
    '📰: newspaper [Objects]'
    '📱: mobile phone [Objects]'
    '📲: mobile phone with arrow [Objects]'
    '📳: vibration mode [Symbols]'
    '📴: mobile phone off [Symbols]'
    '📵: no mobile phones [Symbols]'
    '📶: antenna bars [Symbols]'
    '📷: camera [Objects]'
    '📸: camera with flash [Objects]'
    '📹: video camera [Objects]'
    '📺: television [Objects]'
    '📻: radio [Objects]'
    '📼: videocassette [Objects]'
    '📽️: film projector [Objects]'
    '📿: prayer beads [Objects]'
    '🔀: shuffle tracks button [Symbols]'
    '🔁: repeat button [Symbols]'
    '🔂: repeat single button [Symbols]'
    '🔃: clockwise vertical arrows [Symbols]'
    '🔄: counterclockwise arrows button [Symbols]'
    '🔅: dim button [Symbols]'
    '🔆: bright button [Symbols]'
    '🔇: muted speaker [Objects]'
    '🔈: speaker low volume [Objects]'
    '🔉: speaker medium volume [Objects]'
    '🔊: speaker high volume [Objects]'
    '🔋: battery [Objects]'
    '🔌: electric plug [Objects]'
    '🔍: magnifying glass tilted left [Objects]'
    '🔎: magnifying glass tilted right [Objects]'
    '🔏: locked with pen [Objects]'
    '🔐: locked with key [Objects]'
    '🔑: key [Objects]'
    '🔒: locked [Objects]'
    '🔓: unlocked [Objects]'
    '🔔: bell [Objects]'
    '🔕: bell with slash [Objects]'
    '🔖: bookmark [Objects]'
    '🔗: link [Objects]'
    '🔘: radio button [Symbols]'
    '🔙: BACK arrow [Symbols]'
    '🔚: END arrow [Symbols]'
    '🔛: ON! arrow [Symbols]'
    '🔜: SOON arrow [Symbols]'
    '🔝: TOP arrow [Symbols]'
    '🔞: no one under eighteen [Symbols]'
    '🔟: keycap 10 [Symbols]'
    '🔠: input latin uppercase [Symbols]'
    '🔡: input latin lowercase [Symbols]'
    '🔢: input numbers [Symbols]'
    '🔣: input symbols [Symbols]'
    '🔤: input latin letters [Symbols]'
    '🔥: fire [Travel & Places]'
    '🔦: flashlight [Objects]'
    '🔧: wrench [Objects]'
    '🔨: hammer [Objects]'
    '🔩: nut and bolt [Objects]'
    '🔪: kitchen knife [Food & Drink]'
    '🔫: water pistol [Objects]'
    '🔬: microscope [Objects]'
    '🔭: telescope [Objects]'
    '🔮: crystal ball [Activities]'
    '🔯: dotted six-pointed star [Symbols]'
    '🔰: Japanese symbol for beginner [Symbols]'
    '🔱: trident emblem [Symbols]'
    '🔲: black square button [Symbols]'
    '🔳: white square button [Symbols]'
    '🔴: red circle [Symbols]'
    '🔵: blue circle [Symbols]'
    '🔶: large orange diamond [Symbols]'
    '🔷: large blue diamond [Symbols]'
    '🔸: small orange diamond [Symbols]'
    '🔹: small blue diamond [Symbols]'
    '🔺: red triangle pointed up [Symbols]'
    '🔻: red triangle pointed down [Symbols]'
    '🔼: upwards button [Symbols]'
    '🔽: downwards button [Symbols]'
    '🕉️: om [Symbols]'
    '🕊️: dove [Animals & Nature]'
    '🕋: kaaba [Travel & Places]'
    '🕌: mosque [Travel & Places]'
    '🕍: synagogue [Travel & Places]'
    '🕎: menorah [Symbols]'
    '🕐: one o’clock [Travel & Places]'
    '🕑: two o’clock [Travel & Places]'
    '🕒: three o’clock [Travel & Places]'
    '🕓: four o’clock [Travel & Places]'
    '🕔: five o’clock [Travel & Places]'
    '🕕: six o’clock [Travel & Places]'
    '🕖: seven o’clock [Travel & Places]'
    '🕗: eight o’clock [Travel & Places]'
    '🕘: nine o’clock [Travel & Places]'
    '🕙: ten o’clock [Travel & Places]'
    '🕚: eleven o’clock [Travel & Places]'
    '🕛: twelve o’clock [Travel & Places]'
    '🕜: one-thirty [Travel & Places]'
    '🕝: two-thirty [Travel & Places]'
    '🕞: three-thirty [Travel & Places]'
    '🕟: four-thirty [Travel & Places]'
    '🕠: five-thirty [Travel & Places]'
    '🕡: six-thirty [Travel & Places]'
    '🕢: seven-thirty [Travel & Places]'
    '🕣: eight-thirty [Travel & Places]'
    '🕤: nine-thirty [Travel & Places]'
    '🕥: ten-thirty [Travel & Places]'
    '🕦: eleven-thirty [Travel & Places]'
    '🕧: twelve-thirty [Travel & Places]'
    '🕯️: candle [Objects]'
    '🕰️: mantelpiece clock [Travel & Places]'
    '🕳️: hole [Smileys & Emotion]'
    '🕴️: person in suit levitating [People & Body]'
    '🕵️: detective [People & Body]'
    '🕵️‍♀️: woman detective [People & Body]'
    '🕵️‍♂️: man detective [People & Body]'
    '🕶️: sunglasses [Objects]'
    '🕷️: spider [Animals & Nature]'
    '🕸️: spider web [Animals & Nature]'
    '🕹️: joystick [Activities]'
    '🕺: man dancing [People & Body]'
    '🖇️: linked paperclips [Objects]'
    '🖊️: pen [Objects]'
    '🖋️: fountain pen [Objects]'
    '🖌️: paintbrush [Objects]'
    '🖍️: crayon [Objects]'
    '🖐️: hand with fingers splayed [People & Body]'
    '🖕: middle finger [People & Body]'
    '🖖: vulcan salute [People & Body]'
    '🖤: black heart [Smileys & Emotion]'
    '🖥️: desktop computer [Objects]'
    '🖨️: printer [Objects]'
    '🖱️: computer mouse [Objects]'
    '🖲️: trackball [Objects]'
    '🖼️: framed picture [Activities]'
    '🗂️: card index dividers [Objects]'
    '🗃️: card file box [Objects]'
    '🗄️: file cabinet [Objects]'
    '🗑️: wastebasket [Objects]'
    '🗒️: spiral notepad [Objects]'
    '🗓️: spiral calendar [Objects]'
    '🗜️: clamp [Objects]'
    '🗝️: old key [Objects]'
    '🗞️: rolled-up newspaper [Objects]'
    '🗡️: dagger [Objects]'
    '🗣️: speaking head [People & Body]'
    '🗨️: left speech bubble [Smileys & Emotion]'
    '🗯️: right anger bubble [Smileys & Emotion]'
    '🗳️: ballot box with ballot [Objects]'
    '🗺️: world map [Travel & Places]'
    '🗻: mount fuji [Travel & Places]'
    '🗼: Tokyo tower [Travel & Places]'
    '🗽: Statue of Liberty [Travel & Places]'
    '🗾: map of Japan [Travel & Places]'
    '🗿: moai [Objects]'
    '😀: grinning face [Smileys & Emotion]'
    '😁: beaming face with smiling eyes [Smileys & Emotion]'
    '😂: face with tears of joy [Smileys & Emotion]'
    '😃: grinning face with big eyes [Smileys & Emotion]'
    '😄: grinning face with smiling eyes [Smileys & Emotion]'
    '😅: grinning face with sweat [Smileys & Emotion]'
    '😆: grinning squinting face [Smileys & Emotion]'
    '😇: smiling face with halo [Smileys & Emotion]'
    '😈: smiling face with horns [Smileys & Emotion]'
    '😉: winking face [Smileys & Emotion]'
    '😊: smiling face with smiling eyes [Smileys & Emotion]'
    '😋: face savoring food [Smileys & Emotion]'
    '😌: relieved face [Smileys & Emotion]'
    '😍: smiling face with heart-eyes [Smileys & Emotion]'
    '😎: smiling face with sunglasses [Smileys & Emotion]'
    '😏: smirking face [Smileys & Emotion]'
    '😐: neutral face [Smileys & Emotion]'
    '😑: expressionless face [Smileys & Emotion]'
    '😒: unamused face [Smileys & Emotion]'
    '😓: downcast face with sweat [Smileys & Emotion]'
    '😔: pensive face [Smileys & Emotion]'
    '😕: confused face [Smileys & Emotion]'
    '😖: confounded face [Smileys & Emotion]'
    '😗: kissing face [Smileys & Emotion]'
    '😘: face blowing a kiss [Smileys & Emotion]'
    '😙: kissing face with smiling eyes [Smileys & Emotion]'
    '😚: kissing face with closed eyes [Smileys & Emotion]'
    '😛: face with tongue [Smileys & Emotion]'
    '😜: winking face with tongue [Smileys & Emotion]'
    '😝: squinting face with tongue [Smileys & Emotion]'
    '😞: disappointed face [Smileys & Emotion]'
    '😟: worried face [Smileys & Emotion]'
    '😠: angry face [Smileys & Emotion]'
    '😡: pouting face [Smileys & Emotion]'
    '😢: crying face [Smileys & Emotion]'
    '😣: persevering face [Smileys & Emotion]'
    '😤: face with steam from nose [Smileys & Emotion]'
    '😥: sad but relieved face [Smileys & Emotion]'
    '😦: frowning face with open mouth [Smileys & Emotion]'
    '😧: anguished face [Smileys & Emotion]'
    '😨: fearful face [Smileys & Emotion]'
    '😩: weary face [Smileys & Emotion]'
    '😪: sleepy face [Smileys & Emotion]'
    '😫: tired face [Smileys & Emotion]'
    '😬: grimacing face [Smileys & Emotion]'
    '😭: loudly crying face [Smileys & Emotion]'
    '😮: face with open mouth [Smileys & Emotion]'
    '😮‍💨: face exhaling [Smileys & Emotion]'
    '😯: hushed face [Smileys & Emotion]'
    '😰: anxious face with sweat [Smileys & Emotion]'
    '😱: face screaming in fear [Smileys & Emotion]'
    '😲: astonished face [Smileys & Emotion]'
    '😳: flushed face [Smileys & Emotion]'
    '😴: sleeping face [Smileys & Emotion]'
    '😵: face with crossed-out eyes [Smileys & Emotion]'
    '😵‍💫: face with spiral eyes [Smileys & Emotion]'
    '😶: face without mouth [Smileys & Emotion]'
    '😶‍🌫️: face in clouds [Smileys & Emotion]'
    '😷: face with medical mask [Smileys & Emotion]'
    '😸: grinning cat with smiling eyes [Smileys & Emotion]'
    '😹: cat with tears of joy [Smileys & Emotion]'
    '😺: grinning cat [Smileys & Emotion]'
    '😻: smiling cat with heart-eyes [Smileys & Emotion]'
    '😼: cat with wry smile [Smileys & Emotion]'
    '😽: kissing cat [Smileys & Emotion]'
    '😾: pouting cat [Smileys & Emotion]'
    '😿: crying cat [Smileys & Emotion]'
    '🙀: weary cat [Smileys & Emotion]'
    '🙁: slightly frowning face [Smileys & Emotion]'
    '🙂: slightly smiling face [Smileys & Emotion]'
    '🙃: upside-down face [Smileys & Emotion]'
    '🙄: face with rolling eyes [Smileys & Emotion]'
    '🙅: person gesturing NO [People & Body]'
    '🙅‍♀️: woman gesturing NO [People & Body]'
    '🙅‍♂️: man gesturing NO [People & Body]'
    '🙆: person gesturing OK [People & Body]'
    '🙆‍♀️: woman gesturing OK [People & Body]'
    '🙆‍♂️: man gesturing OK [People & Body]'
    '🙇: person bowing [People & Body]'
    '🙇‍♀️: woman bowing [People & Body]'
    '🙇‍♂️: man bowing [People & Body]'
    '🙈: see-no-evil monkey [Smileys & Emotion]'
    '🙉: hear-no-evil monkey [Smileys & Emotion]'
    '🙊: speak-no-evil monkey [Smileys & Emotion]'
    '🙋: person raising hand [People & Body]'
    '🙋‍♀️: woman raising hand [People & Body]'
    '🙋‍♂️: man raising hand [People & Body]'
    '🙌: raising hands [People & Body]'
    '🙍: person frowning [People & Body]'
    '🙍‍♀️: woman frowning [People & Body]'
    '🙍‍♂️: man frowning [People & Body]'
    '🙎: person pouting [People & Body]'
    '🙎‍♀️: woman pouting [People & Body]'
    '🙎‍♂️: man pouting [People & Body]'
    '🙏: folded hands [People & Body]'
    '🚀: rocket [Travel & Places]'
    '🚁: helicopter [Travel & Places]'
    '🚂: locomotive [Travel & Places]'
    '🚃: railway car [Travel & Places]'
    '🚄: high-speed train [Travel & Places]'
    '🚅: bullet train [Travel & Places]'
    '🚆: train [Travel & Places]'
    '🚇: metro [Travel & Places]'
    '🚈: light rail [Travel & Places]'
    '🚉: station [Travel & Places]'
    '🚊: tram [Travel & Places]'
    '🚋: tram car [Travel & Places]'
    '🚌: bus [Travel & Places]'
    '🚍: oncoming bus [Travel & Places]'
    '🚎: trolleybus [Travel & Places]'
    '🚏: bus stop [Travel & Places]'
    '🚐: minibus [Travel & Places]'
    '🚑: ambulance [Travel & Places]'
    '🚒: fire engine [Travel & Places]'
    '🚓: police car [Travel & Places]'
    '🚔: oncoming police car [Travel & Places]'
    '🚕: taxi [Travel & Places]'
    '🚖: oncoming taxi [Travel & Places]'
    '🚗: automobile [Travel & Places]'
    '🚘: oncoming automobile [Travel & Places]'
    '🚙: sport utility vehicle [Travel & Places]'
    '🚚: delivery truck [Travel & Places]'
    '🚛: articulated lorry [Travel & Places]'
    '🚜: tractor [Travel & Places]'
    '🚝: monorail [Travel & Places]'
    '🚞: mountain railway [Travel & Places]'
    '🚟: suspension railway [Travel & Places]'
    '🚠: mountain cableway [Travel & Places]'
    '🚡: aerial tramway [Travel & Places]'
    '🚢: ship [Travel & Places]'
    '🚣: person rowing boat [People & Body]'
    '🚣‍♀️: woman rowing boat [People & Body]'
    '🚣‍♂️: man rowing boat [People & Body]'
    '🚤: speedboat [Travel & Places]'
    '🚥: horizontal traffic light [Travel & Places]'
    '🚦: vertical traffic light [Travel & Places]'
    '🚧: construction [Travel & Places]'
    '🚨: police car light [Travel & Places]'
    '🚩: triangular flag [Flags]'
    '🚪: door [Objects]'
    '🚫: prohibited [Symbols]'
    '🚬: cigarette [Objects]'
    '🚭: no smoking [Symbols]'
    '🚮: litter in bin sign [Symbols]'
    '🚯: no littering [Symbols]'
    '🚰: potable water [Symbols]'
    '🚱: non-potable water [Symbols]'
    '🚲: bicycle [Travel & Places]'
    '🚳: no bicycles [Symbols]'
    '🚴: person biking [People & Body]'
    '🚴‍♀️: woman biking [People & Body]'
    '🚴‍♂️: man biking [People & Body]'
    '🚵: person mountain biking [People & Body]'
    '🚵‍♀️: woman mountain biking [People & Body]'
    '🚵‍♂️: man mountain biking [People & Body]'
    '🚶: person walking [People & Body]'
    '🚶‍♀️: woman walking [People & Body]'
    '🚶‍♂️: man walking [People & Body]'
    '🚷: no pedestrians [Symbols]'
    '🚸: children crossing [Symbols]'
    '🚹: men’s room [Symbols]'
    '🚺: women’s room [Symbols]'
    '🚻: restroom [Symbols]'
    '🚼: baby symbol [Symbols]'
    '🚽: toilet [Objects]'
    '🚾: water closet [Symbols]'
    '🚿: shower [Objects]'
    '🛀: person taking bath [People & Body]'
    '🛁: bathtub [Objects]'
    '🛂: passport control [Symbols]'
    '🛃: customs [Symbols]'
    '🛄: baggage claim [Symbols]'
    '🛅: left luggage [Symbols]'
    '🛋️: couch and lamp [Objects]'
    '🛌: person in bed [People & Body]'
    '🛍️: shopping bags [Objects]'
    '🛎️: bellhop bell [Travel & Places]'
    '🛏️: bed [Objects]'
    '🛐: place of worship [Symbols]'
    '🛑: stop sign [Travel & Places]'
    '🛒: shopping cart [Objects]'
    '🛕: hindu temple [Travel & Places]'
    '🛖: hut [Travel & Places]'
    '🛗: elevator [Objects]'
    '🛝: playground slide [Travel & Places]'
    '🛞: wheel [Travel & Places]'
    '🛟: ring buoy [Travel & Places]'
    '🛠️: hammer and wrench [Objects]'
    '🛡️: shield [Objects]'
    '🛢️: oil drum [Travel & Places]'
    '🛣️: motorway [Travel & Places]'
    '🛤️: railway track [Travel & Places]'
    '🛥️: motor boat [Travel & Places]'
    '🛩️: small airplane [Travel & Places]'
    '🛫: airplane departure [Travel & Places]'
    '🛬: airplane arrival [Travel & Places]'
    '🛰️: satellite [Travel & Places]'
    '🛳️: passenger ship [Travel & Places]'
    '🛴: kick scooter [Travel & Places]'
    '🛵: motor scooter [Travel & Places]'
    '🛶: canoe [Travel & Places]'
    '🛷: sled [Activities]'
    '🛸: flying saucer [Travel & Places]'
    '🛹: skateboard [Travel & Places]'
    '🛺: auto rickshaw [Travel & Places]'
    '🛻: pickup truck [Travel & Places]'
    '🛼: roller skate [Travel & Places]'
    '🟠: orange circle [Symbols]'
    '🟡: yellow circle [Symbols]'
    '🟢: green circle [Symbols]'
    '🟣: purple circle [Symbols]'
    '🟤: brown circle [Symbols]'
    '🟥: red square [Symbols]'
    '🟦: blue square [Symbols]'
    '🟧: orange square [Symbols]'
    '🟨: yellow square [Symbols]'
    '🟩: green square [Symbols]'
    '🟪: purple square [Symbols]'
    '🟫: brown square [Symbols]'
    '🟰: heavy equals sign [Symbols]'
    '🤌: pinched fingers [People & Body]'
    '🤍: white heart [Smileys & Emotion]'
    '🤎: brown heart [Smileys & Emotion]'
    '🤏: pinching hand [People & Body]'
    '🤐: zipper-mouth face [Smileys & Emotion]'
    '🤑: money-mouth face [Smileys & Emotion]'
    '🤒: face with thermometer [Smileys & Emotion]'
    '🤓: nerd face [Smileys & Emotion]'
    '🤔: thinking face [Smileys & Emotion]'
    '🤕: face with head-bandage [Smileys & Emotion]'
    '🤖: robot [Smileys & Emotion]'
    '🤗: smiling face with open hands [Smileys & Emotion]'
    '🤘: sign of the horns [People & Body]'
    '🤙: call me hand [People & Body]'
    '🤚: raised back of hand [People & Body]'
    '🤛: left-facing fist [People & Body]'
    '🤜: right-facing fist [People & Body]'
    '🤝: handshake [People & Body]'
    '🤞: crossed fingers [People & Body]'
    '🤟: love-you gesture [People & Body]'
    '🤠: cowboy hat face [Smileys & Emotion]'
    '🤡: clown face [Smileys & Emotion]'
    '🤢: nauseated face [Smileys & Emotion]'
    '🤣: rolling on the floor laughing [Smileys & Emotion]'
    '🤤: drooling face [Smileys & Emotion]'
    '🤥: lying face [Smileys & Emotion]'
    '🤦: person facepalming [People & Body]'
    '🤦‍♀️: woman facepalming [People & Body]'
    '🤦‍♂️: man facepalming [People & Body]'
    '🤧: sneezing face [Smileys & Emotion]'
    '🤨: face with raised eyebrow [Smileys & Emotion]'
    '🤩: star-struck [Smileys & Emotion]'
    '🤪: zany face [Smileys & Emotion]'
    '🤫: shushing face [Smileys & Emotion]'
    '🤬: face with symbols on mouth [Smileys & Emotion]'
    '🤭: face with hand over mouth [Smileys & Emotion]'
    '🤮: face vomiting [Smileys & Emotion]'
    '🤯: exploding head [Smileys & Emotion]'
    '🤰: pregnant woman [People & Body]'
    '🤱: breast-feeding [People & Body]'
    '🤲: palms up together [People & Body]'
    '🤳: selfie [People & Body]'
    '🤴: prince [People & Body]'
    '🤵: person in tuxedo [People & Body]'
    '🤵‍♀️: woman in tuxedo [People & Body]'
    '🤵‍♂️: man in tuxedo [People & Body]'
    '🤶: Mrs. Claus [People & Body]'
    '🤷: person shrugging [People & Body]'
    '🤷‍♀️: woman shrugging [People & Body]'
    '🤷‍♂️: man shrugging [People & Body]'
    '🤸: person cartwheeling [People & Body]'
    '🤸‍♀️: woman cartwheeling [People & Body]'
    '🤸‍♂️: man cartwheeling [People & Body]'
    '🤹: person juggling [People & Body]'
    '🤹‍♀️: woman juggling [People & Body]'
    '🤹‍♂️: man juggling [People & Body]'
    '🤺: person fencing [People & Body]'
    '🤼: people wrestling [People & Body]'
    '🤼‍♀️: women wrestling [People & Body]'
    '🤼‍♂️: men wrestling [People & Body]'
    '🤽: person playing water polo [People & Body]'
    '🤽‍♀️: woman playing water polo [People & Body]'
    '🤽‍♂️: man playing water polo [People & Body]'
    '🤾: person playing handball [People & Body]'
    '🤾‍♀️: woman playing handball [People & Body]'
    '🤾‍♂️: man playing handball [People & Body]'
    '🤿: diving mask [Activities]'
    '🥀: wilted flower [Animals & Nature]'
    '🥁: drum [Objects]'
    '🥂: clinking glasses [Food & Drink]'
    '🥃: tumbler glass [Food & Drink]'
    '🥄: spoon [Food & Drink]'
    '🥅: goal net [Activities]'
    '🥇: 1st place medal [Activities]'
    '🥈: 2nd place medal [Activities]'
    '🥉: 3rd place medal [Activities]'
    '🥊: boxing glove [Activities]'
    '🥋: martial arts uniform [Activities]'
    '🥌: curling stone [Activities]'
    '🥍: lacrosse [Activities]'
    '🥎: softball [Activities]'
    '🥏: flying disc [Activities]'
    '🥐: croissant [Food & Drink]'
    '🥑: avocado [Food & Drink]'
    '🥒: cucumber [Food & Drink]'
    '🥓: bacon [Food & Drink]'
    '🥔: potato [Food & Drink]'
    '🥕: carrot [Food & Drink]'
    '🥖: baguette bread [Food & Drink]'
    '🥗: green salad [Food & Drink]'
    '🥘: shallow pan of food [Food & Drink]'
    '🥙: stuffed flatbread [Food & Drink]'
    '🥚: egg [Food & Drink]'
    '🥛: glass of milk [Food & Drink]'
    '🥜: peanuts [Food & Drink]'
    '🥝: kiwi fruit [Food & Drink]'
    '🥞: pancakes [Food & Drink]'
    '🥟: dumpling [Food & Drink]'
    '🥠: fortune cookie [Food & Drink]'
    '🥡: takeout box [Food & Drink]'
    '🥢: chopsticks [Food & Drink]'
    '🥣: bowl with spoon [Food & Drink]'
    '🥤: cup with straw [Food & Drink]'
    '🥥: coconut [Food & Drink]'
    '🥦: broccoli [Food & Drink]'
    '🥧: pie [Food & Drink]'
    '🥨: pretzel [Food & Drink]'
    '🥩: cut of meat [Food & Drink]'
    '🥪: sandwich [Food & Drink]'
    '🥫: canned food [Food & Drink]'
    '🥬: leafy green [Food & Drink]'
    '🥭: mango [Food & Drink]'
    '🥮: moon cake [Food & Drink]'
    '🥯: bagel [Food & Drink]'
    '🥰: smiling face with hearts [Smileys & Emotion]'
    '🥱: yawning face [Smileys & Emotion]'
    '🥲: smiling face with tear [Smileys & Emotion]'
    '🥳: partying face [Smileys & Emotion]'
    '🥴: woozy face [Smileys & Emotion]'
    '🥵: hot face [Smileys & Emotion]'
    '🥶: cold face [Smileys & Emotion]'
    '🥷: ninja [People & Body]'
    '🥸: disguised face [Smileys & Emotion]'
    '🥹: face holding back tears [Smileys & Emotion]'
    '🥺: pleading face [Smileys & Emotion]'
    '🥻: sari [Objects]'
    '🥼: lab coat [Objects]'
    '🥽: goggles [Objects]'
    '🥾: hiking boot [Objects]'
    '🥿: flat shoe [Objects]'
    '🦀: crab [Food & Drink]'
    '🦁: lion [Animals & Nature]'
    '🦂: scorpion [Animals & Nature]'
    '🦃: turkey [Animals & Nature]'
    '🦄: unicorn [Animals & Nature]'
    '🦅: eagle [Animals & Nature]'
    '🦆: duck [Animals & Nature]'
    '🦇: bat [Animals & Nature]'
    '🦈: shark [Animals & Nature]'
    '🦉: owl [Animals & Nature]'
    '🦊: fox [Animals & Nature]'
    '🦋: butterfly [Animals & Nature]'
    '🦌: deer [Animals & Nature]'
    '🦍: gorilla [Animals & Nature]'
    '🦎: lizard [Animals & Nature]'
    '🦏: rhinoceros [Animals & Nature]'
    '🦐: shrimp [Food & Drink]'
    '🦑: squid [Food & Drink]'
    '🦒: giraffe [Animals & Nature]'
    '🦓: zebra [Animals & Nature]'
    '🦔: hedgehog [Animals & Nature]'
    '🦕: sauropod [Animals & Nature]'
    '🦖: T-Rex [Animals & Nature]'
    '🦗: cricket [Animals & Nature]'
    '🦘: kangaroo [Animals & Nature]'
    '🦙: llama [Animals & Nature]'
    '🦚: peacock [Animals & Nature]'
    '🦛: hippopotamus [Animals & Nature]'
    '🦜: parrot [Animals & Nature]'
    '🦝: raccoon [Animals & Nature]'
    '🦞: lobster [Food & Drink]'
    '🦟: mosquito [Animals & Nature]'
    '🦠: microbe [Animals & Nature]'
    '🦡: badger [Animals & Nature]'
    '🦢: swan [Animals & Nature]'
    '🦣: mammoth [Animals & Nature]'
    '🦤: dodo [Animals & Nature]'
    '🦥: sloth [Animals & Nature]'
    '🦦: otter [Animals & Nature]'
    '🦧: orangutan [Animals & Nature]'
    '🦨: skunk [Animals & Nature]'
    '🦩: flamingo [Animals & Nature]'
    '🦪: oyster [Food & Drink]'
    '🦫: beaver [Animals & Nature]'
    '🦬: bison [Animals & Nature]'
    '🦭: seal [Animals & Nature]'
    '🦮: guide dog [Animals & Nature]'
    '🦯: white cane [Objects]'
    '🦴: bone [People & Body]'
    '🦵: leg [People & Body]'
    '🦶: foot [People & Body]'
    '🦷: tooth [People & Body]'
    '🦸: superhero [People & Body]'
    '🦸‍♀️: woman superhero [People & Body]'
    '🦸‍♂️: man superhero [People & Body]'
    '🦹: supervillain [People & Body]'
    '🦹‍♀️: woman supervillain [People & Body]'
    '🦹‍♂️: man supervillain [People & Body]'
    '🦺: safety vest [Objects]'
    '🦻: ear with hearing aid [People & Body]'
    '🦼: motorized wheelchair [Travel & Places]'
    '🦽: manual wheelchair [Travel & Places]'
    '🦾: mechanical arm [People & Body]'
    '🦿: mechanical leg [People & Body]'
    '🧀: cheese wedge [Food & Drink]'
    '🧁: cupcake [Food & Drink]'
    '🧂: salt [Food & Drink]'
    '🧃: beverage box [Food & Drink]'
    '🧄: garlic [Food & Drink]'
    '🧅: onion [Food & Drink]'
    '🧆: falafel [Food & Drink]'
    '🧇: waffle [Food & Drink]'
    '🧈: butter [Food & Drink]'
    '🧉: mate [Food & Drink]'
    '🧊: ice [Food & Drink]'
    '🧋: bubble tea [Food & Drink]'
    '🧌: troll [People & Body]'
    '🧍: person standing [People & Body]'
    '🧍‍♀️: woman standing [People & Body]'
    '🧍‍♂️: man standing [People & Body]'
    '🧎: person kneeling [People & Body]'
    '🧎‍♀️: woman kneeling [People & Body]'
    '🧎‍♂️: man kneeling [People & Body]'
    '🧏: deaf person [People & Body]'
    '🧏‍♀️: deaf woman [People & Body]'
    '🧏‍♂️: deaf man [People & Body]'
    '🧐: face with monocle [Smileys & Emotion]'
    '🧑: person [People & Body]'
    '🧑‍⚕️: health worker [People & Body]'
    '🧑‍⚖️: judge [People & Body]'
    '🧑‍✈️: pilot [People & Body]'
    '🧑‍🌾: farmer [People & Body]'
    '🧑‍🍳: cook [People & Body]'
    '🧑‍🍼: person feeding baby [People & Body]'
    '🧑‍🎄: mx claus [People & Body]'
    '🧑‍🎓: student [People & Body]'
    '🧑‍🎤: singer [People & Body]'
    '🧑‍🎨: artist [People & Body]'
    '🧑‍🏫: teacher [People & Body]'
    '🧑‍🏭: factory worker [People & Body]'
    '🧑‍💻: technologist [People & Body]'
    '🧑‍💼: office worker [People & Body]'
    '🧑‍🔧: mechanic [People & Body]'
    '🧑‍🔬: scientist [People & Body]'
    '🧑‍🚀: astronaut [People & Body]'
    '🧑‍🚒: firefighter [People & Body]'
    '🧑‍🤝‍🧑: people holding hands [People & Body]'
    '🧑‍🦯: person with white cane [People & Body]'
    '🧑‍🦰: person red hair [People & Body]'
    '🧑‍🦱: person curly hair [People & Body]'
    '🧑‍🦲: person bald [People & Body]'
    '🧑‍🦳: person white hair [People & Body]'
    '🧑‍🦼: person in motorized wheelchair [People & Body]'
    '🧑‍🦽: person in manual wheelchair [People & Body]'
    '🧒: child [People & Body]'
    '🧓: older person [People & Body]'
    '🧔: person beard [People & Body]'
    '🧔‍♀️: woman beard [People & Body]'
    '🧔‍♂️: man beard [People & Body]'
    '🧕: woman with headscarf [People & Body]'
    '🧖: person in steamy room [People & Body]'
    '🧖‍♀️: woman in steamy room [People & Body]'
    '🧖‍♂️: man in steamy room [People & Body]'
    '🧗: person climbing [People & Body]'
    '🧗‍♀️: woman climbing [People & Body]'
    '🧗‍♂️: man climbing [People & Body]'
    '🧘: person in lotus position [People & Body]'
    '🧘‍♀️: woman in lotus position [People & Body]'
    '🧘‍♂️: man in lotus position [People & Body]'
    '🧙: mage [People & Body]'
    '🧙‍♀️: woman mage [People & Body]'
    '🧙‍♂️: man mage [People & Body]'
    '🧚: fairy [People & Body]'
    '🧚‍♀️: woman fairy [People & Body]'
    '🧚‍♂️: man fairy [People & Body]'
    '🧛: vampire [People & Body]'
    '🧛‍♀️: woman vampire [People & Body]'
    '🧛‍♂️: man vampire [People & Body]'
    '🧜: merperson [People & Body]'
    '🧜‍♀️: mermaid [People & Body]'
    '🧜‍♂️: merman [People & Body]'
    '🧝: elf [People & Body]'
    '🧝‍♀️: woman elf [People & Body]'
    '🧝‍♂️: man elf [People & Body]'
    '🧞: genie [People & Body]'
    '🧞‍♀️: woman genie [People & Body]'
    '🧞‍♂️: man genie [People & Body]'
    '🧟: zombie [People & Body]'
    '🧟‍♀️: woman zombie [People & Body]'
    '🧟‍♂️: man zombie [People & Body]'
    '🧠: brain [People & Body]'
    '🧡: orange heart [Smileys & Emotion]'
    '🧢: billed cap [Objects]'
    '🧣: scarf [Objects]'
    '🧤: gloves [Objects]'
    '🧥: coat [Objects]'
    '🧦: socks [Objects]'
    '🧧: red envelope [Activities]'
    '🧨: firecracker [Activities]'
    '🧩: puzzle piece [Activities]'
    '🧪: test tube [Objects]'
    '🧫: petri dish [Objects]'
    '🧬: dna [Objects]'
    '🧭: compass [Travel & Places]'
    '🧮: abacus [Objects]'
    '🧯: fire extinguisher [Objects]'
    '🧰: toolbox [Objects]'
    '🧱: brick [Travel & Places]'
    '🧲: magnet [Objects]'
    '🧳: luggage [Travel & Places]'
    '🧴: lotion bottle [Objects]'
    '🧵: thread [Activities]'
    '🧶: yarn [Activities]'
    '🧷: safety pin [Objects]'
    '🧸: teddy bear [Activities]'
    '🧹: broom [Objects]'
    '🧺: basket [Objects]'
    '🧻: roll of paper [Objects]'
    '🧼: soap [Objects]'
    '🧽: sponge [Objects]'
    '🧾: receipt [Objects]'
    '🧿: nazar amulet [Activities]'
    '🩰: ballet shoes [Objects]'
    '🩱: one-piece swimsuit [Objects]'
    '🩲: briefs [Objects]'
    '🩳: shorts [Objects]'
    '🩴: thong sandal [Objects]'
    '🩸: drop of blood [Objects]'
    '🩹: adhesive bandage [Objects]'
    '🩺: stethoscope [Objects]'
    '🩻: x-ray [Objects]'
    '🩼: crutch [Objects]'
    '🪀: yo-yo [Activities]'
    '🪁: kite [Activities]'
    '🪂: parachute [Travel & Places]'
    '🪃: boomerang [Objects]'
    '🪄: magic wand [Activities]'
    '🪅: piñata [Activities]'
    '🪆: nesting dolls [Activities]'
    '🪐: ringed planet [Travel & Places]'
    '🪑: chair [Objects]'
    '🪒: razor [Objects]'
    '🪓: axe [Objects]'
    '🪔: diya lamp [Objects]'
    '🪕: banjo [Objects]'
    '🪖: military helmet [Objects]'
    '🪗: accordion [Objects]'
    '🪘: long drum [Objects]'
    '🪙: coin [Objects]'
    '🪚: carpentry saw [Objects]'
    '🪛: screwdriver [Objects]'
    '🪜: ladder [Objects]'
    '🪝: hook [Objects]'
    '🪞: mirror [Objects]'
    '🪟: window [Objects]'
    '🪠: plunger [Objects]'
    '🪡: sewing needle [Activities]'
    '🪢: knot [Activities]'
    '🪣: bucket [Objects]'
    '🪤: mouse trap [Objects]'
    '🪥: toothbrush [Objects]'
    '🪦: headstone [Objects]'
    '🪧: placard [Objects]'
    '🪨: rock [Travel & Places]'
    '🪩: mirror ball [Activities]'
    '🪪: identification card [Objects]'
    '🪫: low battery [Objects]'
    '🪬: hamsa [Activities]'
    '🪰: fly [Animals & Nature]'
    '🪱: worm [Animals & Nature]'
    '🪲: beetle [Animals & Nature]'
    '🪳: cockroach [Animals & Nature]'
    '🪴: potted plant [Animals & Nature]'
    '🪵: wood [Travel & Places]'
    '🪶: feather [Animals & Nature]'
    '🪷: lotus [Animals & Nature]'
    '🪸: coral [Animals & Nature]'
    '🪹: empty nest [Animals & Nature]'
    '🪺: nest with eggs [Animals & Nature]'
    '🫀: anatomical heart [People & Body]'
    '🫁: lungs [People & Body]'
    '🫂: people hugging [People & Body]'
    '🫃: pregnant man [People & Body]'
    '🫄: pregnant person [People & Body]'
    '🫅: person with crown [People & Body]'
    '🫐: blueberries [Food & Drink]'
    '🫑: bell pepper [Food & Drink]'
    '🫒: olive [Food & Drink]'
    '🫓: flatbread [Food & Drink]'
    '🫔: tamale [Food & Drink]'
    '🫕: fondue [Food & Drink]'
    '🫖: teapot [Food & Drink]'
    '🫗: pouring liquid [Food & Drink]'
    '🫘: beans [Food & Drink]'
    '🫙: jar [Food & Drink]'
    '🫠: melting face [Smileys & Emotion]'
    '🫡: saluting face [Smileys & Emotion]'
    '🫢: face with open eyes and hand over mouth [Smileys & Emotion]'
    '🫣: face with peeking eye [Smileys & Emotion]'
    '🫤: face with diagonal mouth [Smileys & Emotion]'
    '🫥: dotted line face [Smileys & Emotion]'
    '🫦: biting lip [People & Body]'
    '🫧: bubbles [Objects]'
    '🫰: hand with index finger and thumb crossed [People & Body]'
    '🫱: rightwards hand [People & Body]'
    '🫲: leftwards hand [People & Body]'
    '🫳: palm down hand [People & Body]'
    '🫴: palm up hand [People & Body]'
    '🫵: index pointing at the viewer [People & Body]'
    '🫶: heart hands [People & Body]'
)
