emojis=(
    '#️⃣: keycap # (Symbols) [Emoji]'
    '*️⃣: keycap * (Symbols) [Emoji]'
    '0️⃣: keycap 0 (Symbols) [Emoji]'
    '1️⃣: keycap 1 (Symbols) [Emoji]'
    '2️⃣: keycap 2 (Symbols) [Emoji]'
    '3️⃣: keycap 3 (Symbols) [Emoji]'
    '4️⃣: keycap 4 (Symbols) [Emoji]'
    '5️⃣: keycap 5 (Symbols) [Emoji]'
    '6️⃣: keycap 6 (Symbols) [Emoji]'
    '7️⃣: keycap 7 (Symbols) [Emoji]'
    '8️⃣: keycap 8 (Symbols) [Emoji]'
    '9️⃣: keycap 9 (Symbols) [Emoji]'
    '©️: copyright (Symbols) [Emoji]'
    '®️: registered (Symbols) [Emoji]'
    '‼️: double exclamation mark (Symbols) [Emoji]'
    '⁉️: exclamation question mark (Symbols) [Emoji]'
    '™️: trade mark (Symbols) [Emoji]'
    'ℹ️: information (Symbols) [Emoji]'
    '↔️: left-right arrow (Symbols) [Emoji]'
    '↕️: up-down arrow (Symbols) [Emoji]'
    '↖️: up-left arrow (Symbols) [Emoji]'
    '↗️: up-right arrow (Symbols) [Emoji]'
    '↘️: down-right arrow (Symbols) [Emoji]'
    '↙️: down-left arrow (Symbols) [Emoji]'
    '↩️: right arrow curving left (Symbols) [Emoji]'
    '↪️: left arrow curving right (Symbols) [Emoji]'
    '⌚: watch (Travel & Places) [Emoji]'
    '⌛: hourglass done (Travel & Places) [Emoji]'
    '⌨️: keyboard (Objects) [Emoji]'
    '⏏️: eject button (Symbols) [Emoji]'
    '⏩: fast-forward button (Symbols) [Emoji]'
    '⏪: fast reverse button (Symbols) [Emoji]'
    '⏫: fast up button (Symbols) [Emoji]'
    '⏬: fast down button (Symbols) [Emoji]'
    '⏭️: next track button (Symbols) [Emoji]'
    '⏮️: last track button (Symbols) [Emoji]'
    '⏯️: play or pause button (Symbols) [Emoji]'
    '⏰: alarm clock (Travel & Places) [Emoji]'
    '⏱️: stopwatch (Travel & Places) [Emoji]'
    '⏲️: timer clock (Travel & Places) [Emoji]'
    '⏳: hourglass not done (Travel & Places) [Emoji]'
    '⏸️: pause button (Symbols) [Emoji]'
    '⏹️: stop button (Symbols) [Emoji]'
    '⏺️: record button (Symbols) [Emoji]'
    'Ⓜ️: circled M (Symbols) [Emoji]'
    '▪️: black small square (Symbols) [Emoji]'
    '▫️: white small square (Symbols) [Emoji]'
    '▶️: play button (Symbols) [Emoji]'
    '◀️: reverse button (Symbols) [Emoji]'
    '◻️: white medium square (Symbols) [Emoji]'
    '◼️: black medium square (Symbols) [Emoji]'
    '◽: white medium-small square (Symbols) [Emoji]'
    '◾: black medium-small square (Symbols) [Emoji]'
    '☀️: sun (Travel & Places) [Emoji]'
    '☁️: cloud (Travel & Places) [Emoji]'
    '☂️: umbrella (Travel & Places) [Emoji]'
    '☃️: snowman (Travel & Places) [Emoji]'
    '☄️: comet (Travel & Places) [Emoji]'
    '☎️: telephone (Objects) [Emoji]'
    '☑️: check box with check (Symbols) [Emoji]'
    '☔: umbrella with rain drops (Travel & Places) [Emoji]'
    '☕: hot beverage (Food & Drink) [Emoji]'
    '☘️: shamrock (Animals & Nature) [Emoji]'
    '☝️: index pointing up (People & Body) [Emoji]'
    '☠️: skull and crossbones (Smileys & Emotion) [Emoji]'
    '☢️: radioactive (Symbols) [Emoji]'
    '☣️: biohazard (Symbols) [Emoji]'
    '☦️: orthodox cross (Symbols) [Emoji]'
    '☪️: star and crescent (Symbols) [Emoji]'
    '☮️: peace symbol (Symbols) [Emoji]'
    '☯️: yin yang (Symbols) [Emoji]'
    '☸️: wheel of dharma (Symbols) [Emoji]'
    '☹️: frowning face (Smileys & Emotion) [Emoji]'
    '☺️: smiling face (Smileys & Emotion) [Emoji]'
    '♀️: female sign (Symbols) [Emoji]'
    '♂️: male sign (Symbols) [Emoji]'
    '♈: Aries (Symbols) [Emoji]'
    '♉: Taurus (Symbols) [Emoji]'
    '♊: Gemini (Symbols) [Emoji]'
    '♋: Cancer (Symbols) [Emoji]'
    '♌: Leo (Symbols) [Emoji]'
    '♍: Virgo (Symbols) [Emoji]'
    '♎: Libra (Symbols) [Emoji]'
    '♏: Scorpio (Symbols) [Emoji]'
    '♐: Sagittarius (Symbols) [Emoji]'
    '♑: Capricorn (Symbols) [Emoji]'
    '♒: Aquarius (Symbols) [Emoji]'
    '♓: Pisces (Symbols) [Emoji]'
    '♟️: chess pawn (Activities) [Emoji]'
    '♠️: spade suit (Activities) [Emoji]'
    '♣️: club suit (Activities) [Emoji]'
    '♥️: heart suit (Activities) [Emoji]'
    '♦️: diamond suit (Activities) [Emoji]'
    '♨️: hot springs (Travel & Places) [Emoji]'
    '♻️: recycling symbol (Symbols) [Emoji]'
    '♾️: infinity (Symbols) [Emoji]'
    '♿: wheelchair symbol (Symbols) [Emoji]'
    '⚒️: hammer and pick (Objects) [Emoji]'
    '⚓: anchor (Travel & Places) [Emoji]'
    '⚔️: crossed swords (Objects) [Emoji]'
    '⚕️: medical symbol (Symbols) [Emoji]'
    '⚖️: balance scale (Objects) [Emoji]'
    '⚗️: alembic (Objects) [Emoji]'
    '⚙️: gear (Objects) [Emoji]'
    '⚛️: atom symbol (Symbols) [Emoji]'
    '⚜️: fleur-de-lis (Symbols) [Emoji]'
    '⚠️: warning (Symbols) [Emoji]'
    '⚡: high voltage (Travel & Places) [Emoji]'
    '⚧️: transgender symbol (Symbols) [Emoji]'
    '⚪: white circle (Symbols) [Emoji]'
    '⚫: black circle (Symbols) [Emoji]'
    '⚰️: coffin (Objects) [Emoji]'
    '⚱️: funeral urn (Objects) [Emoji]'
    '⚽: soccer ball (Activities) [Emoji]'
    '⚾: baseball (Activities) [Emoji]'
    '⛄: snowman without snow (Travel & Places) [Emoji]'
    '⛅: sun behind cloud (Travel & Places) [Emoji]'
    '⛈️: cloud with lightning and rain (Travel & Places) [Emoji]'
    '⛎: Ophiuchus (Symbols) [Emoji]'
    '⛏️: pick (Objects) [Emoji]'
    '⛑️: rescue worker’s helmet (Objects) [Emoji]'
    '⛓️: chains (Objects) [Emoji]'
    '⛓️‍💥: broken chain (Objects) [Emoji]'
    '⛔: no entry (Symbols) [Emoji]'
    '⛩️: shinto shrine (Travel & Places) [Emoji]'
    '⛪: church (Travel & Places) [Emoji]'
    '⛰️: mountain (Travel & Places) [Emoji]'
    '⛱️: umbrella on ground (Travel & Places) [Emoji]'
    '⛲: fountain (Travel & Places) [Emoji]'
    '⛳: flag in hole (Activities) [Emoji]'
    '⛴️: ferry (Travel & Places) [Emoji]'
    '⛵: sailboat (Travel & Places) [Emoji]'
    '⛷️: skier (People & Body) [Emoji]'
    '⛸️: ice skate (Activities) [Emoji]'
    '⛹️: person bouncing ball (People & Body) [Emoji]'
    '⛹️‍♀️: woman bouncing ball (People & Body) [Emoji]'
    '⛹️‍♂️: man bouncing ball (People & Body) [Emoji]'
    '⛺: tent (Travel & Places) [Emoji]'
    '⛽: fuel pump (Travel & Places) [Emoji]'
    '✂️: scissors (Objects) [Emoji]'
    '✅: check mark button (Symbols) [Emoji]'
    '✈️: airplane (Travel & Places) [Emoji]'
    '✉️: envelope (Objects) [Emoji]'
    '✊: raised fist (People & Body) [Emoji]'
    '✋: raised hand (People & Body) [Emoji]'
    '✌️: victory hand (People & Body) [Emoji]'
    '✍️: writing hand (People & Body) [Emoji]'
    '✏️: pencil (Objects) [Emoji]'
    '✒️: black nib (Objects) [Emoji]'
    '✔️: check mark (Symbols) [Emoji]'
    '✖️: multiply (Symbols) [Emoji]'
    '✝️: latin cross (Symbols) [Emoji]'
    '✡️: star of David (Symbols) [Emoji]'
    '✨: sparkles (Activities) [Emoji]'
    '✳️: eight-spoked asterisk (Symbols) [Emoji]'
    '✴️: eight-pointed star (Symbols) [Emoji]'
    '❄️: snowflake (Travel & Places) [Emoji]'
    '❇️: sparkle (Symbols) [Emoji]'
    '❌: cross mark (Symbols) [Emoji]'
    '❎: cross mark button (Symbols) [Emoji]'
    '❓: red question mark (Symbols) [Emoji]'
    '❔: white question mark (Symbols) [Emoji]'
    '❕: white exclamation mark (Symbols) [Emoji]'
    '❗: red exclamation mark (Symbols) [Emoji]'
    '❣️: heart exclamation (Smileys & Emotion) [Emoji]'
    '❤️: red heart (Smileys & Emotion) [Emoji]'
    '❤️‍🔥: heart on fire (Smileys & Emotion) [Emoji]'
    '❤️‍🩹: mending heart (Smileys & Emotion) [Emoji]'
    '➕: plus (Symbols) [Emoji]'
    '➖: minus (Symbols) [Emoji]'
    '➗: divide (Symbols) [Emoji]'
    '➡️: right arrow (Symbols) [Emoji]'
    '➰: curly loop (Symbols) [Emoji]'
    '➿: double curly loop (Symbols) [Emoji]'
    '⤴️: right arrow curving up (Symbols) [Emoji]'
    '⤵️: right arrow curving down (Symbols) [Emoji]'
    '⬅️: left arrow (Symbols) [Emoji]'
    '⬆️: up arrow (Symbols) [Emoji]'
    '⬇️: down arrow (Symbols) [Emoji]'
    '⬛: black large square (Symbols) [Emoji]'
    '⬜: white large square (Symbols) [Emoji]'
    '⭐: star (Travel & Places) [Emoji]'
    '⭕: hollow red circle (Symbols) [Emoji]'
    '〰️: wavy dash (Symbols) [Emoji]'
    '〽️: part alternation mark (Symbols) [Emoji]'
    '㊗️: Japanese “congratulations” button (Symbols) [Emoji]'
    '㊙️: Japanese “secret” button (Symbols) [Emoji]'
    '🀄: mahjong red dragon (Activities) [Emoji]'
    '🃏: joker (Activities) [Emoji]'
    '🅰️: A button (blood type) (Symbols) [Emoji]'
    '🅱️: B button (blood type) (Symbols) [Emoji]'
    '🅾️: O button (blood type) (Symbols) [Emoji]'
    '🅿️: P button (Symbols) [Emoji]'
    '🆎: AB button (blood type) (Symbols) [Emoji]'
    '🆑: CL button (Symbols) [Emoji]'
    '🆒: COOL button (Symbols) [Emoji]'
    '🆓: FREE button (Symbols) [Emoji]'
    '🆔: ID button (Symbols) [Emoji]'
    '🆕: NEW button (Symbols) [Emoji]'
    '🆖: NG button (Symbols) [Emoji]'
    '🆗: OK button (Symbols) [Emoji]'
    '🆘: SOS button (Symbols) [Emoji]'
    '🆙: UP! button (Symbols) [Emoji]'
    '🆚: VS button (Symbols) [Emoji]'
    '🇦🇨: flag Ascension Island (Flags) [Emoji]'
    '🇦🇩: flag Andorra (Flags) [Emoji]'
    '🇦🇪: flag United Arab Emirates (Flags) [Emoji]'
    '🇦🇫: flag Afghanistan (Flags) [Emoji]'
    '🇦🇬: flag Antigua & Barbuda (Flags) [Emoji]'
    '🇦🇮: flag Anguilla (Flags) [Emoji]'
    '🇦🇱: flag Albania (Flags) [Emoji]'
    '🇦🇲: flag Armenia (Flags) [Emoji]'
    '🇦🇴: flag Angola (Flags) [Emoji]'
    '🇦🇶: flag Antarctica (Flags) [Emoji]'
    '🇦🇷: flag Argentina (Flags) [Emoji]'
    '🇦🇸: flag American Samoa (Flags) [Emoji]'
    '🇦🇹: flag Austria (Flags) [Emoji]'
    '🇦🇺: flag Australia (Flags) [Emoji]'
    '🇦🇼: flag Aruba (Flags) [Emoji]'
    '🇦🇽: flag Åland Islands (Flags) [Emoji]'
    '🇦🇿: flag Azerbaijan (Flags) [Emoji]'
    '🇧🇦: flag Bosnia & Herzegovina (Flags) [Emoji]'
    '🇧🇧: flag Barbados (Flags) [Emoji]'
    '🇧🇩: flag Bangladesh (Flags) [Emoji]'
    '🇧🇪: flag Belgium (Flags) [Emoji]'
    '🇧🇫: flag Burkina Faso (Flags) [Emoji]'
    '🇧🇬: flag Bulgaria (Flags) [Emoji]'
    '🇧🇭: flag Bahrain (Flags) [Emoji]'
    '🇧🇮: flag Burundi (Flags) [Emoji]'
    '🇧🇯: flag Benin (Flags) [Emoji]'
    '🇧🇱: flag St. Barthélemy (Flags) [Emoji]'
    '🇧🇲: flag Bermuda (Flags) [Emoji]'
    '🇧🇳: flag Brunei (Flags) [Emoji]'
    '🇧🇴: flag Bolivia (Flags) [Emoji]'
    '🇧🇶: flag Caribbean Netherlands (Flags) [Emoji]'
    '🇧🇷: flag Brazil (Flags) [Emoji]'
    '🇧🇸: flag Bahamas (Flags) [Emoji]'
    '🇧🇹: flag Bhutan (Flags) [Emoji]'
    '🇧🇻: flag Bouvet Island (Flags) [Emoji]'
    '🇧🇼: flag Botswana (Flags) [Emoji]'
    '🇧🇾: flag Belarus (Flags) [Emoji]'
    '🇧🇿: flag Belize (Flags) [Emoji]'
    '🇨🇦: flag Canada (Flags) [Emoji]'
    '🇨🇨: flag Cocos (Keeling) Islands (Flags) [Emoji]'
    '🇨🇩: flag Congo - Kinshasa (Flags) [Emoji]'
    '🇨🇫: flag Central African Republic (Flags) [Emoji]'
    '🇨🇬: flag Congo - Brazzaville (Flags) [Emoji]'
    '🇨🇭: flag Switzerland (Flags) [Emoji]'
    '🇨🇮: flag Côte d’Ivoire (Flags) [Emoji]'
    '🇨🇰: flag Cook Islands (Flags) [Emoji]'
    '🇨🇱: flag Chile (Flags) [Emoji]'
    '🇨🇲: flag Cameroon (Flags) [Emoji]'
    '🇨🇳: flag China (Flags) [Emoji]'
    '🇨🇴: flag Colombia (Flags) [Emoji]'
    '🇨🇵: flag Clipperton Island (Flags) [Emoji]'
    '🇨🇶: flag Sark (Flags) [Emoji]'
    '🇨🇷: flag Costa Rica (Flags) [Emoji]'
    '🇨🇺: flag Cuba (Flags) [Emoji]'
    '🇨🇻: flag Cape Verde (Flags) [Emoji]'
    '🇨🇼: flag Curaçao (Flags) [Emoji]'
    '🇨🇽: flag Christmas Island (Flags) [Emoji]'
    '🇨🇾: flag Cyprus (Flags) [Emoji]'
    '🇨🇿: flag Czechia (Flags) [Emoji]'
    '🇩🇪: flag Germany (Flags) [Emoji]'
    '🇩🇬: flag Diego Garcia (Flags) [Emoji]'
    '🇩🇯: flag Djibouti (Flags) [Emoji]'
    '🇩🇰: flag Denmark (Flags) [Emoji]'
    '🇩🇲: flag Dominica (Flags) [Emoji]'
    '🇩🇴: flag Dominican Republic (Flags) [Emoji]'
    '🇩🇿: flag Algeria (Flags) [Emoji]'
    '🇪🇦: flag Ceuta & Melilla (Flags) [Emoji]'
    '🇪🇨: flag Ecuador (Flags) [Emoji]'
    '🇪🇪: flag Estonia (Flags) [Emoji]'
    '🇪🇬: flag Egypt (Flags) [Emoji]'
    '🇪🇭: flag Western Sahara (Flags) [Emoji]'
    '🇪🇷: flag Eritrea (Flags) [Emoji]'
    '🇪🇸: flag Spain (Flags) [Emoji]'
    '🇪🇹: flag Ethiopia (Flags) [Emoji]'
    '🇪🇺: flag European Union (Flags) [Emoji]'
    '🇫🇮: flag Finland (Flags) [Emoji]'
    '🇫🇯: flag Fiji (Flags) [Emoji]'
    '🇫🇰: flag Falkland Islands (Flags) [Emoji]'
    '🇫🇲: flag Micronesia (Flags) [Emoji]'
    '🇫🇴: flag Faroe Islands (Flags) [Emoji]'
    '🇫🇷: flag France (Flags) [Emoji]'
    '🇬🇦: flag Gabon (Flags) [Emoji]'
    '🇬🇧: flag United Kingdom (Flags) [Emoji]'
    '🇬🇩: flag Grenada (Flags) [Emoji]'
    '🇬🇪: flag Georgia (Flags) [Emoji]'
    '🇬🇫: flag French Guiana (Flags) [Emoji]'
    '🇬🇬: flag Guernsey (Flags) [Emoji]'
    '🇬🇭: flag Ghana (Flags) [Emoji]'
    '🇬🇮: flag Gibraltar (Flags) [Emoji]'
    '🇬🇱: flag Greenland (Flags) [Emoji]'
    '🇬🇲: flag Gambia (Flags) [Emoji]'
    '🇬🇳: flag Guinea (Flags) [Emoji]'
    '🇬🇵: flag Guadeloupe (Flags) [Emoji]'
    '🇬🇶: flag Equatorial Guinea (Flags) [Emoji]'
    '🇬🇷: flag Greece (Flags) [Emoji]'
    '🇬🇸: flag South Georgia & South Sandwich Islands (Flags) [Emoji]'
    '🇬🇹: flag Guatemala (Flags) [Emoji]'
    '🇬🇺: flag Guam (Flags) [Emoji]'
    '🇬🇼: flag Guinea-Bissau (Flags) [Emoji]'
    '🇬🇾: flag Guyana (Flags) [Emoji]'
    '🇭🇰: flag Hong Kong SAR China (Flags) [Emoji]'
    '🇭🇲: flag Heard & McDonald Islands (Flags) [Emoji]'
    '🇭🇳: flag Honduras (Flags) [Emoji]'
    '🇭🇷: flag Croatia (Flags) [Emoji]'
    '🇭🇹: flag Haiti (Flags) [Emoji]'
    '🇭🇺: flag Hungary (Flags) [Emoji]'
    '🇮🇨: flag Canary Islands (Flags) [Emoji]'
    '🇮🇩: flag Indonesia (Flags) [Emoji]'
    '🇮🇪: flag Ireland (Flags) [Emoji]'
    '🇮🇱: flag Israel (Flags) [Emoji]'
    '🇮🇲: flag Isle of Man (Flags) [Emoji]'
    '🇮🇳: flag India (Flags) [Emoji]'
    '🇮🇴: flag British Indian Ocean Territory (Flags) [Emoji]'
    '🇮🇶: flag Iraq (Flags) [Emoji]'
    '🇮🇷: flag Iran (Flags) [Emoji]'
    '🇮🇸: flag Iceland (Flags) [Emoji]'
    '🇮🇹: flag Italy (Flags) [Emoji]'
    '🇯🇪: flag Jersey (Flags) [Emoji]'
    '🇯🇲: flag Jamaica (Flags) [Emoji]'
    '🇯🇴: flag Jordan (Flags) [Emoji]'
    '🇯🇵: flag Japan (Flags) [Emoji]'
    '🇰🇪: flag Kenya (Flags) [Emoji]'
    '🇰🇬: flag Kyrgyzstan (Flags) [Emoji]'
    '🇰🇭: flag Cambodia (Flags) [Emoji]'
    '🇰🇮: flag Kiribati (Flags) [Emoji]'
    '🇰🇲: flag Comoros (Flags) [Emoji]'
    '🇰🇳: flag St. Kitts & Nevis (Flags) [Emoji]'
    '🇰🇵: flag North Korea (Flags) [Emoji]'
    '🇰🇷: flag South Korea (Flags) [Emoji]'
    '🇰🇼: flag Kuwait (Flags) [Emoji]'
    '🇰🇾: flag Cayman Islands (Flags) [Emoji]'
    '🇰🇿: flag Kazakhstan (Flags) [Emoji]'
    '🇱🇦: flag Laos (Flags) [Emoji]'
    '🇱🇧: flag Lebanon (Flags) [Emoji]'
    '🇱🇨: flag St. Lucia (Flags) [Emoji]'
    '🇱🇮: flag Liechtenstein (Flags) [Emoji]'
    '🇱🇰: flag Sri Lanka (Flags) [Emoji]'
    '🇱🇷: flag Liberia (Flags) [Emoji]'
    '🇱🇸: flag Lesotho (Flags) [Emoji]'
    '🇱🇹: flag Lithuania (Flags) [Emoji]'
    '🇱🇺: flag Luxembourg (Flags) [Emoji]'
    '🇱🇻: flag Latvia (Flags) [Emoji]'
    '🇱🇾: flag Libya (Flags) [Emoji]'
    '🇲🇦: flag Morocco (Flags) [Emoji]'
    '🇲🇨: flag Monaco (Flags) [Emoji]'
    '🇲🇩: flag Moldova (Flags) [Emoji]'
    '🇲🇪: flag Montenegro (Flags) [Emoji]'
    '🇲🇫: flag St. Martin (Flags) [Emoji]'
    '🇲🇬: flag Madagascar (Flags) [Emoji]'
    '🇲🇭: flag Marshall Islands (Flags) [Emoji]'
    '🇲🇰: flag North Macedonia (Flags) [Emoji]'
    '🇲🇱: flag Mali (Flags) [Emoji]'
    '🇲🇲: flag Myanmar (Burma) (Flags) [Emoji]'
    '🇲🇳: flag Mongolia (Flags) [Emoji]'
    '🇲🇴: flag Macao SAR China (Flags) [Emoji]'
    '🇲🇵: flag Northern Mariana Islands (Flags) [Emoji]'
    '🇲🇶: flag Martinique (Flags) [Emoji]'
    '🇲🇷: flag Mauritania (Flags) [Emoji]'
    '🇲🇸: flag Montserrat (Flags) [Emoji]'
    '🇲🇹: flag Malta (Flags) [Emoji]'
    '🇲🇺: flag Mauritius (Flags) [Emoji]'
    '🇲🇻: flag Maldives (Flags) [Emoji]'
    '🇲🇼: flag Malawi (Flags) [Emoji]'
    '🇲🇽: flag Mexico (Flags) [Emoji]'
    '🇲🇾: flag Malaysia (Flags) [Emoji]'
    '🇲🇿: flag Mozambique (Flags) [Emoji]'
    '🇳🇦: flag Namibia (Flags) [Emoji]'
    '🇳🇨: flag New Caledonia (Flags) [Emoji]'
    '🇳🇪: flag Niger (Flags) [Emoji]'
    '🇳🇫: flag Norfolk Island (Flags) [Emoji]'
    '🇳🇬: flag Nigeria (Flags) [Emoji]'
    '🇳🇮: flag Nicaragua (Flags) [Emoji]'
    '🇳🇱: flag Netherlands (Flags) [Emoji]'
    '🇳🇴: flag Norway (Flags) [Emoji]'
    '🇳🇵: flag Nepal (Flags) [Emoji]'
    '🇳🇷: flag Nauru (Flags) [Emoji]'
    '🇳🇺: flag Niue (Flags) [Emoji]'
    '🇳🇿: flag New Zealand (Flags) [Emoji]'
    '🇴🇲: flag Oman (Flags) [Emoji]'
    '🇵🇦: flag Panama (Flags) [Emoji]'
    '🇵🇪: flag Peru (Flags) [Emoji]'
    '🇵🇫: flag French Polynesia (Flags) [Emoji]'
    '🇵🇬: flag Papua New Guinea (Flags) [Emoji]'
    '🇵🇭: flag Philippines (Flags) [Emoji]'
    '🇵🇰: flag Pakistan (Flags) [Emoji]'
    '🇵🇱: flag Poland (Flags) [Emoji]'
    '🇵🇲: flag St. Pierre & Miquelon (Flags) [Emoji]'
    '🇵🇳: flag Pitcairn Islands (Flags) [Emoji]'
    '🇵🇷: flag Puerto Rico (Flags) [Emoji]'
    '🇵🇸: flag Palestinian Territories (Flags) [Emoji]'
    '🇵🇹: flag Portugal (Flags) [Emoji]'
    '🇵🇼: flag Palau (Flags) [Emoji]'
    '🇵🇾: flag Paraguay (Flags) [Emoji]'
    '🇶🇦: flag Qatar (Flags) [Emoji]'
    '🇷🇪: flag Réunion (Flags) [Emoji]'
    '🇷🇴: flag Romania (Flags) [Emoji]'
    '🇷🇸: flag Serbia (Flags) [Emoji]'
    '🇷🇺: flag Russia (Flags) [Emoji]'
    '🇷🇼: flag Rwanda (Flags) [Emoji]'
    '🇸🇦: flag Saudi Arabia (Flags) [Emoji]'
    '🇸🇧: flag Solomon Islands (Flags) [Emoji]'
    '🇸🇨: flag Seychelles (Flags) [Emoji]'
    '🇸🇩: flag Sudan (Flags) [Emoji]'
    '🇸🇪: flag Sweden (Flags) [Emoji]'
    '🇸🇬: flag Singapore (Flags) [Emoji]'
    '🇸🇭: flag St. Helena (Flags) [Emoji]'
    '🇸🇮: flag Slovenia (Flags) [Emoji]'
    '🇸🇯: flag Svalbard & Jan Mayen (Flags) [Emoji]'
    '🇸🇰: flag Slovakia (Flags) [Emoji]'
    '🇸🇱: flag Sierra Leone (Flags) [Emoji]'
    '🇸🇲: flag San Marino (Flags) [Emoji]'
    '🇸🇳: flag Senegal (Flags) [Emoji]'
    '🇸🇴: flag Somalia (Flags) [Emoji]'
    '🇸🇷: flag Suriname (Flags) [Emoji]'
    '🇸🇸: flag South Sudan (Flags) [Emoji]'
    '🇸🇹: flag São Tomé & Príncipe (Flags) [Emoji]'
    '🇸🇻: flag El Salvador (Flags) [Emoji]'
    '🇸🇽: flag Sint Maarten (Flags) [Emoji]'
    '🇸🇾: flag Syria (Flags) [Emoji]'
    '🇸🇿: flag Eswatini (Flags) [Emoji]'
    '🇹🇦: flag Tristan da Cunha (Flags) [Emoji]'
    '🇹🇨: flag Turks & Caicos Islands (Flags) [Emoji]'
    '🇹🇩: flag Chad (Flags) [Emoji]'
    '🇹🇫: flag French Southern Territories (Flags) [Emoji]'
    '🇹🇬: flag Togo (Flags) [Emoji]'
    '🇹🇭: flag Thailand (Flags) [Emoji]'
    '🇹🇯: flag Tajikistan (Flags) [Emoji]'
    '🇹🇰: flag Tokelau (Flags) [Emoji]'
    '🇹🇱: flag Timor-Leste (Flags) [Emoji]'
    '🇹🇲: flag Turkmenistan (Flags) [Emoji]'
    '🇹🇳: flag Tunisia (Flags) [Emoji]'
    '🇹🇴: flag Tonga (Flags) [Emoji]'
    '🇹🇷: flag Türkiye (Flags) [Emoji]'
    '🇹🇹: flag Trinidad & Tobago (Flags) [Emoji]'
    '🇹🇻: flag Tuvalu (Flags) [Emoji]'
    '🇹🇼: flag Taiwan (Flags) [Emoji]'
    '🇹🇿: flag Tanzania (Flags) [Emoji]'
    '🇺🇦: flag Ukraine (Flags) [Emoji]'
    '🇺🇬: flag Uganda (Flags) [Emoji]'
    '🇺🇲: flag U.S. Outlying Islands (Flags) [Emoji]'
    '🇺🇳: flag United Nations (Flags) [Emoji]'
    '🇺🇸: flag United States (Flags) [Emoji]'
    '🇺🇾: flag Uruguay (Flags) [Emoji]'
    '🇺🇿: flag Uzbekistan (Flags) [Emoji]'
    '🇻🇦: flag Vatican City (Flags) [Emoji]'
    '🇻🇨: flag St. Vincent & Grenadines (Flags) [Emoji]'
    '🇻🇪: flag Venezuela (Flags) [Emoji]'
    '🇻🇬: flag British Virgin Islands (Flags) [Emoji]'
    '🇻🇮: flag U.S. Virgin Islands (Flags) [Emoji]'
    '🇻🇳: flag Vietnam (Flags) [Emoji]'
    '🇻🇺: flag Vanuatu (Flags) [Emoji]'
    '🇼🇫: flag Wallis & Futuna (Flags) [Emoji]'
    '🇼🇸: flag Samoa (Flags) [Emoji]'
    '🇽🇰: flag Kosovo (Flags) [Emoji]'
    '🇾🇪: flag Yemen (Flags) [Emoji]'
    '🇾🇹: flag Mayotte (Flags) [Emoji]'
    '🇿🇦: flag South Africa (Flags) [Emoji]'
    '🇿🇲: flag Zambia (Flags) [Emoji]'
    '🇿🇼: flag Zimbabwe (Flags) [Emoji]'
    '🈁: Japanese “here” button (Symbols) [Emoji]'
    '🈂️: Japanese “service charge” button (Symbols) [Emoji]'
    '🈚: Japanese “free of charge” button (Symbols) [Emoji]'
    '🈯: Japanese “reserved” button (Symbols) [Emoji]'
    '🈲: Japanese “prohibited” button (Symbols) [Emoji]'
    '🈳: Japanese “vacancy” button (Symbols) [Emoji]'
    '🈴: Japanese “passing grade” button (Symbols) [Emoji]'
    '🈵: Japanese “no vacancy” button (Symbols) [Emoji]'
    '🈶: Japanese “not free of charge” button (Symbols) [Emoji]'
    '🈷️: Japanese “monthly amount” button (Symbols) [Emoji]'
    '🈸: Japanese “application” button (Symbols) [Emoji]'
    '🈹: Japanese “discount” button (Symbols) [Emoji]'
    '🈺: Japanese “open for business” button (Symbols) [Emoji]'
    '🉐: Japanese “bargain” button (Symbols) [Emoji]'
    '🉑: Japanese “acceptable” button (Symbols) [Emoji]'
    '🌀: cyclone (Travel & Places) [Emoji]'
    '🌁: foggy (Travel & Places) [Emoji]'
    '🌂: closed umbrella (Travel & Places) [Emoji]'
    '🌃: night with stars (Travel & Places) [Emoji]'
    '🌄: sunrise over mountains (Travel & Places) [Emoji]'
    '🌅: sunrise (Travel & Places) [Emoji]'
    '🌆: cityscape at dusk (Travel & Places) [Emoji]'
    '🌇: sunset (Travel & Places) [Emoji]'
    '🌈: rainbow (Travel & Places) [Emoji]'
    '🌉: bridge at night (Travel & Places) [Emoji]'
    '🌊: water wave (Travel & Places) [Emoji]'
    '🌋: volcano (Travel & Places) [Emoji]'
    '🌌: milky way (Travel & Places) [Emoji]'
    '🌍: globe showing Europe-Africa (Travel & Places) [Emoji]'
    '🌎: globe showing Americas (Travel & Places) [Emoji]'
    '🌏: globe showing Asia-Australia (Travel & Places) [Emoji]'
    '🌐: globe with meridians (Travel & Places) [Emoji]'
    '🌑: new moon (Travel & Places) [Emoji]'
    '🌒: waxing crescent moon (Travel & Places) [Emoji]'
    '🌓: first quarter moon (Travel & Places) [Emoji]'
    '🌔: waxing gibbous moon (Travel & Places) [Emoji]'
    '🌕: full moon (Travel & Places) [Emoji]'
    '🌖: waning gibbous moon (Travel & Places) [Emoji]'
    '🌗: last quarter moon (Travel & Places) [Emoji]'
    '🌘: waning crescent moon (Travel & Places) [Emoji]'
    '🌙: crescent moon (Travel & Places) [Emoji]'
    '🌚: new moon face (Travel & Places) [Emoji]'
    '🌛: first quarter moon face (Travel & Places) [Emoji]'
    '🌜: last quarter moon face (Travel & Places) [Emoji]'
    '🌝: full moon face (Travel & Places) [Emoji]'
    '🌞: sun with face (Travel & Places) [Emoji]'
    '🌟: glowing star (Travel & Places) [Emoji]'
    '🌠: shooting star (Travel & Places) [Emoji]'
    '🌡️: thermometer (Travel & Places) [Emoji]'
    '🌤️: sun behind small cloud (Travel & Places) [Emoji]'
    '🌥️: sun behind large cloud (Travel & Places) [Emoji]'
    '🌦️: sun behind rain cloud (Travel & Places) [Emoji]'
    '🌧️: cloud with rain (Travel & Places) [Emoji]'
    '🌨️: cloud with snow (Travel & Places) [Emoji]'
    '🌩️: cloud with lightning (Travel & Places) [Emoji]'
    '🌪️: tornado (Travel & Places) [Emoji]'
    '🌫️: fog (Travel & Places) [Emoji]'
    '🌬️: wind face (Travel & Places) [Emoji]'
    '🌭: hot dog (Food & Drink) [Emoji]'
    '🌮: taco (Food & Drink) [Emoji]'
    '🌯: burrito (Food & Drink) [Emoji]'
    '🌰: chestnut (Food & Drink) [Emoji]'
    '🌱: seedling (Animals & Nature) [Emoji]'
    '🌲: evergreen tree (Animals & Nature) [Emoji]'
    '🌳: deciduous tree (Animals & Nature) [Emoji]'
    '🌴: palm tree (Animals & Nature) [Emoji]'
    '🌵: cactus (Animals & Nature) [Emoji]'
    '🌶️: hot pepper (Food & Drink) [Emoji]'
    '🌷: tulip (Animals & Nature) [Emoji]'
    '🌸: cherry blossom (Animals & Nature) [Emoji]'
    '🌹: rose (Animals & Nature) [Emoji]'
    '🌺: hibiscus (Animals & Nature) [Emoji]'
    '🌻: sunflower (Animals & Nature) [Emoji]'
    '🌼: blossom (Animals & Nature) [Emoji]'
    '🌽: ear of corn (Food & Drink) [Emoji]'
    '🌾: sheaf of rice (Animals & Nature) [Emoji]'
    '🌿: herb (Animals & Nature) [Emoji]'
    '🍀: four leaf clover (Animals & Nature) [Emoji]'
    '🍁: maple leaf (Animals & Nature) [Emoji]'
    '🍂: fallen leaf (Animals & Nature) [Emoji]'
    '🍃: leaf fluttering in wind (Animals & Nature) [Emoji]'
    '🍄: mushroom (Animals & Nature) [Emoji]'
    '🍄‍🟫: brown mushroom (Food & Drink) [Emoji]'
    '🍅: tomato (Food & Drink) [Emoji]'
    '🍆: eggplant (Food & Drink) [Emoji]'
    '🍇: grapes (Food & Drink) [Emoji]'
    '🍈: melon (Food & Drink) [Emoji]'
    '🍉: watermelon (Food & Drink) [Emoji]'
    '🍊: tangerine (Food & Drink) [Emoji]'
    '🍋: lemon (Food & Drink) [Emoji]'
    '🍋‍🟩: lime (Food & Drink) [Emoji]'
    '🍌: banana (Food & Drink) [Emoji]'
    '🍍: pineapple (Food & Drink) [Emoji]'
    '🍎: red apple (Food & Drink) [Emoji]'
    '🍏: green apple (Food & Drink) [Emoji]'
    '🍐: pear (Food & Drink) [Emoji]'
    '🍑: peach (Food & Drink) [Emoji]'
    '🍒: cherries (Food & Drink) [Emoji]'
    '🍓: strawberry (Food & Drink) [Emoji]'
    '🍔: hamburger (Food & Drink) [Emoji]'
    '🍕: pizza (Food & Drink) [Emoji]'
    '🍖: meat on bone (Food & Drink) [Emoji]'
    '🍗: poultry leg (Food & Drink) [Emoji]'
    '🍘: rice cracker (Food & Drink) [Emoji]'
    '🍙: rice ball (Food & Drink) [Emoji]'
    '🍚: cooked rice (Food & Drink) [Emoji]'
    '🍛: curry rice (Food & Drink) [Emoji]'
    '🍜: steaming bowl (Food & Drink) [Emoji]'
    '🍝: spaghetti (Food & Drink) [Emoji]'
    '🍞: bread (Food & Drink) [Emoji]'
    '🍟: french fries (Food & Drink) [Emoji]'
    '🍠: roasted sweet potato (Food & Drink) [Emoji]'
    '🍡: dango (Food & Drink) [Emoji]'
    '🍢: oden (Food & Drink) [Emoji]'
    '🍣: sushi (Food & Drink) [Emoji]'
    '🍤: fried shrimp (Food & Drink) [Emoji]'
    '🍥: fish cake with swirl (Food & Drink) [Emoji]'
    '🍦: soft ice cream (Food & Drink) [Emoji]'
    '🍧: shaved ice (Food & Drink) [Emoji]'
    '🍨: ice cream (Food & Drink) [Emoji]'
    '🍩: doughnut (Food & Drink) [Emoji]'
    '🍪: cookie (Food & Drink) [Emoji]'
    '🍫: chocolate bar (Food & Drink) [Emoji]'
    '🍬: candy (Food & Drink) [Emoji]'
    '🍭: lollipop (Food & Drink) [Emoji]'
    '🍮: custard (Food & Drink) [Emoji]'
    '🍯: honey pot (Food & Drink) [Emoji]'
    '🍰: shortcake (Food & Drink) [Emoji]'
    '🍱: bento box (Food & Drink) [Emoji]'
    '🍲: pot of food (Food & Drink) [Emoji]'
    '🍳: cooking (Food & Drink) [Emoji]'
    '🍴: fork and knife (Food & Drink) [Emoji]'
    '🍵: teacup without handle (Food & Drink) [Emoji]'
    '🍶: sake (Food & Drink) [Emoji]'
    '🍷: wine glass (Food & Drink) [Emoji]'
    '🍸: cocktail glass (Food & Drink) [Emoji]'
    '🍹: tropical drink (Food & Drink) [Emoji]'
    '🍺: beer mug (Food & Drink) [Emoji]'
    '🍻: clinking beer mugs (Food & Drink) [Emoji]'
    '🍼: baby bottle (Food & Drink) [Emoji]'
    '🍽️: fork and knife with plate (Food & Drink) [Emoji]'
    '🍾: bottle with popping cork (Food & Drink) [Emoji]'
    '🍿: popcorn (Food & Drink) [Emoji]'
    '🎀: ribbon (Activities) [Emoji]'
    '🎁: wrapped gift (Activities) [Emoji]'
    '🎂: birthday cake (Food & Drink) [Emoji]'
    '🎃: jack-o-lantern (Activities) [Emoji]'
    '🎄: Christmas tree (Activities) [Emoji]'
    '🎅: Santa Claus (People & Body) [Emoji]'
    '🎆: fireworks (Activities) [Emoji]'
    '🎇: sparkler (Activities) [Emoji]'
    '🎈: balloon (Activities) [Emoji]'
    '🎉: party popper (Activities) [Emoji]'
    '🎊: confetti ball (Activities) [Emoji]'
    '🎋: tanabata tree (Activities) [Emoji]'
    '🎌: crossed flags (Flags) [Emoji]'
    '🎍: pine decoration (Activities) [Emoji]'
    '🎎: Japanese dolls (Activities) [Emoji]'
    '🎏: carp streamer (Activities) [Emoji]'
    '🎐: wind chime (Activities) [Emoji]'
    '🎑: moon viewing ceremony (Activities) [Emoji]'
    '🎒: backpack (Objects) [Emoji]'
    '🎓: graduation cap (Objects) [Emoji]'
    '🎖️: military medal (Activities) [Emoji]'
    '🎗️: reminder ribbon (Activities) [Emoji]'
    '🎙️: studio microphone (Objects) [Emoji]'
    '🎚️: level slider (Objects) [Emoji]'
    '🎛️: control knobs (Objects) [Emoji]'
    '🎞️: film frames (Objects) [Emoji]'
    '🎟️: admission tickets (Activities) [Emoji]'
    '🎠: carousel horse (Travel & Places) [Emoji]'
    '🎡: ferris wheel (Travel & Places) [Emoji]'
    '🎢: roller coaster (Travel & Places) [Emoji]'
    '🎣: fishing pole (Activities) [Emoji]'
    '🎤: microphone (Objects) [Emoji]'
    '🎥: movie camera (Objects) [Emoji]'
    '🎦: cinema (Symbols) [Emoji]'
    '🎧: headphone (Objects) [Emoji]'
    '🎨: artist palette (Activities) [Emoji]'
    '🎩: top hat (Objects) [Emoji]'
    '🎪: circus tent (Travel & Places) [Emoji]'
    '🎫: ticket (Activities) [Emoji]'
    '🎬: clapper board (Objects) [Emoji]'
    '🎭: performing arts (Activities) [Emoji]'
    '🎮: video game (Activities) [Emoji]'
    '🎯: bullseye (Activities) [Emoji]'
    '🎰: slot machine (Activities) [Emoji]'
    '🎱: pool 8 ball (Activities) [Emoji]'
    '🎲: game die (Activities) [Emoji]'
    '🎳: bowling (Activities) [Emoji]'
    '🎴: flower playing cards (Activities) [Emoji]'
    '🎵: musical note (Objects) [Emoji]'
    '🎶: musical notes (Objects) [Emoji]'
    '🎷: saxophone (Objects) [Emoji]'
    '🎸: guitar (Objects) [Emoji]'
    '🎹: musical keyboard (Objects) [Emoji]'
    '🎺: trumpet (Objects) [Emoji]'
    '🎻: violin (Objects) [Emoji]'
    '🎼: musical score (Objects) [Emoji]'
    '🎽: running shirt (Activities) [Emoji]'
    '🎾: tennis (Activities) [Emoji]'
    '🎿: skis (Activities) [Emoji]'
    '🏀: basketball (Activities) [Emoji]'
    '🏁: chequered flag (Flags) [Emoji]'
    '🏂: snowboarder (People & Body) [Emoji]'
    '🏃: person running (People & Body) [Emoji]'
    '🏃‍♀️: woman running (People & Body) [Emoji]'
    '🏃‍♀️‍➡️: woman running facing right (People & Body) [Emoji]'
    '🏃‍♂️: man running (People & Body) [Emoji]'
    '🏃‍♂️‍➡️: man running facing right (People & Body) [Emoji]'
    '🏃‍➡️: person running facing right (People & Body) [Emoji]'
    '🏄: person surfing (People & Body) [Emoji]'
    '🏄‍♀️: woman surfing (People & Body) [Emoji]'
    '🏄‍♂️: man surfing (People & Body) [Emoji]'
    '🏅: sports medal (Activities) [Emoji]'
    '🏆: trophy (Activities) [Emoji]'
    '🏇: horse racing (People & Body) [Emoji]'
    '🏈: american football (Activities) [Emoji]'
    '🏉: rugby football (Activities) [Emoji]'
    '🏊: person swimming (People & Body) [Emoji]'
    '🏊‍♀️: woman swimming (People & Body) [Emoji]'
    '🏊‍♂️: man swimming (People & Body) [Emoji]'
    '🏋️: person lifting weights (People & Body) [Emoji]'
    '🏋️‍♀️: woman lifting weights (People & Body) [Emoji]'
    '🏋️‍♂️: man lifting weights (People & Body) [Emoji]'
    '🏌️: person golfing (People & Body) [Emoji]'
    '🏌️‍♀️: woman golfing (People & Body) [Emoji]'
    '🏌️‍♂️: man golfing (People & Body) [Emoji]'
    '🏍️: motorcycle (Travel & Places) [Emoji]'
    '🏎️: racing car (Travel & Places) [Emoji]'
    '🏏: cricket game (Activities) [Emoji]'
    '🏐: volleyball (Activities) [Emoji]'
    '🏑: field hockey (Activities) [Emoji]'
    '🏒: ice hockey (Activities) [Emoji]'
    '🏓: ping pong (Activities) [Emoji]'
    '🏔️: snow-capped mountain (Travel & Places) [Emoji]'
    '🏕️: camping (Travel & Places) [Emoji]'
    '🏖️: beach with umbrella (Travel & Places) [Emoji]'
    '🏗️: building construction (Travel & Places) [Emoji]'
    '🏘️: houses (Travel & Places) [Emoji]'
    '🏙️: cityscape (Travel & Places) [Emoji]'
    '🏚️: derelict house (Travel & Places) [Emoji]'
    '🏛️: classical building (Travel & Places) [Emoji]'
    '🏜️: desert (Travel & Places) [Emoji]'
    '🏝️: desert island (Travel & Places) [Emoji]'
    '🏞️: national park (Travel & Places) [Emoji]'
    '🏟️: stadium (Travel & Places) [Emoji]'
    '🏠: house (Travel & Places) [Emoji]'
    '🏡: house with garden (Travel & Places) [Emoji]'
    '🏢: office building (Travel & Places) [Emoji]'
    '🏣: Japanese post office (Travel & Places) [Emoji]'
    '🏤: post office (Travel & Places) [Emoji]'
    '🏥: hospital (Travel & Places) [Emoji]'
    '🏦: bank (Travel & Places) [Emoji]'
    '🏧: ATM sign (Symbols) [Emoji]'
    '🏨: hotel (Travel & Places) [Emoji]'
    '🏩: love hotel (Travel & Places) [Emoji]'
    '🏪: convenience store (Travel & Places) [Emoji]'
    '🏫: school (Travel & Places) [Emoji]'
    '🏬: department store (Travel & Places) [Emoji]'
    '🏭: factory (Travel & Places) [Emoji]'
    '🏮: red paper lantern (Objects) [Emoji]'
    '🏯: Japanese castle (Travel & Places) [Emoji]'
    '🏰: castle (Travel & Places) [Emoji]'
    '🏳️: white flag (Flags) [Emoji]'
    '🏳️‍⚧️: transgender flag (Flags) [Emoji]'
    '🏳️‍🌈: rainbow flag (Flags) [Emoji]'
    '🏴: black flag (Flags) [Emoji]'
    '🏴‍☠️: pirate flag (Flags) [Emoji]'
    '🏴󠁧󠁢󠁥󠁮󠁧󠁿: flag England (Flags) [Emoji]'
    '🏴󠁧󠁢󠁳󠁣󠁴󠁿: flag Scotland (Flags) [Emoji]'
    '🏴󠁧󠁢󠁷󠁬󠁳󠁿: flag Wales (Flags) [Emoji]'
    '🏵️: rosette (Animals & Nature) [Emoji]'
    '🏷️: label (Objects) [Emoji]'
    '🏸: badminton (Activities) [Emoji]'
    '🏹: bow and arrow (Objects) [Emoji]'
    '🏺: amphora (Food & Drink) [Emoji]'
    '🐀: rat (Animals & Nature) [Emoji]'
    '🐁: mouse (Animals & Nature) [Emoji]'
    '🐂: ox (Animals & Nature) [Emoji]'
    '🐃: water buffalo (Animals & Nature) [Emoji]'
    '🐄: cow (Animals & Nature) [Emoji]'
    '🐅: tiger (Animals & Nature) [Emoji]'
    '🐆: leopard (Animals & Nature) [Emoji]'
    '🐇: rabbit (Animals & Nature) [Emoji]'
    '🐈: cat (Animals & Nature) [Emoji]'
    '🐈‍⬛: black cat (Animals & Nature) [Emoji]'
    '🐉: dragon (Animals & Nature) [Emoji]'
    '🐊: crocodile (Animals & Nature) [Emoji]'
    '🐋: whale (Animals & Nature) [Emoji]'
    '🐌: snail (Animals & Nature) [Emoji]'
    '🐍: snake (Animals & Nature) [Emoji]'
    '🐎: horse (Animals & Nature) [Emoji]'
    '🐏: ram (Animals & Nature) [Emoji]'
    '🐐: goat (Animals & Nature) [Emoji]'
    '🐑: ewe (Animals & Nature) [Emoji]'
    '🐒: monkey (Animals & Nature) [Emoji]'
    '🐓: rooster (Animals & Nature) [Emoji]'
    '🐔: chicken (Animals & Nature) [Emoji]'
    '🐕: dog (Animals & Nature) [Emoji]'
    '🐕‍🦺: service dog (Animals & Nature) [Emoji]'
    '🐖: pig (Animals & Nature) [Emoji]'
    '🐗: boar (Animals & Nature) [Emoji]'
    '🐘: elephant (Animals & Nature) [Emoji]'
    '🐙: octopus (Animals & Nature) [Emoji]'
    '🐚: spiral shell (Animals & Nature) [Emoji]'
    '🐛: bug (Animals & Nature) [Emoji]'
    '🐜: ant (Animals & Nature) [Emoji]'
    '🐝: honeybee (Animals & Nature) [Emoji]'
    '🐞: lady beetle (Animals & Nature) [Emoji]'
    '🐟: fish (Animals & Nature) [Emoji]'
    '🐠: tropical fish (Animals & Nature) [Emoji]'
    '🐡: blowfish (Animals & Nature) [Emoji]'
    '🐢: turtle (Animals & Nature) [Emoji]'
    '🐣: hatching chick (Animals & Nature) [Emoji]'
    '🐤: baby chick (Animals & Nature) [Emoji]'
    '🐥: front-facing baby chick (Animals & Nature) [Emoji]'
    '🐦: bird (Animals & Nature) [Emoji]'
    '🐦‍⬛: black bird (Animals & Nature) [Emoji]'
    '🐦‍🔥: phoenix (Animals & Nature) [Emoji]'
    '🐧: penguin (Animals & Nature) [Emoji]'
    '🐨: koala (Animals & Nature) [Emoji]'
    '🐩: poodle (Animals & Nature) [Emoji]'
    '🐪: camel (Animals & Nature) [Emoji]'
    '🐫: two-hump camel (Animals & Nature) [Emoji]'
    '🐬: dolphin (Animals & Nature) [Emoji]'
    '🐭: mouse face (Animals & Nature) [Emoji]'
    '🐮: cow face (Animals & Nature) [Emoji]'
    '🐯: tiger face (Animals & Nature) [Emoji]'
    '🐰: rabbit face (Animals & Nature) [Emoji]'
    '🐱: cat face (Animals & Nature) [Emoji]'
    '🐲: dragon face (Animals & Nature) [Emoji]'
    '🐳: spouting whale (Animals & Nature) [Emoji]'
    '🐴: horse face (Animals & Nature) [Emoji]'
    '🐵: monkey face (Animals & Nature) [Emoji]'
    '🐶: dog face (Animals & Nature) [Emoji]'
    '🐷: pig face (Animals & Nature) [Emoji]'
    '🐸: frog (Animals & Nature) [Emoji]'
    '🐹: hamster (Animals & Nature) [Emoji]'
    '🐺: wolf (Animals & Nature) [Emoji]'
    '🐻: bear (Animals & Nature) [Emoji]'
    '🐻‍❄️: polar bear (Animals & Nature) [Emoji]'
    '🐼: panda (Animals & Nature) [Emoji]'
    '🐽: pig nose (Animals & Nature) [Emoji]'
    '🐾: paw prints (Animals & Nature) [Emoji]'
    '🐿️: chipmunk (Animals & Nature) [Emoji]'
    '👀: eyes (People & Body) [Emoji]'
    '👁️: eye (People & Body) [Emoji]'
    '👁️‍🗨️: eye in speech bubble (Smileys & Emotion) [Emoji]'
    '👂: ear (People & Body) [Emoji]'
    '👃: nose (People & Body) [Emoji]'
    '👄: mouth (People & Body) [Emoji]'
    '👅: tongue (People & Body) [Emoji]'
    '👆: backhand index pointing up (People & Body) [Emoji]'
    '👇: backhand index pointing down (People & Body) [Emoji]'
    '👈: backhand index pointing left (People & Body) [Emoji]'
    '👉: backhand index pointing right (People & Body) [Emoji]'
    '👊: oncoming fist (People & Body) [Emoji]'
    '👋: waving hand (People & Body) [Emoji]'
    '👌: OK hand (People & Body) [Emoji]'
    '👍: thumbs up (People & Body) [Emoji]'
    '👎: thumbs down (People & Body) [Emoji]'
    '👏: clapping hands (People & Body) [Emoji]'
    '👐: open hands (People & Body) [Emoji]'
    '👑: crown (Objects) [Emoji]'
    '👒: woman’s hat (Objects) [Emoji]'
    '👓: glasses (Objects) [Emoji]'
    '👔: necktie (Objects) [Emoji]'
    '👕: t-shirt (Objects) [Emoji]'
    '👖: jeans (Objects) [Emoji]'
    '👗: dress (Objects) [Emoji]'
    '👘: kimono (Objects) [Emoji]'
    '👙: bikini (Objects) [Emoji]'
    '👚: woman’s clothes (Objects) [Emoji]'
    '👛: purse (Objects) [Emoji]'
    '👜: handbag (Objects) [Emoji]'
    '👝: clutch bag (Objects) [Emoji]'
    '👞: man’s shoe (Objects) [Emoji]'
    '👟: running shoe (Objects) [Emoji]'
    '👠: high-heeled shoe (Objects) [Emoji]'
    '👡: woman’s sandal (Objects) [Emoji]'
    '👢: woman’s boot (Objects) [Emoji]'
    '👣: footprints (People & Body) [Emoji]'
    '👤: bust in silhouette (People & Body) [Emoji]'
    '👥: busts in silhouette (People & Body) [Emoji]'
    '👦: boy (People & Body) [Emoji]'
    '👧: girl (People & Body) [Emoji]'
    '👨: man (People & Body) [Emoji]'
    '👨‍⚕️: man health worker (People & Body) [Emoji]'
    '👨‍⚖️: man judge (People & Body) [Emoji]'
    '👨‍✈️: man pilot (People & Body) [Emoji]'
    '👨‍❤️‍👨: couple with heart man, man (People & Body) [Emoji]'
    '👨‍❤️‍💋‍👨: kiss man, man (People & Body) [Emoji]'
    '👨‍🌾: man farmer (People & Body) [Emoji]'
    '👨‍🍳: man cook (People & Body) [Emoji]'
    '👨‍🍼: man feeding baby (People & Body) [Emoji]'
    '👨‍🎓: man student (People & Body) [Emoji]'
    '👨‍🎤: man singer (People & Body) [Emoji]'
    '👨‍🎨: man artist (People & Body) [Emoji]'
    '👨‍🏫: man teacher (People & Body) [Emoji]'
    '👨‍🏭: man factory worker (People & Body) [Emoji]'
    '👨‍👦: family man, boy (People & Body) [Emoji]'
    '👨‍👦‍👦: family man, boy, boy (People & Body) [Emoji]'
    '👨‍👧: family man, girl (People & Body) [Emoji]'
    '👨‍👧‍👦: family man, girl, boy (People & Body) [Emoji]'
    '👨‍👧‍👧: family man, girl, girl (People & Body) [Emoji]'
    '👨‍👨‍👦: family man, man, boy (People & Body) [Emoji]'
    '👨‍👨‍👦‍👦: family man, man, boy, boy (People & Body) [Emoji]'
    '👨‍👨‍👧: family man, man, girl (People & Body) [Emoji]'
    '👨‍👨‍👧‍👦: family man, man, girl, boy (People & Body) [Emoji]'
    '👨‍👨‍👧‍👧: family man, man, girl, girl (People & Body) [Emoji]'
    '👨‍👩‍👦: family man, woman, boy (People & Body) [Emoji]'
    '👨‍👩‍👦‍👦: family man, woman, boy, boy (People & Body) [Emoji]'
    '👨‍👩‍👧: family man, woman, girl (People & Body) [Emoji]'
    '👨‍👩‍👧‍👦: family man, woman, girl, boy (People & Body) [Emoji]'
    '👨‍👩‍👧‍👧: family man, woman, girl, girl (People & Body) [Emoji]'
    '👨‍💻: man technologist (People & Body) [Emoji]'
    '👨‍💼: man office worker (People & Body) [Emoji]'
    '👨‍🔧: man mechanic (People & Body) [Emoji]'
    '👨‍🔬: man scientist (People & Body) [Emoji]'
    '👨‍🚀: man astronaut (People & Body) [Emoji]'
    '👨‍🚒: man firefighter (People & Body) [Emoji]'
    '👨‍🦯: man with white cane (People & Body) [Emoji]'
    '👨‍🦯‍➡️: man with white cane facing right (People & Body) [Emoji]'
    '👨‍🦰: man red hair (People & Body) [Emoji]'
    '👨‍🦱: man curly hair (People & Body) [Emoji]'
    '👨‍🦲: man bald (People & Body) [Emoji]'
    '👨‍🦳: man white hair (People & Body) [Emoji]'
    '👨‍🦼: man in motorized wheelchair (People & Body) [Emoji]'
    '👨‍🦼‍➡️: man in motorized wheelchair facing right (People & Body) [Emoji]'
    '👨‍🦽: man in manual wheelchair (People & Body) [Emoji]'
    '👨‍🦽‍➡️: man in manual wheelchair facing right (People & Body) [Emoji]'
    '👩: woman (People & Body) [Emoji]'
    '👩‍⚕️: woman health worker (People & Body) [Emoji]'
    '👩‍⚖️: woman judge (People & Body) [Emoji]'
    '👩‍✈️: woman pilot (People & Body) [Emoji]'
    '👩‍❤️‍👨: couple with heart woman, man (People & Body) [Emoji]'
    '👩‍❤️‍👩: couple with heart woman, woman (People & Body) [Emoji]'
    '👩‍❤️‍💋‍👨: kiss woman, man (People & Body) [Emoji]'
    '👩‍❤️‍💋‍👩: kiss woman, woman (People & Body) [Emoji]'
    '👩‍🌾: woman farmer (People & Body) [Emoji]'
    '👩‍🍳: woman cook (People & Body) [Emoji]'
    '👩‍🍼: woman feeding baby (People & Body) [Emoji]'
    '👩‍🎓: woman student (People & Body) [Emoji]'
    '👩‍🎤: woman singer (People & Body) [Emoji]'
    '👩‍🎨: woman artist (People & Body) [Emoji]'
    '👩‍🏫: woman teacher (People & Body) [Emoji]'
    '👩‍🏭: woman factory worker (People & Body) [Emoji]'
    '👩‍👦: family woman, boy (People & Body) [Emoji]'
    '👩‍👦‍👦: family woman, boy, boy (People & Body) [Emoji]'
    '👩‍👧: family woman, girl (People & Body) [Emoji]'
    '👩‍👧‍👦: family woman, girl, boy (People & Body) [Emoji]'
    '👩‍👧‍👧: family woman, girl, girl (People & Body) [Emoji]'
    '👩‍👩‍👦: family woman, woman, boy (People & Body) [Emoji]'
    '👩‍👩‍👦‍👦: family woman, woman, boy, boy (People & Body) [Emoji]'
    '👩‍👩‍👧: family woman, woman, girl (People & Body) [Emoji]'
    '👩‍👩‍👧‍👦: family woman, woman, girl, boy (People & Body) [Emoji]'
    '👩‍👩‍👧‍👧: family woman, woman, girl, girl (People & Body) [Emoji]'
    '👩‍💻: woman technologist (People & Body) [Emoji]'
    '👩‍💼: woman office worker (People & Body) [Emoji]'
    '👩‍🔧: woman mechanic (People & Body) [Emoji]'
    '👩‍🔬: woman scientist (People & Body) [Emoji]'
    '👩‍🚀: woman astronaut (People & Body) [Emoji]'
    '👩‍🚒: woman firefighter (People & Body) [Emoji]'
    '👩‍🦯: woman with white cane (People & Body) [Emoji]'
    '👩‍🦯‍➡️: woman with white cane facing right (People & Body) [Emoji]'
    '👩‍🦰: woman red hair (People & Body) [Emoji]'
    '👩‍🦱: woman curly hair (People & Body) [Emoji]'
    '👩‍🦲: woman bald (People & Body) [Emoji]'
    '👩‍🦳: woman white hair (People & Body) [Emoji]'
    '👩‍🦼: woman in motorized wheelchair (People & Body) [Emoji]'
    '👩‍🦼‍➡️: woman in motorized wheelchair facing right (People & Body) [Emoji]'
    '👩‍🦽: woman in manual wheelchair (People & Body) [Emoji]'
    '👩‍🦽‍➡️: woman in manual wheelchair facing right (People & Body) [Emoji]'
    '👪: family (People & Body) [Emoji]'
    '👫: woman and man holding hands (People & Body) [Emoji]'
    '👬: men holding hands (People & Body) [Emoji]'
    '👭: women holding hands (People & Body) [Emoji]'
    '👮: police officer (People & Body) [Emoji]'
    '👮‍♀️: woman police officer (People & Body) [Emoji]'
    '👮‍♂️: man police officer (People & Body) [Emoji]'
    '👯: people with bunny ears (People & Body) [Emoji]'
    '👯‍♀️: women with bunny ears (People & Body) [Emoji]'
    '👯‍♂️: men with bunny ears (People & Body) [Emoji]'
    '👰: person with veil (People & Body) [Emoji]'
    '👰‍♀️: woman with veil (People & Body) [Emoji]'
    '👰‍♂️: man with veil (People & Body) [Emoji]'
    '👱: person blond hair (People & Body) [Emoji]'
    '👱‍♀️: woman blond hair (People & Body) [Emoji]'
    '👱‍♂️: man blond hair (People & Body) [Emoji]'
    '👲: person with skullcap (People & Body) [Emoji]'
    '👳: person wearing turban (People & Body) [Emoji]'
    '👳‍♀️: woman wearing turban (People & Body) [Emoji]'
    '👳‍♂️: man wearing turban (People & Body) [Emoji]'
    '👴: old man (People & Body) [Emoji]'
    '👵: old woman (People & Body) [Emoji]'
    '👶: baby (People & Body) [Emoji]'
    '👷: construction worker (People & Body) [Emoji]'
    '👷‍♀️: woman construction worker (People & Body) [Emoji]'
    '👷‍♂️: man construction worker (People & Body) [Emoji]'
    '👸: princess (People & Body) [Emoji]'
    '👹: ogre (Smileys & Emotion) [Emoji]'
    '👺: goblin (Smileys & Emotion) [Emoji]'
    '👻: ghost (Smileys & Emotion) [Emoji]'
    '👼: baby angel (People & Body) [Emoji]'
    '👽: alien (Smileys & Emotion) [Emoji]'
    '👾: alien monster (Smileys & Emotion) [Emoji]'
    '👿: angry face with horns (Smileys & Emotion) [Emoji]'
    '💀: skull (Smileys & Emotion) [Emoji]'
    '💁: person tipping hand (People & Body) [Emoji]'
    '💁‍♀️: woman tipping hand (People & Body) [Emoji]'
    '💁‍♂️: man tipping hand (People & Body) [Emoji]'
    '💂: guard (People & Body) [Emoji]'
    '💂‍♀️: woman guard (People & Body) [Emoji]'
    '💂‍♂️: man guard (People & Body) [Emoji]'
    '💃: woman dancing (People & Body) [Emoji]'
    '💄: lipstick (Objects) [Emoji]'
    '💅: nail polish (People & Body) [Emoji]'
    '💆: person getting massage (People & Body) [Emoji]'
    '💆‍♀️: woman getting massage (People & Body) [Emoji]'
    '💆‍♂️: man getting massage (People & Body) [Emoji]'
    '💇: person getting haircut (People & Body) [Emoji]'
    '💇‍♀️: woman getting haircut (People & Body) [Emoji]'
    '💇‍♂️: man getting haircut (People & Body) [Emoji]'
    '💈: barber pole (Travel & Places) [Emoji]'
    '💉: syringe (Objects) [Emoji]'
    '💊: pill (Objects) [Emoji]'
    '💋: kiss mark (Smileys & Emotion) [Emoji]'
    '💌: love letter (Smileys & Emotion) [Emoji]'
    '💍: ring (Objects) [Emoji]'
    '💎: gem stone (Objects) [Emoji]'
    '💏: kiss (People & Body) [Emoji]'
    '💐: bouquet (Animals & Nature) [Emoji]'
    '💑: couple with heart (People & Body) [Emoji]'
    '💒: wedding (Travel & Places) [Emoji]'
    '💓: beating heart (Smileys & Emotion) [Emoji]'
    '💔: broken heart (Smileys & Emotion) [Emoji]'
    '💕: two hearts (Smileys & Emotion) [Emoji]'
    '💖: sparkling heart (Smileys & Emotion) [Emoji]'
    '💗: growing heart (Smileys & Emotion) [Emoji]'
    '💘: heart with arrow (Smileys & Emotion) [Emoji]'
    '💙: blue heart (Smileys & Emotion) [Emoji]'
    '💚: green heart (Smileys & Emotion) [Emoji]'
    '💛: yellow heart (Smileys & Emotion) [Emoji]'
    '💜: purple heart (Smileys & Emotion) [Emoji]'
    '💝: heart with ribbon (Smileys & Emotion) [Emoji]'
    '💞: revolving hearts (Smileys & Emotion) [Emoji]'
    '💟: heart decoration (Smileys & Emotion) [Emoji]'
    '💠: diamond with a dot (Symbols) [Emoji]'
    '💡: light bulb (Objects) [Emoji]'
    '💢: anger symbol (Smileys & Emotion) [Emoji]'
    '💣: bomb (Objects) [Emoji]'
    '💤: ZZZ (Smileys & Emotion) [Emoji]'
    '💥: collision (Smileys & Emotion) [Emoji]'
    '💦: sweat droplets (Smileys & Emotion) [Emoji]'
    '💧: droplet (Travel & Places) [Emoji]'
    '💨: dashing away (Smileys & Emotion) [Emoji]'
    '💩: pile of poo (Smileys & Emotion) [Emoji]'
    '💪: flexed biceps (People & Body) [Emoji]'
    '💫: dizzy (Smileys & Emotion) [Emoji]'
    '💬: speech balloon (Smileys & Emotion) [Emoji]'
    '💭: thought balloon (Smileys & Emotion) [Emoji]'
    '💮: white flower (Animals & Nature) [Emoji]'
    '💯: hundred points (Smileys & Emotion) [Emoji]'
    '💰: money bag (Objects) [Emoji]'
    '💱: currency exchange (Symbols) [Emoji]'
    '💲: heavy dollar sign (Symbols) [Emoji]'
    '💳: credit card (Objects) [Emoji]'
    '💴: yen banknote (Objects) [Emoji]'
    '💵: dollar banknote (Objects) [Emoji]'
    '💶: euro banknote (Objects) [Emoji]'
    '💷: pound banknote (Objects) [Emoji]'
    '💸: money with wings (Objects) [Emoji]'
    '💹: chart increasing with yen (Objects) [Emoji]'
    '💺: seat (Travel & Places) [Emoji]'
    '💻: laptop (Objects) [Emoji]'
    '💼: briefcase (Objects) [Emoji]'
    '💽: computer disk (Objects) [Emoji]'
    '💾: floppy disk (Objects) [Emoji]'
    '💿: optical disk (Objects) [Emoji]'
    '📀: dvd (Objects) [Emoji]'
    '📁: file folder (Objects) [Emoji]'
    '📂: open file folder (Objects) [Emoji]'
    '📃: page with curl (Objects) [Emoji]'
    '📄: page facing up (Objects) [Emoji]'
    '📅: calendar (Objects) [Emoji]'
    '📆: tear-off calendar (Objects) [Emoji]'
    '📇: card index (Objects) [Emoji]'
    '📈: chart increasing (Objects) [Emoji]'
    '📉: chart decreasing (Objects) [Emoji]'
    '📊: bar chart (Objects) [Emoji]'
    '📋: clipboard (Objects) [Emoji]'
    '📌: pushpin (Objects) [Emoji]'
    '📍: round pushpin (Objects) [Emoji]'
    '📎: paperclip (Objects) [Emoji]'
    '📏: straight ruler (Objects) [Emoji]'
    '📐: triangular ruler (Objects) [Emoji]'
    '📑: bookmark tabs (Objects) [Emoji]'
    '📒: ledger (Objects) [Emoji]'
    '📓: notebook (Objects) [Emoji]'
    '📔: notebook with decorative cover (Objects) [Emoji]'
    '📕: closed book (Objects) [Emoji]'
    '📖: open book (Objects) [Emoji]'
    '📗: green book (Objects) [Emoji]'
    '📘: blue book (Objects) [Emoji]'
    '📙: orange book (Objects) [Emoji]'
    '📚: books (Objects) [Emoji]'
    '📛: name badge (Symbols) [Emoji]'
    '📜: scroll (Objects) [Emoji]'
    '📝: memo (Objects) [Emoji]'
    '📞: telephone receiver (Objects) [Emoji]'
    '📟: pager (Objects) [Emoji]'
    '📠: fax machine (Objects) [Emoji]'
    '📡: satellite antenna (Objects) [Emoji]'
    '📢: loudspeaker (Objects) [Emoji]'
    '📣: megaphone (Objects) [Emoji]'
    '📤: outbox tray (Objects) [Emoji]'
    '📥: inbox tray (Objects) [Emoji]'
    '📦: package (Objects) [Emoji]'
    '📧: e-mail (Objects) [Emoji]'
    '📨: incoming envelope (Objects) [Emoji]'
    '📩: envelope with arrow (Objects) [Emoji]'
    '📪: closed mailbox with lowered flag (Objects) [Emoji]'
    '📫: closed mailbox with raised flag (Objects) [Emoji]'
    '📬: open mailbox with raised flag (Objects) [Emoji]'
    '📭: open mailbox with lowered flag (Objects) [Emoji]'
    '📮: postbox (Objects) [Emoji]'
    '📯: postal horn (Objects) [Emoji]'
    '📰: newspaper (Objects) [Emoji]'
    '📱: mobile phone (Objects) [Emoji]'
    '📲: mobile phone with arrow (Objects) [Emoji]'
    '📳: vibration mode (Symbols) [Emoji]'
    '📴: mobile phone off (Symbols) [Emoji]'
    '📵: no mobile phones (Symbols) [Emoji]'
    '📶: antenna bars (Symbols) [Emoji]'
    '📷: camera (Objects) [Emoji]'
    '📸: camera with flash (Objects) [Emoji]'
    '📹: video camera (Objects) [Emoji]'
    '📺: television (Objects) [Emoji]'
    '📻: radio (Objects) [Emoji]'
    '📼: videocassette (Objects) [Emoji]'
    '📽️: film projector (Objects) [Emoji]'
    '📿: prayer beads (Objects) [Emoji]'
    '🔀: shuffle tracks button (Symbols) [Emoji]'
    '🔁: repeat button (Symbols) [Emoji]'
    '🔂: repeat single button (Symbols) [Emoji]'
    '🔃: clockwise vertical arrows (Symbols) [Emoji]'
    '🔄: counterclockwise arrows button (Symbols) [Emoji]'
    '🔅: dim button (Symbols) [Emoji]'
    '🔆: bright button (Symbols) [Emoji]'
    '🔇: muted speaker (Objects) [Emoji]'
    '🔈: speaker low volume (Objects) [Emoji]'
    '🔉: speaker medium volume (Objects) [Emoji]'
    '🔊: speaker high volume (Objects) [Emoji]'
    '🔋: battery (Objects) [Emoji]'
    '🔌: electric plug (Objects) [Emoji]'
    '🔍: magnifying glass tilted left (Objects) [Emoji]'
    '🔎: magnifying glass tilted right (Objects) [Emoji]'
    '🔏: locked with pen (Objects) [Emoji]'
    '🔐: locked with key (Objects) [Emoji]'
    '🔑: key (Objects) [Emoji]'
    '🔒: locked (Objects) [Emoji]'
    '🔓: unlocked (Objects) [Emoji]'
    '🔔: bell (Objects) [Emoji]'
    '🔕: bell with slash (Objects) [Emoji]'
    '🔖: bookmark (Objects) [Emoji]'
    '🔗: link (Objects) [Emoji]'
    '🔘: radio button (Symbols) [Emoji]'
    '🔙: BACK arrow (Symbols) [Emoji]'
    '🔚: END arrow (Symbols) [Emoji]'
    '🔛: ON! arrow (Symbols) [Emoji]'
    '🔜: SOON arrow (Symbols) [Emoji]'
    '🔝: TOP arrow (Symbols) [Emoji]'
    '🔞: no one under eighteen (Symbols) [Emoji]'
    '🔟: keycap 10 (Symbols) [Emoji]'
    '🔠: input latin uppercase (Symbols) [Emoji]'
    '🔡: input latin lowercase (Symbols) [Emoji]'
    '🔢: input numbers (Symbols) [Emoji]'
    '🔣: input symbols (Symbols) [Emoji]'
    '🔤: input latin letters (Symbols) [Emoji]'
    '🔥: fire (Travel & Places) [Emoji]'
    '🔦: flashlight (Objects) [Emoji]'
    '🔧: wrench (Objects) [Emoji]'
    '🔨: hammer (Objects) [Emoji]'
    '🔩: nut and bolt (Objects) [Emoji]'
    '🔪: kitchen knife (Food & Drink) [Emoji]'
    '🔫: water pistol (Activities) [Emoji]'
    '🔬: microscope (Objects) [Emoji]'
    '🔭: telescope (Objects) [Emoji]'
    '🔮: crystal ball (Activities) [Emoji]'
    '🔯: dotted six-pointed star (Symbols) [Emoji]'
    '🔰: Japanese symbol for beginner (Symbols) [Emoji]'
    '🔱: trident emblem (Symbols) [Emoji]'
    '🔲: black square button (Symbols) [Emoji]'
    '🔳: white square button (Symbols) [Emoji]'
    '🔴: red circle (Symbols) [Emoji]'
    '🔵: blue circle (Symbols) [Emoji]'
    '🔶: large orange diamond (Symbols) [Emoji]'
    '🔷: large blue diamond (Symbols) [Emoji]'
    '🔸: small orange diamond (Symbols) [Emoji]'
    '🔹: small blue diamond (Symbols) [Emoji]'
    '🔺: red triangle pointed up (Symbols) [Emoji]'
    '🔻: red triangle pointed down (Symbols) [Emoji]'
    '🔼: upwards button (Symbols) [Emoji]'
    '🔽: downwards button (Symbols) [Emoji]'
    '🕉️: om (Symbols) [Emoji]'
    '🕊️: dove (Animals & Nature) [Emoji]'
    '🕋: kaaba (Travel & Places) [Emoji]'
    '🕌: mosque (Travel & Places) [Emoji]'
    '🕍: synagogue (Travel & Places) [Emoji]'
    '🕎: menorah (Symbols) [Emoji]'
    '🕐: one o’clock (Travel & Places) [Emoji]'
    '🕑: two o’clock (Travel & Places) [Emoji]'
    '🕒: three o’clock (Travel & Places) [Emoji]'
    '🕓: four o’clock (Travel & Places) [Emoji]'
    '🕔: five o’clock (Travel & Places) [Emoji]'
    '🕕: six o’clock (Travel & Places) [Emoji]'
    '🕖: seven o’clock (Travel & Places) [Emoji]'
    '🕗: eight o’clock (Travel & Places) [Emoji]'
    '🕘: nine o’clock (Travel & Places) [Emoji]'
    '🕙: ten o’clock (Travel & Places) [Emoji]'
    '🕚: eleven o’clock (Travel & Places) [Emoji]'
    '🕛: twelve o’clock (Travel & Places) [Emoji]'
    '🕜: one-thirty (Travel & Places) [Emoji]'
    '🕝: two-thirty (Travel & Places) [Emoji]'
    '🕞: three-thirty (Travel & Places) [Emoji]'
    '🕟: four-thirty (Travel & Places) [Emoji]'
    '🕠: five-thirty (Travel & Places) [Emoji]'
    '🕡: six-thirty (Travel & Places) [Emoji]'
    '🕢: seven-thirty (Travel & Places) [Emoji]'
    '🕣: eight-thirty (Travel & Places) [Emoji]'
    '🕤: nine-thirty (Travel & Places) [Emoji]'
    '🕥: ten-thirty (Travel & Places) [Emoji]'
    '🕦: eleven-thirty (Travel & Places) [Emoji]'
    '🕧: twelve-thirty (Travel & Places) [Emoji]'
    '🕯️: candle (Objects) [Emoji]'
    '🕰️: mantelpiece clock (Travel & Places) [Emoji]'
    '🕳️: hole (Smileys & Emotion) [Emoji]'
    '🕴️: person in suit levitating (People & Body) [Emoji]'
    '🕵️: detective (People & Body) [Emoji]'
    '🕵️‍♀️: woman detective (People & Body) [Emoji]'
    '🕵️‍♂️: man detective (People & Body) [Emoji]'
    '🕶️: sunglasses (Objects) [Emoji]'
    '🕷️: spider (Animals & Nature) [Emoji]'
    '🕸️: spider web (Animals & Nature) [Emoji]'
    '🕹️: joystick (Activities) [Emoji]'
    '🕺: man dancing (People & Body) [Emoji]'
    '🖇️: linked paperclips (Objects) [Emoji]'
    '🖊️: pen (Objects) [Emoji]'
    '🖋️: fountain pen (Objects) [Emoji]'
    '🖌️: paintbrush (Objects) [Emoji]'
    '🖍️: crayon (Objects) [Emoji]'
    '🖐️: hand with fingers splayed (People & Body) [Emoji]'
    '🖕: middle finger (People & Body) [Emoji]'
    '🖖: vulcan salute (People & Body) [Emoji]'
    '🖤: black heart (Smileys & Emotion) [Emoji]'
    '🖥️: desktop computer (Objects) [Emoji]'
    '🖨️: printer (Objects) [Emoji]'
    '🖱️: computer mouse (Objects) [Emoji]'
    '🖲️: trackball (Objects) [Emoji]'
    '🖼️: framed picture (Activities) [Emoji]'
    '🗂️: card index dividers (Objects) [Emoji]'
    '🗃️: card file box (Objects) [Emoji]'
    '🗄️: file cabinet (Objects) [Emoji]'
    '🗑️: wastebasket (Objects) [Emoji]'
    '🗒️: spiral notepad (Objects) [Emoji]'
    '🗓️: spiral calendar (Objects) [Emoji]'
    '🗜️: clamp (Objects) [Emoji]'
    '🗝️: old key (Objects) [Emoji]'
    '🗞️: rolled-up newspaper (Objects) [Emoji]'
    '🗡️: dagger (Objects) [Emoji]'
    '🗣️: speaking head (People & Body) [Emoji]'
    '🗨️: left speech bubble (Smileys & Emotion) [Emoji]'
    '🗯️: right anger bubble (Smileys & Emotion) [Emoji]'
    '🗳️: ballot box with ballot (Objects) [Emoji]'
    '🗺️: world map (Travel & Places) [Emoji]'
    '🗻: mount fuji (Travel & Places) [Emoji]'
    '🗼: Tokyo tower (Travel & Places) [Emoji]'
    '🗽: Statue of Liberty (Travel & Places) [Emoji]'
    '🗾: map of Japan (Travel & Places) [Emoji]'
    '🗿: moai (Objects) [Emoji]'
    '😀: grinning face (Smileys & Emotion) [Emoji]'
    '😁: beaming face with smiling eyes (Smileys & Emotion) [Emoji]'
    '😂: face with tears of joy (Smileys & Emotion) [Emoji]'
    '😃: grinning face with big eyes (Smileys & Emotion) [Emoji]'
    '😄: grinning face with smiling eyes (Smileys & Emotion) [Emoji]'
    '😅: grinning face with sweat (Smileys & Emotion) [Emoji]'
    '😆: grinning squinting face (Smileys & Emotion) [Emoji]'
    '😇: smiling face with halo (Smileys & Emotion) [Emoji]'
    '😈: smiling face with horns (Smileys & Emotion) [Emoji]'
    '😉: winking face (Smileys & Emotion) [Emoji]'
    '😊: smiling face with smiling eyes (Smileys & Emotion) [Emoji]'
    '😋: face savoring food (Smileys & Emotion) [Emoji]'
    '😌: relieved face (Smileys & Emotion) [Emoji]'
    '😍: smiling face with heart-eyes (Smileys & Emotion) [Emoji]'
    '😎: smiling face with sunglasses (Smileys & Emotion) [Emoji]'
    '😏: smirking face (Smileys & Emotion) [Emoji]'
    '😐: neutral face (Smileys & Emotion) [Emoji]'
    '😑: expressionless face (Smileys & Emotion) [Emoji]'
    '😒: unamused face (Smileys & Emotion) [Emoji]'
    '😓: downcast face with sweat (Smileys & Emotion) [Emoji]'
    '😔: pensive face (Smileys & Emotion) [Emoji]'
    '😕: confused face (Smileys & Emotion) [Emoji]'
    '😖: confounded face (Smileys & Emotion) [Emoji]'
    '😗: kissing face (Smileys & Emotion) [Emoji]'
    '😘: face blowing a kiss (Smileys & Emotion) [Emoji]'
    '😙: kissing face with smiling eyes (Smileys & Emotion) [Emoji]'
    '😚: kissing face with closed eyes (Smileys & Emotion) [Emoji]'
    '😛: face with tongue (Smileys & Emotion) [Emoji]'
    '😜: winking face with tongue (Smileys & Emotion) [Emoji]'
    '😝: squinting face with tongue (Smileys & Emotion) [Emoji]'
    '😞: disappointed face (Smileys & Emotion) [Emoji]'
    '😟: worried face (Smileys & Emotion) [Emoji]'
    '😠: angry face (Smileys & Emotion) [Emoji]'
    '😡: enraged face (Smileys & Emotion) [Emoji]'
    '😢: crying face (Smileys & Emotion) [Emoji]'
    '😣: persevering face (Smileys & Emotion) [Emoji]'
    '😤: face with steam from nose (Smileys & Emotion) [Emoji]'
    '😥: sad but relieved face (Smileys & Emotion) [Emoji]'
    '😦: frowning face with open mouth (Smileys & Emotion) [Emoji]'
    '😧: anguished face (Smileys & Emotion) [Emoji]'
    '😨: fearful face (Smileys & Emotion) [Emoji]'
    '😩: weary face (Smileys & Emotion) [Emoji]'
    '😪: sleepy face (Smileys & Emotion) [Emoji]'
    '😫: tired face (Smileys & Emotion) [Emoji]'
    '😬: grimacing face (Smileys & Emotion) [Emoji]'
    '😭: loudly crying face (Smileys & Emotion) [Emoji]'
    '😮: face with open mouth (Smileys & Emotion) [Emoji]'
    '😮‍💨: face exhaling (Smileys & Emotion) [Emoji]'
    '😯: hushed face (Smileys & Emotion) [Emoji]'
    '😰: anxious face with sweat (Smileys & Emotion) [Emoji]'
    '😱: face screaming in fear (Smileys & Emotion) [Emoji]'
    '😲: astonished face (Smileys & Emotion) [Emoji]'
    '😳: flushed face (Smileys & Emotion) [Emoji]'
    '😴: sleeping face (Smileys & Emotion) [Emoji]'
    '😵: face with crossed-out eyes (Smileys & Emotion) [Emoji]'
    '😵‍💫: face with spiral eyes (Smileys & Emotion) [Emoji]'
    '😶: face without mouth (Smileys & Emotion) [Emoji]'
    '😶‍🌫️: face in clouds (Smileys & Emotion) [Emoji]'
    '😷: face with medical mask (Smileys & Emotion) [Emoji]'
    '😸: grinning cat with smiling eyes (Smileys & Emotion) [Emoji]'
    '😹: cat with tears of joy (Smileys & Emotion) [Emoji]'
    '😺: grinning cat (Smileys & Emotion) [Emoji]'
    '😻: smiling cat with heart-eyes (Smileys & Emotion) [Emoji]'
    '😼: cat with wry smile (Smileys & Emotion) [Emoji]'
    '😽: kissing cat (Smileys & Emotion) [Emoji]'
    '😾: pouting cat (Smileys & Emotion) [Emoji]'
    '😿: crying cat (Smileys & Emotion) [Emoji]'
    '🙀: weary cat (Smileys & Emotion) [Emoji]'
    '🙁: slightly frowning face (Smileys & Emotion) [Emoji]'
    '🙂: slightly smiling face (Smileys & Emotion) [Emoji]'
    '🙂‍↔️: head shaking horizontally (Smileys & Emotion) [Emoji]'
    '🙂‍↕️: head shaking vertically (Smileys & Emotion) [Emoji]'
    '🙃: upside-down face (Smileys & Emotion) [Emoji]'
    '🙄: face with rolling eyes (Smileys & Emotion) [Emoji]'
    '🙅: person gesturing NO (People & Body) [Emoji]'
    '🙅‍♀️: woman gesturing NO (People & Body) [Emoji]'
    '🙅‍♂️: man gesturing NO (People & Body) [Emoji]'
    '🙆: person gesturing OK (People & Body) [Emoji]'
    '🙆‍♀️: woman gesturing OK (People & Body) [Emoji]'
    '🙆‍♂️: man gesturing OK (People & Body) [Emoji]'
    '🙇: person bowing (People & Body) [Emoji]'
    '🙇‍♀️: woman bowing (People & Body) [Emoji]'
    '🙇‍♂️: man bowing (People & Body) [Emoji]'
    '🙈: see-no-evil monkey (Smileys & Emotion) [Emoji]'
    '🙉: hear-no-evil monkey (Smileys & Emotion) [Emoji]'
    '🙊: speak-no-evil monkey (Smileys & Emotion) [Emoji]'
    '🙋: person raising hand (People & Body) [Emoji]'
    '🙋‍♀️: woman raising hand (People & Body) [Emoji]'
    '🙋‍♂️: man raising hand (People & Body) [Emoji]'
    '🙌: raising hands (People & Body) [Emoji]'
    '🙍: person frowning (People & Body) [Emoji]'
    '🙍‍♀️: woman frowning (People & Body) [Emoji]'
    '🙍‍♂️: man frowning (People & Body) [Emoji]'
    '🙎: person pouting (People & Body) [Emoji]'
    '🙎‍♀️: woman pouting (People & Body) [Emoji]'
    '🙎‍♂️: man pouting (People & Body) [Emoji]'
    '🙏: folded hands (People & Body) [Emoji]'
    '🚀: rocket (Travel & Places) [Emoji]'
    '🚁: helicopter (Travel & Places) [Emoji]'
    '🚂: locomotive (Travel & Places) [Emoji]'
    '🚃: railway car (Travel & Places) [Emoji]'
    '🚄: high-speed train (Travel & Places) [Emoji]'
    '🚅: bullet train (Travel & Places) [Emoji]'
    '🚆: train (Travel & Places) [Emoji]'
    '🚇: metro (Travel & Places) [Emoji]'
    '🚈: light rail (Travel & Places) [Emoji]'
    '🚉: station (Travel & Places) [Emoji]'
    '🚊: tram (Travel & Places) [Emoji]'
    '🚋: tram car (Travel & Places) [Emoji]'
    '🚌: bus (Travel & Places) [Emoji]'
    '🚍: oncoming bus (Travel & Places) [Emoji]'
    '🚎: trolleybus (Travel & Places) [Emoji]'
    '🚏: bus stop (Travel & Places) [Emoji]'
    '🚐: minibus (Travel & Places) [Emoji]'
    '🚑: ambulance (Travel & Places) [Emoji]'
    '🚒: fire engine (Travel & Places) [Emoji]'
    '🚓: police car (Travel & Places) [Emoji]'
    '🚔: oncoming police car (Travel & Places) [Emoji]'
    '🚕: taxi (Travel & Places) [Emoji]'
    '🚖: oncoming taxi (Travel & Places) [Emoji]'
    '🚗: automobile (Travel & Places) [Emoji]'
    '🚘: oncoming automobile (Travel & Places) [Emoji]'
    '🚙: sport utility vehicle (Travel & Places) [Emoji]'
    '🚚: delivery truck (Travel & Places) [Emoji]'
    '🚛: articulated lorry (Travel & Places) [Emoji]'
    '🚜: tractor (Travel & Places) [Emoji]'
    '🚝: monorail (Travel & Places) [Emoji]'
    '🚞: mountain railway (Travel & Places) [Emoji]'
    '🚟: suspension railway (Travel & Places) [Emoji]'
    '🚠: mountain cableway (Travel & Places) [Emoji]'
    '🚡: aerial tramway (Travel & Places) [Emoji]'
    '🚢: ship (Travel & Places) [Emoji]'
    '🚣: person rowing boat (People & Body) [Emoji]'
    '🚣‍♀️: woman rowing boat (People & Body) [Emoji]'
    '🚣‍♂️: man rowing boat (People & Body) [Emoji]'
    '🚤: speedboat (Travel & Places) [Emoji]'
    '🚥: horizontal traffic light (Travel & Places) [Emoji]'
    '🚦: vertical traffic light (Travel & Places) [Emoji]'
    '🚧: construction (Travel & Places) [Emoji]'
    '🚨: police car light (Travel & Places) [Emoji]'
    '🚩: triangular flag (Flags) [Emoji]'
    '🚪: door (Objects) [Emoji]'
    '🚫: prohibited (Symbols) [Emoji]'
    '🚬: cigarette (Objects) [Emoji]'
    '🚭: no smoking (Symbols) [Emoji]'
    '🚮: litter in bin sign (Symbols) [Emoji]'
    '🚯: no littering (Symbols) [Emoji]'
    '🚰: potable water (Symbols) [Emoji]'
    '🚱: non-potable water (Symbols) [Emoji]'
    '🚲: bicycle (Travel & Places) [Emoji]'
    '🚳: no bicycles (Symbols) [Emoji]'
    '🚴: person biking (People & Body) [Emoji]'
    '🚴‍♀️: woman biking (People & Body) [Emoji]'
    '🚴‍♂️: man biking (People & Body) [Emoji]'
    '🚵: person mountain biking (People & Body) [Emoji]'
    '🚵‍♀️: woman mountain biking (People & Body) [Emoji]'
    '🚵‍♂️: man mountain biking (People & Body) [Emoji]'
    '🚶: person walking (People & Body) [Emoji]'
    '🚶‍♀️: woman walking (People & Body) [Emoji]'
    '🚶‍♀️‍➡️: woman walking facing right (People & Body) [Emoji]'
    '🚶‍♂️: man walking (People & Body) [Emoji]'
    '🚶‍♂️‍➡️: man walking facing right (People & Body) [Emoji]'
    '🚶‍➡️: person walking facing right (People & Body) [Emoji]'
    '🚷: no pedestrians (Symbols) [Emoji]'
    '🚸: children crossing (Symbols) [Emoji]'
    '🚹: men’s room (Symbols) [Emoji]'
    '🚺: women’s room (Symbols) [Emoji]'
    '🚻: restroom (Symbols) [Emoji]'
    '🚼: baby symbol (Symbols) [Emoji]'
    '🚽: toilet (Objects) [Emoji]'
    '🚾: water closet (Symbols) [Emoji]'
    '🚿: shower (Objects) [Emoji]'
    '🛀: person taking bath (People & Body) [Emoji]'
    '🛁: bathtub (Objects) [Emoji]'
    '🛂: passport control (Symbols) [Emoji]'
    '🛃: customs (Symbols) [Emoji]'
    '🛄: baggage claim (Symbols) [Emoji]'
    '🛅: left luggage (Symbols) [Emoji]'
    '🛋️: couch and lamp (Objects) [Emoji]'
    '🛌: person in bed (People & Body) [Emoji]'
    '🛍️: shopping bags (Objects) [Emoji]'
    '🛎️: bellhop bell (Travel & Places) [Emoji]'
    '🛏️: bed (Objects) [Emoji]'
    '🛐: place of worship (Symbols) [Emoji]'
    '🛑: stop sign (Travel & Places) [Emoji]'
    '🛒: shopping cart (Objects) [Emoji]'
    '🛕: hindu temple (Travel & Places) [Emoji]'
    '🛖: hut (Travel & Places) [Emoji]'
    '🛗: elevator (Objects) [Emoji]'
    '🛜: wireless (Symbols) [Emoji]'
    '🛝: playground slide (Travel & Places) [Emoji]'
    '🛞: wheel (Travel & Places) [Emoji]'
    '🛟: ring buoy (Travel & Places) [Emoji]'
    '🛠️: hammer and wrench (Objects) [Emoji]'
    '🛡️: shield (Objects) [Emoji]'
    '🛢️: oil drum (Travel & Places) [Emoji]'
    '🛣️: motorway (Travel & Places) [Emoji]'
    '🛤️: railway track (Travel & Places) [Emoji]'
    '🛥️: motor boat (Travel & Places) [Emoji]'
    '🛩️: small airplane (Travel & Places) [Emoji]'
    '🛫: airplane departure (Travel & Places) [Emoji]'
    '🛬: airplane arrival (Travel & Places) [Emoji]'
    '🛰️: satellite (Travel & Places) [Emoji]'
    '🛳️: passenger ship (Travel & Places) [Emoji]'
    '🛴: kick scooter (Travel & Places) [Emoji]'
    '🛵: motor scooter (Travel & Places) [Emoji]'
    '🛶: canoe (Travel & Places) [Emoji]'
    '🛷: sled (Activities) [Emoji]'
    '🛸: flying saucer (Travel & Places) [Emoji]'
    '🛹: skateboard (Travel & Places) [Emoji]'
    '🛺: auto rickshaw (Travel & Places) [Emoji]'
    '🛻: pickup truck (Travel & Places) [Emoji]'
    '🛼: roller skate (Travel & Places) [Emoji]'
    '🟠: orange circle (Symbols) [Emoji]'
    '🟡: yellow circle (Symbols) [Emoji]'
    '🟢: green circle (Symbols) [Emoji]'
    '🟣: purple circle (Symbols) [Emoji]'
    '🟤: brown circle (Symbols) [Emoji]'
    '🟥: red square (Symbols) [Emoji]'
    '🟦: blue square (Symbols) [Emoji]'
    '🟧: orange square (Symbols) [Emoji]'
    '🟨: yellow square (Symbols) [Emoji]'
    '🟩: green square (Symbols) [Emoji]'
    '🟪: purple square (Symbols) [Emoji]'
    '🟫: brown square (Symbols) [Emoji]'
    '🟰: heavy equals sign (Symbols) [Emoji]'
    '🤌: pinched fingers (People & Body) [Emoji]'
    '🤍: white heart (Smileys & Emotion) [Emoji]'
    '🤎: brown heart (Smileys & Emotion) [Emoji]'
    '🤏: pinching hand (People & Body) [Emoji]'
    '🤐: zipper-mouth face (Smileys & Emotion) [Emoji]'
    '🤑: money-mouth face (Smileys & Emotion) [Emoji]'
    '🤒: face with thermometer (Smileys & Emotion) [Emoji]'
    '🤓: nerd face (Smileys & Emotion) [Emoji]'
    '🤔: thinking face (Smileys & Emotion) [Emoji]'
    '🤕: face with head-bandage (Smileys & Emotion) [Emoji]'
    '🤖: robot (Smileys & Emotion) [Emoji]'
    '🤗: smiling face with open hands (Smileys & Emotion) [Emoji]'
    '🤘: sign of the horns (People & Body) [Emoji]'
    '🤙: call me hand (People & Body) [Emoji]'
    '🤚: raised back of hand (People & Body) [Emoji]'
    '🤛: left-facing fist (People & Body) [Emoji]'
    '🤜: right-facing fist (People & Body) [Emoji]'
    '🤝: handshake (People & Body) [Emoji]'
    '🤞: crossed fingers (People & Body) [Emoji]'
    '🤟: love-you gesture (People & Body) [Emoji]'
    '🤠: cowboy hat face (Smileys & Emotion) [Emoji]'
    '🤡: clown face (Smileys & Emotion) [Emoji]'
    '🤢: nauseated face (Smileys & Emotion) [Emoji]'
    '🤣: rolling on the floor laughing (Smileys & Emotion) [Emoji]'
    '🤤: drooling face (Smileys & Emotion) [Emoji]'
    '🤥: lying face (Smileys & Emotion) [Emoji]'
    '🤦: person facepalming (People & Body) [Emoji]'
    '🤦‍♀️: woman facepalming (People & Body) [Emoji]'
    '🤦‍♂️: man facepalming (People & Body) [Emoji]'
    '🤧: sneezing face (Smileys & Emotion) [Emoji]'
    '🤨: face with raised eyebrow (Smileys & Emotion) [Emoji]'
    '🤩: star-struck (Smileys & Emotion) [Emoji]'
    '🤪: zany face (Smileys & Emotion) [Emoji]'
    '🤫: shushing face (Smileys & Emotion) [Emoji]'
    '🤬: face with symbols on mouth (Smileys & Emotion) [Emoji]'
    '🤭: face with hand over mouth (Smileys & Emotion) [Emoji]'
    '🤮: face vomiting (Smileys & Emotion) [Emoji]'
    '🤯: exploding head (Smileys & Emotion) [Emoji]'
    '🤰: pregnant woman (People & Body) [Emoji]'
    '🤱: breast-feeding (People & Body) [Emoji]'
    '🤲: palms up together (People & Body) [Emoji]'
    '🤳: selfie (People & Body) [Emoji]'
    '🤴: prince (People & Body) [Emoji]'
    '🤵: person in tuxedo (People & Body) [Emoji]'
    '🤵‍♀️: woman in tuxedo (People & Body) [Emoji]'
    '🤵‍♂️: man in tuxedo (People & Body) [Emoji]'
    '🤶: Mrs. Claus (People & Body) [Emoji]'
    '🤷: person shrugging (People & Body) [Emoji]'
    '🤷‍♀️: woman shrugging (People & Body) [Emoji]'
    '🤷‍♂️: man shrugging (People & Body) [Emoji]'
    '🤸: person cartwheeling (People & Body) [Emoji]'
    '🤸‍♀️: woman cartwheeling (People & Body) [Emoji]'
    '🤸‍♂️: man cartwheeling (People & Body) [Emoji]'
    '🤹: person juggling (People & Body) [Emoji]'
    '🤹‍♀️: woman juggling (People & Body) [Emoji]'
    '🤹‍♂️: man juggling (People & Body) [Emoji]'
    '🤺: person fencing (People & Body) [Emoji]'
    '🤼: people wrestling (People & Body) [Emoji]'
    '🤼‍♀️: women wrestling (People & Body) [Emoji]'
    '🤼‍♂️: men wrestling (People & Body) [Emoji]'
    '🤽: person playing water polo (People & Body) [Emoji]'
    '🤽‍♀️: woman playing water polo (People & Body) [Emoji]'
    '🤽‍♂️: man playing water polo (People & Body) [Emoji]'
    '🤾: person playing handball (People & Body) [Emoji]'
    '🤾‍♀️: woman playing handball (People & Body) [Emoji]'
    '🤾‍♂️: man playing handball (People & Body) [Emoji]'
    '🤿: diving mask (Activities) [Emoji]'
    '🥀: wilted flower (Animals & Nature) [Emoji]'
    '🥁: drum (Objects) [Emoji]'
    '🥂: clinking glasses (Food & Drink) [Emoji]'
    '🥃: tumbler glass (Food & Drink) [Emoji]'
    '🥄: spoon (Food & Drink) [Emoji]'
    '🥅: goal net (Activities) [Emoji]'
    '🥇: 1st place medal (Activities) [Emoji]'
    '🥈: 2nd place medal (Activities) [Emoji]'
    '🥉: 3rd place medal (Activities) [Emoji]'
    '🥊: boxing glove (Activities) [Emoji]'
    '🥋: martial arts uniform (Activities) [Emoji]'
    '🥌: curling stone (Activities) [Emoji]'
    '🥍: lacrosse (Activities) [Emoji]'
    '🥎: softball (Activities) [Emoji]'
    '🥏: flying disc (Activities) [Emoji]'
    '🥐: croissant (Food & Drink) [Emoji]'
    '🥑: avocado (Food & Drink) [Emoji]'
    '🥒: cucumber (Food & Drink) [Emoji]'
    '🥓: bacon (Food & Drink) [Emoji]'
    '🥔: potato (Food & Drink) [Emoji]'
    '🥕: carrot (Food & Drink) [Emoji]'
    '🥖: baguette bread (Food & Drink) [Emoji]'
    '🥗: green salad (Food & Drink) [Emoji]'
    '🥘: shallow pan of food (Food & Drink) [Emoji]'
    '🥙: stuffed flatbread (Food & Drink) [Emoji]'
    '🥚: egg (Food & Drink) [Emoji]'
    '🥛: glass of milk (Food & Drink) [Emoji]'
    '🥜: peanuts (Food & Drink) [Emoji]'
    '🥝: kiwi fruit (Food & Drink) [Emoji]'
    '🥞: pancakes (Food & Drink) [Emoji]'
    '🥟: dumpling (Food & Drink) [Emoji]'
    '🥠: fortune cookie (Food & Drink) [Emoji]'
    '🥡: takeout box (Food & Drink) [Emoji]'
    '🥢: chopsticks (Food & Drink) [Emoji]'
    '🥣: bowl with spoon (Food & Drink) [Emoji]'
    '🥤: cup with straw (Food & Drink) [Emoji]'
    '🥥: coconut (Food & Drink) [Emoji]'
    '🥦: broccoli (Food & Drink) [Emoji]'
    '🥧: pie (Food & Drink) [Emoji]'
    '🥨: pretzel (Food & Drink) [Emoji]'
    '🥩: cut of meat (Food & Drink) [Emoji]'
    '🥪: sandwich (Food & Drink) [Emoji]'
    '🥫: canned food (Food & Drink) [Emoji]'
    '🥬: leafy green (Food & Drink) [Emoji]'
    '🥭: mango (Food & Drink) [Emoji]'
    '🥮: moon cake (Food & Drink) [Emoji]'
    '🥯: bagel (Food & Drink) [Emoji]'
    '🥰: smiling face with hearts (Smileys & Emotion) [Emoji]'
    '🥱: yawning face (Smileys & Emotion) [Emoji]'
    '🥲: smiling face with tear (Smileys & Emotion) [Emoji]'
    '🥳: partying face (Smileys & Emotion) [Emoji]'
    '🥴: woozy face (Smileys & Emotion) [Emoji]'
    '🥵: hot face (Smileys & Emotion) [Emoji]'
    '🥶: cold face (Smileys & Emotion) [Emoji]'
    '🥷: ninja (People & Body) [Emoji]'
    '🥸: disguised face (Smileys & Emotion) [Emoji]'
    '🥹: face holding back tears (Smileys & Emotion) [Emoji]'
    '🥺: pleading face (Smileys & Emotion) [Emoji]'
    '🥻: sari (Objects) [Emoji]'
    '🥼: lab coat (Objects) [Emoji]'
    '🥽: goggles (Objects) [Emoji]'
    '🥾: hiking boot (Objects) [Emoji]'
    '🥿: flat shoe (Objects) [Emoji]'
    '🦀: crab (Animals & Nature) [Emoji]'
    '🦁: lion (Animals & Nature) [Emoji]'
    '🦂: scorpion (Animals & Nature) [Emoji]'
    '🦃: turkey (Animals & Nature) [Emoji]'
    '🦄: unicorn (Animals & Nature) [Emoji]'
    '🦅: eagle (Animals & Nature) [Emoji]'
    '🦆: duck (Animals & Nature) [Emoji]'
    '🦇: bat (Animals & Nature) [Emoji]'
    '🦈: shark (Animals & Nature) [Emoji]'
    '🦉: owl (Animals & Nature) [Emoji]'
    '🦊: fox (Animals & Nature) [Emoji]'
    '🦋: butterfly (Animals & Nature) [Emoji]'
    '🦌: deer (Animals & Nature) [Emoji]'
    '🦍: gorilla (Animals & Nature) [Emoji]'
    '🦎: lizard (Animals & Nature) [Emoji]'
    '🦏: rhinoceros (Animals & Nature) [Emoji]'
    '🦐: shrimp (Animals & Nature) [Emoji]'
    '🦑: squid (Animals & Nature) [Emoji]'
    '🦒: giraffe (Animals & Nature) [Emoji]'
    '🦓: zebra (Animals & Nature) [Emoji]'
    '🦔: hedgehog (Animals & Nature) [Emoji]'
    '🦕: sauropod (Animals & Nature) [Emoji]'
    '🦖: T-Rex (Animals & Nature) [Emoji]'
    '🦗: cricket (Animals & Nature) [Emoji]'
    '🦘: kangaroo (Animals & Nature) [Emoji]'
    '🦙: llama (Animals & Nature) [Emoji]'
    '🦚: peacock (Animals & Nature) [Emoji]'
    '🦛: hippopotamus (Animals & Nature) [Emoji]'
    '🦜: parrot (Animals & Nature) [Emoji]'
    '🦝: raccoon (Animals & Nature) [Emoji]'
    '🦞: lobster (Animals & Nature) [Emoji]'
    '🦟: mosquito (Animals & Nature) [Emoji]'
    '🦠: microbe (Animals & Nature) [Emoji]'
    '🦡: badger (Animals & Nature) [Emoji]'
    '🦢: swan (Animals & Nature) [Emoji]'
    '🦣: mammoth (Animals & Nature) [Emoji]'
    '🦤: dodo (Animals & Nature) [Emoji]'
    '🦥: sloth (Animals & Nature) [Emoji]'
    '🦦: otter (Animals & Nature) [Emoji]'
    '🦧: orangutan (Animals & Nature) [Emoji]'
    '🦨: skunk (Animals & Nature) [Emoji]'
    '🦩: flamingo (Animals & Nature) [Emoji]'
    '🦪: oyster (Animals & Nature) [Emoji]'
    '🦫: beaver (Animals & Nature) [Emoji]'
    '🦬: bison (Animals & Nature) [Emoji]'
    '🦭: seal (Animals & Nature) [Emoji]'
    '🦮: guide dog (Animals & Nature) [Emoji]'
    '🦯: white cane (Objects) [Emoji]'
    '🦴: bone (People & Body) [Emoji]'
    '🦵: leg (People & Body) [Emoji]'
    '🦶: foot (People & Body) [Emoji]'
    '🦷: tooth (People & Body) [Emoji]'
    '🦸: superhero (People & Body) [Emoji]'
    '🦸‍♀️: woman superhero (People & Body) [Emoji]'
    '🦸‍♂️: man superhero (People & Body) [Emoji]'
    '🦹: supervillain (People & Body) [Emoji]'
    '🦹‍♀️: woman supervillain (People & Body) [Emoji]'
    '🦹‍♂️: man supervillain (People & Body) [Emoji]'
    '🦺: safety vest (Objects) [Emoji]'
    '🦻: ear with hearing aid (People & Body) [Emoji]'
    '🦼: motorized wheelchair (Travel & Places) [Emoji]'
    '🦽: manual wheelchair (Travel & Places) [Emoji]'
    '🦾: mechanical arm (People & Body) [Emoji]'
    '🦿: mechanical leg (People & Body) [Emoji]'
    '🧀: cheese wedge (Food & Drink) [Emoji]'
    '🧁: cupcake (Food & Drink) [Emoji]'
    '🧂: salt (Food & Drink) [Emoji]'
    '🧃: beverage box (Food & Drink) [Emoji]'
    '🧄: garlic (Food & Drink) [Emoji]'
    '🧅: onion (Food & Drink) [Emoji]'
    '🧆: falafel (Food & Drink) [Emoji]'
    '🧇: waffle (Food & Drink) [Emoji]'
    '🧈: butter (Food & Drink) [Emoji]'
    '🧉: mate (Food & Drink) [Emoji]'
    '🧊: ice (Food & Drink) [Emoji]'
    '🧋: bubble tea (Food & Drink) [Emoji]'
    '🧌: troll (People & Body) [Emoji]'
    '🧍: person standing (People & Body) [Emoji]'
    '🧍‍♀️: woman standing (People & Body) [Emoji]'
    '🧍‍♂️: man standing (People & Body) [Emoji]'
    '🧎: person kneeling (People & Body) [Emoji]'
    '🧎‍♀️: woman kneeling (People & Body) [Emoji]'
    '🧎‍♀️‍➡️: woman kneeling facing right (People & Body) [Emoji]'
    '🧎‍♂️: man kneeling (People & Body) [Emoji]'
    '🧎‍♂️‍➡️: man kneeling facing right (People & Body) [Emoji]'
    '🧎‍➡️: person kneeling facing right (People & Body) [Emoji]'
    '🧏: deaf person (People & Body) [Emoji]'
    '🧏‍♀️: deaf woman (People & Body) [Emoji]'
    '🧏‍♂️: deaf man (People & Body) [Emoji]'
    '🧐: face with monocle (Smileys & Emotion) [Emoji]'
    '🧑: person (People & Body) [Emoji]'
    '🧑‍⚕️: health worker (People & Body) [Emoji]'
    '🧑‍⚖️: judge (People & Body) [Emoji]'
    '🧑‍✈️: pilot (People & Body) [Emoji]'
    '🧑‍🌾: farmer (People & Body) [Emoji]'
    '🧑‍🍳: cook (People & Body) [Emoji]'
    '🧑‍🍼: person feeding baby (People & Body) [Emoji]'
    '🧑‍🎄: Mx Claus (People & Body) [Emoji]'
    '🧑‍🎓: student (People & Body) [Emoji]'
    '🧑‍🎤: singer (People & Body) [Emoji]'
    '🧑‍🎨: artist (People & Body) [Emoji]'
    '🧑‍🏫: teacher (People & Body) [Emoji]'
    '🧑‍🏭: factory worker (People & Body) [Emoji]'
    '🧑‍💻: technologist (People & Body) [Emoji]'
    '🧑‍💼: office worker (People & Body) [Emoji]'
    '🧑‍🔧: mechanic (People & Body) [Emoji]'
    '🧑‍🔬: scientist (People & Body) [Emoji]'
    '🧑‍🚀: astronaut (People & Body) [Emoji]'
    '🧑‍🚒: firefighter (People & Body) [Emoji]'
    '🧑‍🤝‍🧑: people holding hands (People & Body) [Emoji]'
    '🧑‍🦯: person with white cane (People & Body) [Emoji]'
    '🧑‍🦯‍➡️: person with white cane facing right (People & Body) [Emoji]'
    '🧑‍🦰: person red hair (People & Body) [Emoji]'
    '🧑‍🦱: person curly hair (People & Body) [Emoji]'
    '🧑‍🦲: person bald (People & Body) [Emoji]'
    '🧑‍🦳: person white hair (People & Body) [Emoji]'
    '🧑‍🦼: person in motorized wheelchair (People & Body) [Emoji]'
    '🧑‍🦼‍➡️: person in motorized wheelchair facing right (People & Body) [Emoji]'
    '🧑‍🦽: person in manual wheelchair (People & Body) [Emoji]'
    '🧑‍🦽‍➡️: person in manual wheelchair facing right (People & Body) [Emoji]'
    '🧑‍🧑‍🧒: family adult, adult, child (People & Body) [Emoji]'
    '🧑‍🧑‍🧒‍🧒: family adult, adult, child, child (People & Body) [Emoji]'
    '🧑‍🧒: family adult, child (People & Body) [Emoji]'
    '🧑‍🧒‍🧒: family adult, child, child (People & Body) [Emoji]'
    '🧒: child (People & Body) [Emoji]'
    '🧓: older person (People & Body) [Emoji]'
    '🧔: person beard (People & Body) [Emoji]'
    '🧔‍♀️: woman beard (People & Body) [Emoji]'
    '🧔‍♂️: man beard (People & Body) [Emoji]'
    '🧕: woman with headscarf (People & Body) [Emoji]'
    '🧖: person in steamy room (People & Body) [Emoji]'
    '🧖‍♀️: woman in steamy room (People & Body) [Emoji]'
    '🧖‍♂️: man in steamy room (People & Body) [Emoji]'
    '🧗: person climbing (People & Body) [Emoji]'
    '🧗‍♀️: woman climbing (People & Body) [Emoji]'
    '🧗‍♂️: man climbing (People & Body) [Emoji]'
    '🧘: person in lotus position (People & Body) [Emoji]'
    '🧘‍♀️: woman in lotus position (People & Body) [Emoji]'
    '🧘‍♂️: man in lotus position (People & Body) [Emoji]'
    '🧙: mage (People & Body) [Emoji]'
    '🧙‍♀️: woman mage (People & Body) [Emoji]'
    '🧙‍♂️: man mage (People & Body) [Emoji]'
    '🧚: fairy (People & Body) [Emoji]'
    '🧚‍♀️: woman fairy (People & Body) [Emoji]'
    '🧚‍♂️: man fairy (People & Body) [Emoji]'
    '🧛: vampire (People & Body) [Emoji]'
    '🧛‍♀️: woman vampire (People & Body) [Emoji]'
    '🧛‍♂️: man vampire (People & Body) [Emoji]'
    '🧜: merperson (People & Body) [Emoji]'
    '🧜‍♀️: mermaid (People & Body) [Emoji]'
    '🧜‍♂️: merman (People & Body) [Emoji]'
    '🧝: elf (People & Body) [Emoji]'
    '🧝‍♀️: woman elf (People & Body) [Emoji]'
    '🧝‍♂️: man elf (People & Body) [Emoji]'
    '🧞: genie (People & Body) [Emoji]'
    '🧞‍♀️: woman genie (People & Body) [Emoji]'
    '🧞‍♂️: man genie (People & Body) [Emoji]'
    '🧟: zombie (People & Body) [Emoji]'
    '🧟‍♀️: woman zombie (People & Body) [Emoji]'
    '🧟‍♂️: man zombie (People & Body) [Emoji]'
    '🧠: brain (People & Body) [Emoji]'
    '🧡: orange heart (Smileys & Emotion) [Emoji]'
    '🧢: billed cap (Objects) [Emoji]'
    '🧣: scarf (Objects) [Emoji]'
    '🧤: gloves (Objects) [Emoji]'
    '🧥: coat (Objects) [Emoji]'
    '🧦: socks (Objects) [Emoji]'
    '🧧: red envelope (Activities) [Emoji]'
    '🧨: firecracker (Activities) [Emoji]'
    '🧩: puzzle piece (Activities) [Emoji]'
    '🧪: test tube (Objects) [Emoji]'
    '🧫: petri dish (Objects) [Emoji]'
    '🧬: dna (Objects) [Emoji]'
    '🧭: compass (Travel & Places) [Emoji]'
    '🧮: abacus (Objects) [Emoji]'
    '🧯: fire extinguisher (Objects) [Emoji]'
    '🧰: toolbox (Objects) [Emoji]'
    '🧱: brick (Travel & Places) [Emoji]'
    '🧲: magnet (Objects) [Emoji]'
    '🧳: luggage (Travel & Places) [Emoji]'
    '🧴: lotion bottle (Objects) [Emoji]'
    '🧵: thread (Activities) [Emoji]'
    '🧶: yarn (Activities) [Emoji]'
    '🧷: safety pin (Objects) [Emoji]'
    '🧸: teddy bear (Activities) [Emoji]'
    '🧹: broom (Objects) [Emoji]'
    '🧺: basket (Objects) [Emoji]'
    '🧻: roll of paper (Objects) [Emoji]'
    '🧼: soap (Objects) [Emoji]'
    '🧽: sponge (Objects) [Emoji]'
    '🧾: receipt (Objects) [Emoji]'
    '🧿: nazar amulet (Objects) [Emoji]'
    '🩰: ballet shoes (Objects) [Emoji]'
    '🩱: one-piece swimsuit (Objects) [Emoji]'
    '🩲: briefs (Objects) [Emoji]'
    '🩳: shorts (Objects) [Emoji]'
    '🩴: thong sandal (Objects) [Emoji]'
    '🩵: light blue heart (Smileys & Emotion) [Emoji]'
    '🩶: grey heart (Smileys & Emotion) [Emoji]'
    '🩷: pink heart (Smileys & Emotion) [Emoji]'
    '🩸: drop of blood (Objects) [Emoji]'
    '🩹: adhesive bandage (Objects) [Emoji]'
    '🩺: stethoscope (Objects) [Emoji]'
    '🩻: x-ray (Objects) [Emoji]'
    '🩼: crutch (Objects) [Emoji]'
    '🪀: yo-yo (Activities) [Emoji]'
    '🪁: kite (Activities) [Emoji]'
    '🪂: parachute (Travel & Places) [Emoji]'
    '🪃: boomerang (Objects) [Emoji]'
    '🪄: magic wand (Activities) [Emoji]'
    '🪅: piñata (Activities) [Emoji]'
    '🪆: nesting dolls (Activities) [Emoji]'
    '🪇: maracas (Objects) [Emoji]'
    '🪈: flute (Objects) [Emoji]'
    '🪉: harp (Objects) [Emoji]'
    '🪏: shovel (Objects) [Emoji]'
    '🪐: ringed planet (Travel & Places) [Emoji]'
    '🪑: chair (Objects) [Emoji]'
    '🪒: razor (Objects) [Emoji]'
    '🪓: axe (Objects) [Emoji]'
    '🪔: diya lamp (Objects) [Emoji]'
    '🪕: banjo (Objects) [Emoji]'
    '🪖: military helmet (Objects) [Emoji]'
    '🪗: accordion (Objects) [Emoji]'
    '🪘: long drum (Objects) [Emoji]'
    '🪙: coin (Objects) [Emoji]'
    '🪚: carpentry saw (Objects) [Emoji]'
    '🪛: screwdriver (Objects) [Emoji]'
    '🪜: ladder (Objects) [Emoji]'
    '🪝: hook (Objects) [Emoji]'
    '🪞: mirror (Objects) [Emoji]'
    '🪟: window (Objects) [Emoji]'
    '🪠: plunger (Objects) [Emoji]'
    '🪡: sewing needle (Activities) [Emoji]'
    '🪢: knot (Activities) [Emoji]'
    '🪣: bucket (Objects) [Emoji]'
    '🪤: mouse trap (Objects) [Emoji]'
    '🪥: toothbrush (Objects) [Emoji]'
    '🪦: headstone (Objects) [Emoji]'
    '🪧: placard (Objects) [Emoji]'
    '🪨: rock (Travel & Places) [Emoji]'
    '🪩: mirror ball (Activities) [Emoji]'
    '🪪: identification card (Objects) [Emoji]'
    '🪫: low battery (Objects) [Emoji]'
    '🪬: hamsa (Objects) [Emoji]'
    '🪭: folding hand fan (Objects) [Emoji]'
    '🪮: hair pick (Objects) [Emoji]'
    '🪯: khanda (Symbols) [Emoji]'
    '🪰: fly (Animals & Nature) [Emoji]'
    '🪱: worm (Animals & Nature) [Emoji]'
    '🪲: beetle (Animals & Nature) [Emoji]'
    '🪳: cockroach (Animals & Nature) [Emoji]'
    '🪴: potted plant (Animals & Nature) [Emoji]'
    '🪵: wood (Travel & Places) [Emoji]'
    '🪶: feather (Animals & Nature) [Emoji]'
    '🪷: lotus (Animals & Nature) [Emoji]'
    '🪸: coral (Animals & Nature) [Emoji]'
    '🪹: empty nest (Animals & Nature) [Emoji]'
    '🪺: nest with eggs (Animals & Nature) [Emoji]'
    '🪻: hyacinth (Animals & Nature) [Emoji]'
    '🪼: jellyfish (Animals & Nature) [Emoji]'
    '🪽: wing (Animals & Nature) [Emoji]'
    '🪾: leafless tree (Animals & Nature) [Emoji]'
    '🪿: goose (Animals & Nature) [Emoji]'
    '🫀: anatomical heart (People & Body) [Emoji]'
    '🫁: lungs (People & Body) [Emoji]'
    '🫂: people hugging (People & Body) [Emoji]'
    '🫃: pregnant man (People & Body) [Emoji]'
    '🫄: pregnant person (People & Body) [Emoji]'
    '🫅: person with crown (People & Body) [Emoji]'
    '🫆: fingerprint (People & Body) [Emoji]'
    '🫎: moose (Animals & Nature) [Emoji]'
    '🫏: donkey (Animals & Nature) [Emoji]'
    '🫐: blueberries (Food & Drink) [Emoji]'
    '🫑: bell pepper (Food & Drink) [Emoji]'
    '🫒: olive (Food & Drink) [Emoji]'
    '🫓: flatbread (Food & Drink) [Emoji]'
    '🫔: tamale (Food & Drink) [Emoji]'
    '🫕: fondue (Food & Drink) [Emoji]'
    '🫖: teapot (Food & Drink) [Emoji]'
    '🫗: pouring liquid (Food & Drink) [Emoji]'
    '🫘: beans (Food & Drink) [Emoji]'
    '🫙: jar (Food & Drink) [Emoji]'
    '🫚: ginger root (Food & Drink) [Emoji]'
    '🫛: pea pod (Food & Drink) [Emoji]'
    '🫜: root vegetable (Food & Drink) [Emoji]'
    '🫟: splatter (Symbols) [Emoji]'
    '🫠: melting face (Smileys & Emotion) [Emoji]'
    '🫡: saluting face (Smileys & Emotion) [Emoji]'
    '🫢: face with open eyes and hand over mouth (Smileys & Emotion) [Emoji]'
    '🫣: face with peeking eye (Smileys & Emotion) [Emoji]'
    '🫤: face with diagonal mouth (Smileys & Emotion) [Emoji]'
    '🫥: dotted line face (Smileys & Emotion) [Emoji]'
    '🫦: biting lip (People & Body) [Emoji]'
    '🫧: bubbles (Objects) [Emoji]'
    '🫨: shaking face (Smileys & Emotion) [Emoji]'
    '🫩: face with bags under eyes (Smileys & Emotion) [Emoji]'
    '🫰: hand with index finger and thumb crossed (People & Body) [Emoji]'
    '🫱: rightwards hand (People & Body) [Emoji]'
    '🫲: leftwards hand (People & Body) [Emoji]'
    '🫳: palm down hand (People & Body) [Emoji]'
    '🫴: palm up hand (People & Body) [Emoji]'
    '🫵: index pointing at the viewer (People & Body) [Emoji]'
    '🫶: heart hands (People & Body) [Emoji]'
    '🫷: leftwards pushing hand (People & Body) [Emoji]'
    '🫸: rightwards pushing hand (People & Body) [Emoji]'
)
